[package]
name = "ash-remote-connections"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[[bin]]
name = "ash-remote"
path = "src/main.rs"

[lib]
doctest = false
name = "ash_remote_connections"
path = "src/lib.rs"

[dependencies]
ash-utils-home-dir = { workspace = true }
ash-install-context = { workspace = true }
ash-app-server = { workspace = true }
build-info = { workspace = true }
ash-package-store = { workspace = true }
process-hardening = { workspace = true }
flate2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
ash-app-server-client = { workspace = true }
ash-app-server-protocol = { workspace = true }
ash-http-client = { workspace = true }
ash-remote = { workspace = true }
ash-utils-path = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
