use crate::AppServerListenInfo;
use crate::protocol::error::AppServerError;
use crate::protocol::registry::CLIENT_METHODS;
use crate::protocol::registry::ClientRequestSchema;
use crate::protocol::registry::ClientResultSchema;
use crate::protocol::registry::HOST_METHODS;
use crate::protocol::registry::HostRequestSchema;
use crate::protocol::registry::HostResultSchema;
use crate::protocol::registry::SERVER_NOTIFICATIONS;
use crate::protocol::registry::ServerNotificationSchema;
use crate::protocol::registry::TYPESCRIPT_BINDINGS;
use crate::rpc::JsonRpcError;
use crate::rpc::JsonRpcFailure;
use crate::rpc::JsonRpcNotification;
use crate::rpc::JsonRpcRequest;
use crate::rpc::JsonRpcResponse;
use crate::typescript_decoder;
use schemars::JsonSchema;
use schemars::Schema;
use schemars::schema_for;
use serde_json::Value;
use sha2::Digest;
use sha2::Sha256;
use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::path::Component;
use std::path::Path;
use std::path::PathBuf;

/// Checked-in JSON Schema fixture, relative to this crate's manifest directory.
pub const JSON_SCHEMA_FIXTURE: &str = "schema/json/schema.json";

/// Checked-in TypeScript fixture directory, relative to this crate's manifest directory.
pub const TYPESCRIPT_FIXTURE_DIRECTORY: &str = "schema/typescript";

/// Prefix that identifies TypeScript files owned by the protocol generator.
pub const GENERATED_TYPESCRIPT_HEADER: &str =
    "// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.\n";

#[allow(dead_code)]
#[derive(JsonSchema)]
#[schemars(title = "Zeta App Server Protocol")]
#[serde(rename_all = "camelCase")]
struct ProtocolSchema {
    listen_info: AppServerListenInfo,
    client_request: JsonRpcRequest<ClientRequestSchema>,
    client_response: JsonRpcResponse<ClientResultSchema, AppServerError>,
    host_request: JsonRpcRequest<HostRequestSchema>,
    host_response: JsonRpcResponse<HostResultSchema, JsonRpcError>,
    server_notification: JsonRpcNotification<ServerNotificationSchema>,
    error_response: JsonRpcFailure<AppServerError>,
}

fn generated_protocol() -> String {
    assert_typescript_bindings_are_closed();
    let schema_hash = schema_hash();
    format!(
        "{GENERATED_TYPESCRIPT_HEADER}\
         export const APP_SERVER_PROTOCOL_MAJOR = {} as const;\n\
         export const APP_SERVER_PROTOCOL_REVISION = {} as const;\n\
         export const APP_SERVER_CAPABILITY_VERSION = {} as const;\n\
         export const APP_SERVER_SCHEMA_HASH = {schema_hash:?} as const;\n\
         export type JsonRpcVersion = \"2.0\";\n\
         export type JsonRpcId = number | string | null;\n\
         export type JsonRpcRequest<P> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P }};\n\
         export type JsonRpcNotification<P> = {{ jsonrpc: JsonRpcVersion; method: string; params: P }};\n\
         export type JsonRpcSuccess<R> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R }};\n\
         export type JsonRpcFailure<E> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E }};\n\
         export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;\n\
         export type JsonRpcError = {{ code: number; message: string; data: unknown }};\n",
        crate::protocol::initialize::APP_SERVER_PROTOCOL_MAJOR,
        crate::protocol::initialize::APP_SERVER_PROTOCOL_REVISION,
        crate::protocol::initialize::APP_SERVER_CAPABILITY_VERSION,
    )
}

fn generated_request_map() -> String {
    let mut type_expressions = vec!["AppServerError".to_owned()];
    for method in CLIENT_METHODS {
        type_expressions.push(method.params_type());
        type_expressions.push(method.result_type());
    }

    let mut output = String::from(GENERATED_TYPESCRIPT_HEADER);
    output.push_str(&generated_type_imports(type_expressions));
    output.push_str("import type { JsonRpcRequest, JsonRpcResponse } from './protocol.js';\n\n");

    output.push_str("export interface AppServerRequestMap {\n");
    for method in CLIENT_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ params: {}; response: {} }};\n",
            method.method,
            method.params_type(),
            method.result_type()
        ));
    }
    output.push_str(
        "}\n\
         export type AppServerMethod = keyof AppServerRequestMap;\n\
         export type MethodParams<M extends AppServerMethod> = AppServerRequestMap[M][\"params\"];\n\
         export type MethodResult<M extends AppServerMethod> = AppServerRequestMap[M][\"response\"];\n\
         export type AppServerRequest<M extends AppServerMethod> = JsonRpcRequest<MethodParams<M>> & { method: M };\n\
         export type AppServerResponse<M extends AppServerMethod> = JsonRpcResponse<MethodResult<M>, AppServerError>;\n\
         export type AppServerMethodDefinition<M extends AppServerMethod> = {\n\
           readonly method: M;\n\
           readonly __params?: MethodParams<M>;\n\
           readonly __result?: MethodResult<M>;\n\
         };\n\
         export const APP_SERVER_METHODS: { [M in AppServerMethod]: AppServerMethodDefinition<M> } = {\n",
    );
    for method in CLIENT_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ method: {:?} }},\n",
            method.method, method.method
        ));
    }
    output.push_str("};\n");
    output
}

fn generated_notification_map() -> String {
    let type_expressions = SERVER_NOTIFICATIONS
        .iter()
        .map(|notification| notification.params_type())
        .collect::<Vec<_>>();
    let mut output = String::from(GENERATED_TYPESCRIPT_HEADER);
    output.push_str(&generated_type_imports(type_expressions));
    output.push_str("import type { JsonRpcVersion } from './protocol.js';\n\n");

    output.push_str("export interface AppServerNotificationMap {\n");
    for notification in SERVER_NOTIFICATIONS {
        output.push_str(&format!(
            "  {:?}: {};\n",
            notification.method,
            notification.params_type()
        ));
    }
    output.push_str(
        "}\n\
         export type AppServerNotificationMethod = keyof AppServerNotificationMap;\n\
         export type NotificationParams<M extends AppServerNotificationMethod> = AppServerNotificationMap[M];\n\
         export type ServerNotification = {\n\
           [M in AppServerNotificationMethod]: { method: M; params: NotificationParams<M> }\n\
         }[AppServerNotificationMethod];\n\
         export type AppServerWireNotification = {\n\
           [M in AppServerNotificationMethod]: { jsonrpc: JsonRpcVersion; method: M; params: NotificationParams<M> }\n\
         }[AppServerNotificationMethod];\n",
    );

    output.push_str(
        "export type AppServerNotificationDefinition<M extends AppServerNotificationMethod> = {\n\
           readonly method: M;\n\
           readonly __params?: NotificationParams<M>;\n\
         };\n\
         export const APP_SERVER_NOTIFICATIONS: {\n\
           [M in AppServerNotificationMethod]: AppServerNotificationDefinition<M>\n\
         } = {\n",
    );
    for notification in SERVER_NOTIFICATIONS {
        output.push_str(&format!(
            "  {:?}: {{ method: {:?} }},\n",
            notification.method, notification.method
        ));
    }
    output.push_str("};\n");
    output
}

fn generated_server_request_map() -> String {
    let mut type_expressions = Vec::new();
    for method in HOST_METHODS {
        type_expressions.push(method.params_type());
        type_expressions.push(method.result_type());
    }

    let mut output = String::from(GENERATED_TYPESCRIPT_HEADER);
    output.push_str(&generated_type_imports(type_expressions));
    output.push_str(
        "import type { JsonRpcError, JsonRpcRequest, JsonRpcResponse } from './protocol.js';\n\n",
    );
    output.push_str("export interface AppServerServerRequestMap {\n");
    for method in HOST_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ params: {}; response: {} }};\n",
            method.method,
            method.params_type(),
            method.result_type()
        ));
    }
    output.push_str(
        "}\n\
         export type AppServerServerRequestMethod = keyof AppServerServerRequestMap;\n\
         export type ServerRequestParams<M extends AppServerServerRequestMethod> = AppServerServerRequestMap[M][\"params\"];\n\
         export type ServerRequestResult<M extends AppServerServerRequestMethod> = AppServerServerRequestMap[M][\"response\"];\n\
         export type AppServerServerRequest<M extends AppServerServerRequestMethod> = JsonRpcRequest<ServerRequestParams<M>> & { method: M };\n\
         export type AppServerServerResponse<M extends AppServerServerRequestMethod> = JsonRpcResponse<ServerRequestResult<M>, JsonRpcError>;\n\
         export type AppServerServerRequestDefinition<M extends AppServerServerRequestMethod> = {\n\
           readonly method: M;\n\
           readonly __params?: ServerRequestParams<M>;\n\
           readonly __result?: ServerRequestResult<M>;\n\
         };\n\
         export const APP_SERVER_SERVER_REQUESTS: { [M in AppServerServerRequestMethod]: AppServerServerRequestDefinition<M> } = {\n",
    );
    for method in HOST_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ method: {:?} }},\n",
            method.method, method.method
        ));
    }
    output.push_str("};\n");
    output
}

/// Returns the complete generated TypeScript protocol file set.
pub fn typescript_files() -> Vec<(PathBuf, String)> {
    assert_typescript_bindings_are_closed();
    let schema = protocol_schema_value();
    let mut files = vec![
        (PathBuf::from("protocol.ts"), generated_protocol()),
        (
            PathBuf::from("AppServerRequestMap.ts"),
            generated_request_map(),
        ),
        (
            PathBuf::from("AppServerNotificationMap.ts"),
            generated_notification_map(),
        ),
        (
            PathBuf::from("AppServerServerRequestMap.ts"),
            generated_server_request_map(),
        ),
        (
            PathBuf::from("AppServerProtocolDecoder.ts"),
            typescript_decoder::generate(&schema),
        ),
        (
            PathBuf::from("AppServerListenInfo.ts"),
            generated_listen_info(),
        ),
        (PathBuf::from("types/index.ts"), generated_types_index()),
        (PathBuf::from("index.ts"), generated_index()),
    ];

    for binding in TYPESCRIPT_BINDINGS {
        files.push((
            PathBuf::from("types").join(binding_output_path(binding)),
            generated_binding(binding),
        ));
    }
    files.sort_by(|left, right| left.0.cmp(&right.0));
    files
}

fn generated_binding(binding: &crate::protocol::registry::TypeScriptBinding) -> String {
    let identifier = binding.identifier();
    let declaration = binding.declaration();
    let dependencies = registered_type_identifiers(std::slice::from_ref(&declaration))
        .into_iter()
        .filter(|dependency| dependency != &identifier)
        .collect::<BTreeSet<_>>();
    let mut output = String::from(GENERATED_TYPESCRIPT_HEADER);
    for dependency in &dependencies {
        output.push_str(&format!(
            "import type {{ {dependency} }} from './{dependency}.js';\n"
        ));
    }
    if !dependencies.is_empty() {
        output.push('\n');
    }
    output.push_str("export ");
    output.push_str(&declaration);
    output.push('\n');
    normalize_typescript(output)
}

fn generated_listen_info() -> String {
    format!(
        "{GENERATED_TYPESCRIPT_HEADER}export {}\n",
        <AppServerListenInfo as ts_rs::TS>::decl(&ts_rs::Config::default())
    )
}

fn generated_types_index() -> String {
    let mut bindings = TYPESCRIPT_BINDINGS.iter().collect::<Vec<_>>();
    bindings.sort_by_key(|binding| binding.identifier());
    let mut output = String::from(GENERATED_TYPESCRIPT_HEADER);
    for binding in bindings {
        output.push_str(&format!(
            "export type {{ {} }} from '{}';\n",
            binding.identifier(),
            typescript_module_path("./", &binding_output_path(binding))
        ));
    }
    output
}

fn generated_index() -> String {
    format!(
        "{GENERATED_TYPESCRIPT_HEADER}\
         export {{ APP_SERVER_CAPABILITY_VERSION, APP_SERVER_PROTOCOL_MAJOR, APP_SERVER_PROTOCOL_REVISION, APP_SERVER_SCHEMA_HASH }} from './protocol.js';\n\
         export type {{ JsonRpcError, JsonRpcFailure, JsonRpcId, JsonRpcNotification, JsonRpcRequest, JsonRpcResponse, JsonRpcSuccess, JsonRpcVersion }} from './protocol.js';\n\
         export type {{ AppServerListenInfo }} from './AppServerListenInfo.js';\n\
         export {{ APP_SERVER_METHODS }} from './AppServerRequestMap.js';\n\
         export type {{ AppServerMethod, AppServerMethodDefinition, AppServerRequest, AppServerRequestMap, AppServerResponse, MethodParams, MethodResult }} from './AppServerRequestMap.js';\n\
         export {{ APP_SERVER_NOTIFICATIONS }} from './AppServerNotificationMap.js';\n\
         export type {{ AppServerNotificationDefinition, AppServerNotificationMap, AppServerNotificationMethod, AppServerWireNotification, NotificationParams, ServerNotification }} from './AppServerNotificationMap.js';\n\
         export {{ APP_SERVER_SERVER_REQUESTS }} from './AppServerServerRequestMap.js';\n\
         export type {{ AppServerServerRequest, AppServerServerRequestDefinition, AppServerServerRequestMap, AppServerServerRequestMethod, AppServerServerResponse, ServerRequestParams, ServerRequestResult }} from './AppServerServerRequestMap.js';\n\
         export type * from './types/index.js';\n"
    )
}

fn generated_type_imports(type_expressions: Vec<String>) -> String {
    let identifiers = registered_type_identifiers(&type_expressions);
    let mut imports = BTreeMap::new();
    for binding in TYPESCRIPT_BINDINGS {
        let identifier = binding.identifier();
        if identifiers.contains(&identifier) {
            imports.insert(binding_output_path(binding), identifier);
        }
    }

    let mut output = String::new();
    for (path, identifier) in imports {
        output.push_str(&format!(
            "import type {{ {identifier} }} from '{}';\n",
            typescript_module_path("./types/", &path)
        ));
    }
    output
}

fn registered_type_identifiers(type_expressions: &[String]) -> BTreeSet<String> {
    let identifiers = type_expressions
        .iter()
        .flat_map(|expression| {
            expression
                .split(|character: char| !character.is_ascii_alphanumeric() && character != '_')
        })
        .collect::<BTreeSet<_>>();
    TYPESCRIPT_BINDINGS
        .iter()
        .map(|binding| binding.identifier())
        .filter(|identifier| identifiers.contains(identifier.as_str()))
        .collect()
}

fn typescript_module_path(prefix: &str, path: &Path) -> String {
    let mut path = path.to_path_buf();
    path.set_extension("js");
    format!("{prefix}{}", path.to_string_lossy().replace('\\', "/"))
}

fn normalize_typescript(output: String) -> String {
    let mut normalized = output
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    normalized.push('\n');
    normalized
}

fn binding_output_path(binding: &crate::protocol::registry::TypeScriptBinding) -> PathBuf {
    PathBuf::from(format!("{}.ts", binding.identifier()))
}

fn assert_typescript_bindings_are_closed() {
    let mut registered = BTreeSet::new();
    let mut output_paths = BTreeSet::new();
    for binding in TYPESCRIPT_BINDINGS {
        let identifier = binding.identifier();
        assert!(
            registered.insert(identifier.clone()),
            "duplicate TypeScript binding identifier: {identifier}"
        );
        assert!(
            identifier
                .chars()
                .all(|character| character.is_ascii_alphanumeric() || character == '_'),
            "invalid TypeScript binding identifier: {identifier}"
        );
        let output_path = binding_output_path(binding);
        assert!(
            !output_path.is_absolute()
                && output_path
                    .extension()
                    .is_some_and(|extension| extension == "ts")
                && output_path
                    .components()
                    .all(|component| matches!(component, Component::Normal(_))),
            "invalid TypeScript binding output path: {}",
            output_path.display()
        );
        assert!(
            output_paths.insert(output_path.clone()),
            "duplicate TypeScript binding output path: {}",
            output_path.display()
        );
    }
    let missing = TYPESCRIPT_BINDINGS
        .iter()
        .flat_map(|binding| binding.dependencies())
        .filter(|dependency| !registered.contains(dependency))
        .collect::<BTreeSet<_>>();

    assert!(
        missing.is_empty(),
        "TypeScript bindings are missing declarations for: {}",
        missing.into_iter().collect::<Vec<_>>().join(", ")
    );
}

pub fn json_schema() -> String {
    let schema = protocol_schema_value();
    let mut output =
        serde_json::to_string_pretty(&schema).expect("protocol schema must serialize as JSON");
    output.push('\n');
    output
}

pub fn schema_hash() -> String {
    let schema = protocol_schema_value();
    let canonical =
        serde_json::to_vec(&schema).expect("canonical protocol schema must serialize as JSON");
    let digest = Sha256::digest(canonical);
    format!("sha256:{digest:x}")
}

fn protocol_schema_value() -> Value {
    let mut schema =
        serde_json::to_value(protocol_schema()).expect("protocol schema must serialize as JSON");
    canonicalize_json(&mut schema);
    schema
}

fn canonicalize_json(value: &mut Value) {
    match value {
        Value::Array(values) => {
            for value in values {
                canonicalize_json(value);
            }
        }
        Value::Object(object) => {
            let mut entries = std::mem::take(object).into_iter().collect::<Vec<_>>();
            for (_, value) in &mut entries {
                canonicalize_json(value);
            }
            entries.sort_by(|left, right| left.0.cmp(&right.0));
            object.extend(entries);
        }
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {}
    }
}

fn protocol_schema() -> Schema {
    schema_for!(ProtocolSchema)
}
