use crate::protocol::error::AppServerError;
use crate::protocol::registry::CLIENT_METHODS;
use crate::protocol::registry::ClientRequestSchema;
use crate::protocol::registry::ClientResultSchema;
use crate::protocol::registry::HOST_METHODS;
use crate::protocol::registry::HostRequestSchema;
use crate::protocol::registry::HostResultSchema;
use crate::protocol::registry::SERVER_NOTIFICATIONS;
use crate::protocol::registry::ServerNotificationSchema;
use crate::protocol::registry::TYPESCRIPT_BINDINGS;
use crate::rpc::JsonRpcError;
use crate::rpc::JsonRpcFailure;
use crate::rpc::JsonRpcNotification;
use crate::rpc::JsonRpcRequest;
use crate::rpc::JsonRpcResponse;
use schemars::JsonSchema;
use schemars::Schema;
use schemars::schema_for;
use serde_json::Value;
use sha2::Digest;
use sha2::Sha256;
use std::collections::BTreeSet;

/// Checked-in JSON Schema fixture, relative to this crate's manifest directory.
pub const JSON_SCHEMA_FIXTURE: &str = "schema/json/schema.json";

/// Checked-in TypeScript fixture, relative to this crate's manifest directory.
pub const TYPESCRIPT_FIXTURE: &str = "schema/typescript/types.ts";

#[allow(dead_code)]
#[derive(JsonSchema)]
#[schemars(title = "Zeta App Server Protocol")]
#[serde(rename_all = "camelCase")]
struct ProtocolSchema {
    client_request: JsonRpcRequest<ClientRequestSchema>,
    client_response: JsonRpcResponse<ClientResultSchema, AppServerError>,
    host_request: JsonRpcRequest<HostRequestSchema>,
    host_response: JsonRpcResponse<HostResultSchema, JsonRpcError>,
    server_notification: JsonRpcNotification<ServerNotificationSchema>,
    error_response: JsonRpcFailure<AppServerError>,
}

pub fn typescript() -> String {
    assert_typescript_bindings_are_closed();
    let schema_hash = schema_hash();
    let mut output = format!(
        "// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.\n\
         export const APP_SERVER_PROTOCOL_MAJOR = {} as const;\n\
         export const APP_SERVER_PROTOCOL_REVISION = {} as const;\n\
         export const APP_SERVER_SCHEMA_HASH = {schema_hash:?} as const;\n\
         export type JsonRpcVersion = \"2.0\";\n\
         export type JsonRpcId = number | string | null;\n\
         export type JsonRpcRequest<P> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P }};\n\
         export type JsonRpcNotification<P> = {{ jsonrpc: JsonRpcVersion; method: string; params: P }};\n\
         export type JsonRpcSuccess<R> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R }};\n\
         export type JsonRpcFailure<E> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E }};\n\
         export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;\n\
         export type JsonRpcError = {{ code: number; message: string; data: unknown }};\n",
        crate::protocol::initialize::APP_SERVER_PROTOCOL_MAJOR,
        crate::protocol::initialize::APP_SERVER_PROTOCOL_REVISION,
    );
    for binding in TYPESCRIPT_BINDINGS {
        output.push_str("export ");
        output.push_str(&binding.declaration());
        output.push('\n');
    }

    output.push_str("export type ServerNotification =\n");
    for (index, notification) in SERVER_NOTIFICATIONS.iter().enumerate() {
        let prefix = if index == 0 { "  " } else { "  | " };
        output.push_str(&format!(
            "{prefix}{{ method: {:?}; params: {} }}\n",
            notification.method,
            notification.params_type()
        ));
    }
    output.push_str(";\n");

    output.push_str(
        "export type AppServerWireNotification = JsonRpcNotification<ServerNotification>;\n",
    );

    output.push_str("export interface AppServerMethodMap {\n");
    for method in CLIENT_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ params: {}; result: {} }};\n",
            method.method,
            method.params_type(),
            method.result_type()
        ));
    }
    output.push_str(
        "}\n\
         export type AppServerMethod = keyof AppServerMethodMap;\n\
         export type MethodParams<M extends AppServerMethod> = AppServerMethodMap[M][\"params\"];\n\
         export type MethodResult<M extends AppServerMethod> = AppServerMethodMap[M][\"result\"];\n\
         export type AppServerRequest<M extends AppServerMethod> = JsonRpcRequest<MethodParams<M>>;\n\
         export type AppServerResponse<M extends AppServerMethod> = JsonRpcResponse<MethodResult<M>, AppServerError>;\n\
         export type AppServerMethodDefinition<M extends AppServerMethod> = {\n\
           readonly method: M;\n\
           readonly __params?: MethodParams<M>;\n\
           readonly __result?: MethodResult<M>;\n\
         };\n\
         export const APP_SERVER_METHODS: { [M in AppServerMethod]: AppServerMethodDefinition<M> } = {\n",
    );
    for method in CLIENT_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ method: {:?} }},\n",
            method.method, method.method
        ));
    }
    output.push_str("};\n");

    output.push_str(
        "export type AppServerNotificationMethod = ServerNotification[\"method\"];\n\
         export type NotificationParams<M extends AppServerNotificationMethod> =\n\
           Extract<ServerNotification, { method: M }>[\"params\"];\n\
         export type AppServerNotificationDefinition<M extends AppServerNotificationMethod> = {\n\
           readonly method: M;\n\
           readonly __params?: NotificationParams<M>;\n\
         };\n\
         export const APP_SERVER_NOTIFICATIONS: {\n\
           [M in AppServerNotificationMethod]: AppServerNotificationDefinition<M>\n\
         } = {\n",
    );
    for notification in SERVER_NOTIFICATIONS {
        output.push_str(&format!(
            "  {:?}: {{ method: {:?} }},\n",
            notification.method, notification.method
        ));
    }
    output.push_str("};\n");
    output.push_str("export interface AppServerHostMethodMap {\n");
    for method in HOST_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ params: {}; result: {} }};\n",
            method.method,
            method.params_type(),
            method.result_type()
        ));
    }
    output.push_str(
        "}\n\
         export type AppServerHostMethod = keyof AppServerHostMethodMap;\n\
         export type HostMethodParams<M extends AppServerHostMethod> = AppServerHostMethodMap[M][\"params\"];\n\
         export type HostMethodResult<M extends AppServerHostMethod> = AppServerHostMethodMap[M][\"result\"];\n\
         export type AppServerHostRequest<M extends AppServerHostMethod> = JsonRpcRequest<HostMethodParams<M>>;\n\
         export type AppServerHostResponse<M extends AppServerHostMethod> = JsonRpcResponse<HostMethodResult<M>, JsonRpcError>;\n\
         export type AppServerHostMethodDefinition<M extends AppServerHostMethod> = {\n\
           readonly method: M;\n\
           readonly __params?: HostMethodParams<M>;\n\
           readonly __result?: HostMethodResult<M>;\n\
         };\n\
         export const APP_SERVER_HOST_METHODS: { [M in AppServerHostMethod]: AppServerHostMethodDefinition<M> } = {\n",
    );
    for method in HOST_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ method: {:?} }},\n",
            method.method, method.method
        ));
    }
    output.push_str("};\n");
    let mut normalized = output
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    normalized.push('\n');
    normalized
}

fn assert_typescript_bindings_are_closed() {
    let registered = TYPESCRIPT_BINDINGS
        .iter()
        .map(|binding| binding.identifier())
        .collect::<BTreeSet<_>>();
    let missing = TYPESCRIPT_BINDINGS
        .iter()
        .flat_map(|binding| binding.dependencies())
        .filter(|dependency| !registered.contains(dependency))
        .collect::<BTreeSet<_>>();

    assert!(
        missing.is_empty(),
        "TypeScript bindings are missing declarations for: {}",
        missing.into_iter().collect::<Vec<_>>().join(", ")
    );
}

pub fn json_schema() -> String {
    let mut schema =
        serde_json::to_value(protocol_schema()).expect("protocol schema must serialize as JSON");
    canonicalize_json(&mut schema);
    let mut output =
        serde_json::to_string_pretty(&schema).expect("protocol schema must serialize as JSON");
    output.push('\n');
    output
}

pub fn schema_hash() -> String {
    let mut schema =
        serde_json::to_value(protocol_schema()).expect("protocol schema must serialize as JSON");
    canonicalize_json(&mut schema);
    let canonical =
        serde_json::to_vec(&schema).expect("canonical protocol schema must serialize as JSON");
    let digest = Sha256::digest(canonical);
    format!("sha256:{digest:x}")
}

fn canonicalize_json(value: &mut Value) {
    match value {
        Value::Array(values) => {
            for value in values {
                canonicalize_json(value);
            }
        }
        Value::Object(object) => {
            let mut entries = std::mem::take(object).into_iter().collect::<Vec<_>>();
            for (_, value) in &mut entries {
                canonicalize_json(value);
            }
            entries.sort_by(|left, right| left.0.cmp(&right.0));
            object.extend(entries);
        }
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {}
    }
}

fn protocol_schema() -> Schema {
    schema_for!(ProtocolSchema)
}
