use crate::protocol::error::AppServerError;
use crate::protocol::registry::{
    CLIENT_METHODS, ClientRequestSchema, ClientResultSchema, SERVER_NOTIFICATIONS,
    ServerNotificationSchema, TYPESCRIPT_BINDINGS,
};
use crate::rpc::{JsonRpcFailure, JsonRpcNotification, JsonRpcRequest, JsonRpcResponse};
use schemars::{JsonSchema, Schema, schema_for};
use sha2::{Digest, Sha256};

/// Checked-in JSON Schema fixture, relative to this crate's manifest directory.
pub const JSON_SCHEMA_FIXTURE: &str = "schema/schema.json";

/// Checked-in TypeScript fixture, relative to this crate's manifest directory.
pub const TYPESCRIPT_FIXTURE: &str = "schema/types.ts";

#[allow(dead_code)]
#[derive(JsonSchema)]
#[schemars(title = "Zeta App Server Protocol")]
#[serde(rename_all = "camelCase")]
struct ProtocolSchema {
    client_request: JsonRpcRequest<ClientRequestSchema>,
    client_response: JsonRpcResponse<ClientResultSchema, AppServerError>,
    server_notification: JsonRpcNotification<ServerNotificationSchema>,
    error_response: JsonRpcFailure<AppServerError>,
}

pub fn typescript() -> String {
    let schema_hash = schema_hash();
    let mut output = format!(
        "// Generated by `zeta-app-server-protocol export`. Do not edit.\n\
         export const APP_SERVER_SCHEMA_HASH = {schema_hash:?} as const;\n\
         export type JsonRpcVersion = \"2.0\";\n\
         export type JsonRpcId = number | string | null;\n\
         export type JsonRpcRequest<P> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P }};\n\
         export type JsonRpcNotification<P> = {{ jsonrpc: JsonRpcVersion; method: string; params: P }};\n\
         export type JsonRpcSuccess<R> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R }};\n\
         export type JsonRpcFailure<E> = {{ jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E }};\n\
         export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;\n"
    );
    for binding in TYPESCRIPT_BINDINGS {
        output.push_str("export ");
        output.push_str(&binding.declaration());
        output.push('\n');
    }

    output.push_str("export type ServerNotification =\n");
    for (index, notification) in SERVER_NOTIFICATIONS.iter().enumerate() {
        let prefix = if index == 0 { "  " } else { "  | " };
        output.push_str(&format!(
            "{prefix}{{ method: {:?}; params: {} }}\n",
            notification.method,
            notification.params_type()
        ));
    }
    output.push_str(";\n");

    output.push_str(
        "export type AppServerWireNotification = JsonRpcNotification<ServerNotification>;\n",
    );

    output.push_str("export interface AppServerMethodMap {\n");
    for method in CLIENT_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ params: {}; result: {} }};\n",
            method.method,
            method.params_type(),
            method.result_type()
        ));
    }
    output.push_str(
        "}\n\
         export type AppServerMethod = keyof AppServerMethodMap;\n\
         export type MethodParams<M extends AppServerMethod> = AppServerMethodMap[M][\"params\"];\n\
         export type MethodResult<M extends AppServerMethod> = AppServerMethodMap[M][\"result\"];\n\
         export type AppServerRequest<M extends AppServerMethod> = JsonRpcRequest<MethodParams<M>>;\n\
         export type AppServerResponse<M extends AppServerMethod> = JsonRpcResponse<MethodResult<M>, AppServerError>;\n\
         export type AppServerMethodDefinition<M extends AppServerMethod> = {\n\
           readonly method: M;\n\
           readonly __params?: MethodParams<M>;\n\
           readonly __result?: MethodResult<M>;\n\
         };\n\
         export const APP_SERVER_METHODS: { [M in AppServerMethod]: AppServerMethodDefinition<M> } = {\n",
    );
    for method in CLIENT_METHODS {
        output.push_str(&format!(
            "  {:?}: {{ method: {:?} }},\n",
            method.method, method.method
        ));
    }
    output.push_str("};\n");

    output.push_str(
        "export type AppServerNotificationMethod = ServerNotification[\"method\"];\n\
         export type NotificationParams<M extends AppServerNotificationMethod> =\n\
           Extract<ServerNotification, { method: M }>[\"params\"];\n\
         export type AppServerNotificationDefinition<M extends AppServerNotificationMethod> = {\n\
           readonly method: M;\n\
           readonly __params?: NotificationParams<M>;\n\
         };\n\
         export const APP_SERVER_NOTIFICATIONS: {\n\
           [M in AppServerNotificationMethod]: AppServerNotificationDefinition<M>\n\
         } = {\n",
    );
    for notification in SERVER_NOTIFICATIONS {
        output.push_str(&format!(
            "  {:?}: {{ method: {:?} }},\n",
            notification.method, notification.method
        ));
    }
    output.push_str("};\n");
    output
}

pub fn json_schema() -> String {
    let schema = protocol_schema();
    let mut output =
        serde_json::to_string_pretty(&schema).expect("protocol schema must serialize as JSON");
    output.push('\n');
    output
}

pub fn schema_hash() -> String {
    let canonical =
        serde_json::to_vec(&protocol_schema()).expect("protocol schema must serialize as JSON");
    let digest = Sha256::digest(canonical);
    format!("sha256:{digest:x}")
}

fn protocol_schema() -> Schema {
    schema_for!(ProtocolSchema)
}
