const TYPESCRIPT_V1: &str = r#"// Generated by `zeta app-server generate-ts`. Do not edit.
export type ProtocolVersion = 1;
export type ThreadId = string;
export type TurnId = string;
export type TurnStatus =
  | "created" | "running" | "waitingForApproval" | "waitingForUserInput"
  | "waitingForCapability" | "cancelling" | "completed" | "failed" | "interrupted";
export type Theme = "light" | "dark" | "system";
export interface ModelRef {
  provider: string;
  model: string;
}
export interface BrowserCapability {
  version: number;
  observe: boolean;
  input: boolean;
}
export interface ClientCapabilities {
  notifications?: boolean;
  browser?: BrowserCapability | null;
}
export interface InitializeParams {
  clientInfo: { name: string; version: string };
  protocolVersions: { min: number; max: number };
  capabilities: ClientCapabilities;
}
export interface InitializeResult {
  serverInfo: { name: string; version: string };
  protocolVersion: ProtocolVersion;
  schemaHash: string;
  capabilities: { threads: boolean; turns: boolean; resources: boolean };
}
export interface ThreadStartParams { idempotencyKey: string; title: string; }
export interface ThreadStartResult { threadId: ThreadId; sequence: number; }
export interface ThreadReadParams { threadId: ThreadId; }
export interface ThreadResumeParams { threadId: ThreadId; }
export interface ThreadUnsubscribeParams { threadId: ThreadId; }
export interface Turn {
  turnId: TurnId;
  status: TurnStatus;
}
export interface Thread {
  threadId: ThreadId;
  title: string;
  sequence: number;
  turns: Turn[];
}
export interface ThreadReadResult { thread: Thread; }
export interface ThreadListResult { threads: Thread[]; }
export interface TurnStartParams { idempotencyKey: string; threadId: ThreadId; input: Array<{ type: "text"; text: string }>; }
export interface TurnStartResult { turnId: TurnId; sequence: number; }
export interface TurnInterruptParams { threadId: ThreadId; turnId: TurnId; }
export interface ConfigReadResult {
  preferredModel: ModelRef | null;
  theme: Theme | null;
}
export interface ConfigUpdateParams {
  idempotencyKey: string;
  preferredModel?: ModelRef | null;
  theme?: Theme | null;
}
export interface ThreadStartedNotification { threadId: ThreadId; sequence: number; }
export interface TurnStartedNotification { threadId: ThreadId; turnId: TurnId; sequence: number; }
export interface AgentMessageCompletedNotification { threadId: ThreadId; turnId: TurnId; text: string; sequence: number; }
export interface TurnCompletedNotification { threadId: ThreadId; turnId: TurnId; sequence: number; }
export interface TurnInterruptedNotification { threadId: ThreadId; turnId: TurnId; sequence: number; }
export interface ResourceMetadataParams { resourceId: string; }
export interface ResourceMetadataResult { resourceId: string; mimeType: string; size: number; sha256: string; }
export interface ResourceReadParams { resourceId: string; offset: number; maxBytes: number; }
export interface ResourceReadResult { resourceId: string; offset: number; data: number[]; eof: boolean; }
export interface ResourceReleaseParams { resourceId: string; }
export type ServerNotification =
  | { method: "thread/started"; params: ThreadStartedNotification }
  | { method: "turn/started"; params: TurnStartedNotification }
  | { method: "item/agentMessage/completed"; params: AgentMessageCompletedNotification }
  | { method: "turn/completed"; params: TurnCompletedNotification }
  | { method: "turn/interrupted"; params: TurnInterruptedNotification };
export interface AppServerMethodMap {
  "initialize": { params: InitializeParams; result: InitializeResult };
  "thread/start": { params: ThreadStartParams; result: ThreadStartResult };
  "thread/read": { params: ThreadReadParams; result: ThreadReadResult };
  "thread/resume": { params: ThreadResumeParams; result: ThreadReadResult };
  "thread/list": { params: Record<string, never>; result: ThreadListResult };
  "thread/unsubscribe": { params: ThreadUnsubscribeParams; result: null };
  "config/read": { params: Record<string, never>; result: ConfigReadResult };
  "config/update": { params: ConfigUpdateParams; result: ConfigReadResult };
  "turn/start": { params: TurnStartParams; result: TurnStartResult };
  "turn/interrupt": { params: TurnInterruptParams; result: null };
  "resource/metadata": { params: ResourceMetadataParams; result: ResourceMetadataResult };
  "resource/read": { params: ResourceReadParams; result: ResourceReadResult };
  "resource/release": { params: ResourceReleaseParams; result: null };
}
export type AppServerMethod = keyof AppServerMethodMap;
export type MethodParams<M extends AppServerMethod> = AppServerMethodMap[M]["params"];
export type MethodResult<M extends AppServerMethod> = AppServerMethodMap[M]["result"];
export type AppServerErrorName =
  | "ParseError" | "InvalidRequest" | "MethodNotFound" | "InvalidParams"
  | "InternalError" | "ServerOverloaded" | "NotInitialized" | "AlreadyInitialized"
  | "ProtocolVersionUnsupported" | "IdempotencyConflict" | "CoreOperationFailed"
  | "ResourceNotFound" | "ResourceNotOwner" | "ResourceTooLarge"
  | "InvalidResourceChunkSize" | "InvalidResourceOffset" | "ConfigUnavailable";
export interface AppServerError {
  code: number;
  message: AppServerErrorName;
  data: null;
}
"#;

const JSON_SCHEMA_V1: &str = r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Zeta App Server Protocol v1",
  "type": "object",
  "definitions": {
    "threadId": { "type": "string", "minLength": 1 },
    "turnId": { "type": "string", "minLength": 1 },
    "turnStatus": {
      "type": "string",
      "enum": ["created", "running", "waitingForApproval", "waitingForUserInput", "waitingForCapability", "cancelling", "completed", "failed", "interrupted"]
    },
    "theme": { "type": "string", "enum": ["light", "dark", "system"] },
    "modelRef": {
      "type": "object",
      "required": ["provider", "model"],
      "properties": {
        "provider": { "type": "string", "minLength": 1 },
        "model": { "type": "string", "minLength": 1 }
      }
    },
    "initializeParams": {
      "type": "object",
      "required": ["clientInfo", "protocolVersions", "capabilities"],
      "properties": {
        "clientInfo": {
          "type": "object",
          "required": ["name", "version"],
          "properties": { "name": { "type": "string" }, "version": { "type": "string" } }
        },
        "protocolVersions": {
          "type": "object",
          "required": ["min", "max"],
          "properties": { "min": { "type": "integer", "minimum": 1 }, "max": { "type": "integer", "minimum": 1 } }
        },
        "capabilities": { "type": "object" }
      }
    },
    "initializeResult": {
      "type": "object",
      "required": ["serverInfo", "protocolVersion", "schemaHash", "capabilities"]
    },
    "threadStartParams": {
      "type": "object",
      "required": ["idempotencyKey", "title"],
      "properties": { "idempotencyKey": { "type": "string", "minLength": 1 }, "title": { "type": "string" } }
    },
    "threadStartResult": {
      "type": "object",
      "required": ["threadId", "sequence"],
      "properties": { "threadId": { "$ref": "#/definitions/threadId" }, "sequence": { "type": "integer", "minimum": 0 } }
    },
    "threadReadParams": {
      "type": "object",
      "required": ["threadId"],
      "properties": { "threadId": { "$ref": "#/definitions/threadId" } }
    },
    "threadResumeParams": {
      "type": "object",
      "required": ["threadId"],
      "properties": { "threadId": { "$ref": "#/definitions/threadId" } }
    },
    "threadUnsubscribeParams": {
      "type": "object",
      "required": ["threadId"],
      "properties": { "threadId": { "$ref": "#/definitions/threadId" } }
    },
    "turn": {
      "type": "object",
      "required": ["turnId", "status"],
      "properties": { "turnId": { "$ref": "#/definitions/turnId" }, "status": { "$ref": "#/definitions/turnStatus" } }
    },
    "thread": {
      "type": "object",
      "required": ["threadId", "title", "sequence", "turns"],
      "properties": {
        "threadId": { "$ref": "#/definitions/threadId" },
        "title": { "type": "string" },
        "sequence": { "type": "integer", "minimum": 0 },
        "turns": { "type": "array", "items": { "$ref": "#/definitions/turn" } }
      }
    },
    "threadReadResult": {
      "type": "object",
      "required": ["thread"],
      "properties": { "thread": { "$ref": "#/definitions/thread" } }
    },
    "threadListResult": {
      "type": "object",
      "required": ["threads"],
      "properties": { "threads": { "type": "array", "items": { "$ref": "#/definitions/thread" } } }
    },
    "turnStartParams": {
      "type": "object",
      "required": ["idempotencyKey", "threadId", "input"],
      "properties": {
        "idempotencyKey": { "type": "string", "minLength": 1 },
        "threadId": { "$ref": "#/definitions/threadId" },
        "input": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": ["type", "text"],
            "properties": { "type": { "const": "text" }, "text": { "type": "string" } }
          }
        }
      }
    },
    "turnStartResult": {
      "type": "object",
      "required": ["turnId", "sequence"],
      "properties": { "turnId": { "$ref": "#/definitions/turnId" }, "sequence": { "type": "integer", "minimum": 0 } }
    },
    "turnInterruptParams": {
      "type": "object",
      "required": ["threadId", "turnId"],
      "properties": { "threadId": { "$ref": "#/definitions/threadId" }, "turnId": { "$ref": "#/definitions/turnId" } }
    },
    "configReadResult": {
      "type": "object",
      "required": ["preferredModel", "theme"],
      "properties": {
        "preferredModel": {
          "anyOf": [{ "$ref": "#/definitions/modelRef" }, { "type": "null" }]
        },
        "theme": { "anyOf": [{ "$ref": "#/definitions/theme" }, { "type": "null" }] }
      }
    },
    "configUpdateParams": {
      "type": "object",
      "required": ["idempotencyKey"],
      "properties": {
        "idempotencyKey": { "type": "string", "minLength": 1 },
        "preferredModel": {
          "anyOf": [{ "$ref": "#/definitions/modelRef" }, { "type": "null" }]
        },
        "theme": { "anyOf": [{ "$ref": "#/definitions/theme" }, { "type": "null" }] }
      }
    },
    "resourceMetadataParams": {
      "type": "object",
      "required": ["resourceId"],
      "properties": { "resourceId": { "type": "string", "minLength": 1 } }
    },
    "resourceMetadataResult": {
      "type": "object",
      "required": ["resourceId", "mimeType", "size", "sha256"]
    },
    "resourceReadParams": {
      "type": "object",
      "required": ["resourceId", "offset", "maxBytes"],
      "properties": {
        "resourceId": { "type": "string", "minLength": 1 },
        "offset": { "type": "integer", "minimum": 0 },
        "maxBytes": { "type": "integer", "minimum": 1, "maximum": 262144 }
      }
    },
    "resourceReadResult": {
      "type": "object",
      "required": ["resourceId", "offset", "data", "eof"]
    },
    "resourceReleaseParams": {
      "type": "object",
      "required": ["resourceId"],
      "properties": { "resourceId": { "type": "string", "minLength": 1 } }
    },
    "threadStartedNotification": {
      "type": "object",
      "required": ["threadId", "sequence"]
    },
    "turnStartedNotification": {
      "type": "object",
      "required": ["threadId", "turnId", "sequence"]
    },
    "agentMessageCompletedNotification": {
      "type": "object",
      "required": ["threadId", "turnId", "text", "sequence"]
    },
    "turnCompletedNotification": {
      "type": "object",
      "required": ["threadId", "turnId", "sequence"]
    },
    "turnInterruptedNotification": {
      "type": "object",
      "required": ["threadId", "turnId", "sequence"]
    },
    "appServerError": {
      "type": "object",
      "required": ["code", "message", "data"],
      "properties": {
        "code": { "type": "integer" },
        "message": {
          "type": "string",
          "enum": ["ParseError", "InvalidRequest", "MethodNotFound", "InvalidParams", "InternalError", "ServerOverloaded", "NotInitialized", "AlreadyInitialized", "ProtocolVersionUnsupported", "IdempotencyConflict", "CoreOperationFailed", "ResourceNotFound", "ResourceNotOwner", "ResourceTooLarge", "InvalidResourceChunkSize", "InvalidResourceOffset", "ConfigUnavailable"]
        },
        "data": { "type": "null" }
      }
    }
  }
}
"##;

pub fn typescript_v1() -> &'static str {
    TYPESCRIPT_V1
}
pub fn json_schema_v1() -> &'static str {
    JSON_SCHEMA_V1
}

pub fn schema_hash_v1() -> String {
    let hash = TYPESCRIPT_V1
        .as_bytes()
        .iter()
        .chain(JSON_SCHEMA_V1.as_bytes())
        .fold(0xcbf29ce484222325_u64, |hash, byte| {
            (hash ^ u64::from(*byte)).wrapping_mul(0x100000001b3)
        });
    format!("fnv1a64:{hash:016x}")
}
