// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AppServerError, AppServerListenInfo, AppServerMethod, AppServerResponse, AppServerServerRequest, AppServerServerRequestMethod, AppServerServerResponse, AppServerWireNotification, JsonRpcError, JsonRpcId, MethodParams, MethodResult, ServerRequestParams, ServerRequestResult } from './types.js';

type JsonSchema = boolean | {
	readonly $defs?: Readonly<Record<string, JsonSchema>>;
	readonly $ref?: string;
	readonly type?: string | readonly string[];
	readonly const?: unknown;
	readonly enum?: readonly unknown[];
	readonly oneOf?: readonly JsonSchema[];
	readonly anyOf?: readonly JsonSchema[];
	readonly properties?: Readonly<Record<string, JsonSchema>>;
	readonly required?: readonly string[];
	readonly additionalProperties?: boolean | JsonSchema;
	readonly unevaluatedProperties?: boolean | JsonSchema;
	readonly items?: JsonSchema;
	readonly minimum?: number;
	readonly maximum?: number;
	readonly minLength?: number;
	readonly maxLength?: number;
	readonly minItems?: number;
	readonly maxItems?: number;
	readonly uniqueItems?: boolean;
};

const protocolSchema = JSON.parse(__PROTOCOL_SCHEMA__) as JsonSchema;

export type DecodedAppServerEnvelope =
	| { readonly kind: 'response'; readonly id: JsonRpcId; readonly result: unknown }
	| { readonly kind: 'error'; readonly id: JsonRpcId; readonly error: unknown }
	| { readonly kind: 'notification'; readonly method: string; readonly params: unknown }
	| { readonly kind: 'serverRequest'; readonly id: JsonRpcId; readonly method: string; readonly params: unknown };

export class AppServerProtocolDecodeError extends Error {
	public constructor(public readonly path: string, message: string) {
		super(`${path}: ${message}`);
		this.name = 'AppServerProtocolDecodeError';
	}
}

export function decodeAppServerEnvelope(value: unknown): DecodedAppServerEnvelope {
	const envelope = record(value, '$');
	if (envelope.jsonrpc !== '2.0') throw failure('$.jsonrpc', 'expected "2.0"');
	if (typeof envelope.method === 'string') {
		if (!Object.hasOwn(envelope, 'params')) throw failure('$.params', 'missing required field');
		if (Object.hasOwn(envelope, 'id')) {
			exactKeys(envelope, ['jsonrpc', 'id', 'method', 'params'], '$');
			assertJsonRpcId(envelope.id, '$.id');
			return { kind: 'serverRequest', id: envelope.id, method: envelope.method, params: envelope.params };
		}
		exactKeys(envelope, ['jsonrpc', 'method', 'params'], '$');
		return { kind: 'notification', method: envelope.method, params: envelope.params };
	}
	if (!Object.hasOwn(envelope, 'id')) throw failure('$.id', 'missing required field');
	assertJsonRpcId(envelope.id, '$.id');
	const hasResult = Object.hasOwn(envelope, 'result');
	const hasError = Object.hasOwn(envelope, 'error');
	if (hasResult === hasError) throw failure('$', 'expected exactly one result or error field');
	if (hasResult) {
		exactKeys(envelope, ['jsonrpc', 'id', 'result'], '$');
		return { kind: 'response', id: envelope.id, result: envelope.result };
	}
	exactKeys(envelope, ['jsonrpc', 'id', 'error'], '$');
	return { kind: 'error', id: envelope.id, error: envelope.error };
}

export function decodeAppServerListenInfo(value: unknown): AppServerListenInfo {
	assertDefinition('AppServerListenInfo', value, '$');
	const listenInfo = value as AppServerListenInfo;
	const match = /^ws:\/\/(127(?:\.\d{1,3}){3}|\[::1\]):([0-9]+)$/.exec(listenInfo.endpoint);
	if (!match) throw failure('$.endpoint', 'expected an explicit loopback WebSocket endpoint');
	if (match[1].startsWith('127.') && match[1].split('.').some(part => Number(part) > 255)) {
		throw failure('$.endpoint', 'invalid IPv4 loopback address');
	}
	const port = Number(match[2]);
	if (!Number.isSafeInteger(port) || port < 1 || port > 65_535) throw failure('$.endpoint', 'invalid port');
	return listenInfo;
}

export function decodeAppServerRequestParams<M extends AppServerMethod>(method: M, value: unknown): MethodParams<M> {
	assertDefinition('ClientRequestSchema', { method, params: value }, '$');
	return value as MethodParams<M>;
}

export function decodeAppServerResult<M extends AppServerMethod>(method: M, value: unknown): MethodResult<M> {
	assertDefinition('ClientResultSchema', { method, result: value }, '$');
	return value as MethodResult<M>;
}

export function decodeAppServerResponse<M extends AppServerMethod>(method: M, value: unknown): AppServerResponse<M> {
	const envelope = decodeAppServerEnvelope(value);
	if (envelope.kind === 'response') {
		return { jsonrpc: '2.0', id: envelope.id, result: decodeAppServerResult(method, envelope.result) };
	}
	if (envelope.kind === 'error') {
		return { jsonrpc: '2.0', id: envelope.id, error: decodeAppServerError(envelope.error) };
	}
	throw failure('$', 'expected a client response');
}

export function decodeAppServerNotification(value: unknown): AppServerWireNotification {
	const envelope = decodeAppServerEnvelope(value);
	if (envelope.kind !== 'notification') throw failure('$', 'expected a server notification');
	assertDefinition('ServerNotificationSchema', { method: envelope.method, params: envelope.params }, '$');
	return { jsonrpc: '2.0', method: envelope.method, params: envelope.params } as AppServerWireNotification;
}

export function decodeAppServerServerRequest(value: unknown): AppServerServerRequest<AppServerServerRequestMethod> {
	const envelope = decodeAppServerEnvelope(value);
	if (envelope.kind !== 'serverRequest') throw failure('$', 'expected a server request');
	assertDefinition('HostRequestSchema', { method: envelope.method, params: envelope.params }, '$');
	return { jsonrpc: '2.0', id: envelope.id, method: envelope.method, params: envelope.params } as AppServerServerRequest<AppServerServerRequestMethod>;
}

export function decodeAppServerServerRequestParams<M extends AppServerServerRequestMethod>(method: M, value: unknown): ServerRequestParams<M> {
	assertDefinition('HostRequestSchema', { method, params: value }, '$');
	return value as ServerRequestParams<M>;
}

export function decodeAppServerServerRequestResult<M extends AppServerServerRequestMethod>(method: M, value: unknown): ServerRequestResult<M> {
	assertDefinition('HostResultSchema', { method, result: value }, '$');
	return value as ServerRequestResult<M>;
}

export function decodeAppServerServerResponse<M extends AppServerServerRequestMethod>(method: M, value: unknown): AppServerServerResponse<M> {
	const envelope = decodeAppServerEnvelope(value);
	if (envelope.kind === 'response') {
		return { jsonrpc: '2.0', id: envelope.id, result: decodeAppServerServerRequestResult(method, envelope.result) };
	}
	if (envelope.kind === 'error') {
		return { jsonrpc: '2.0', id: envelope.id, error: decodeJsonRpcError(envelope.error) };
	}
	throw failure('$', 'expected a host response');
}

export function decodeAppServerError(value: unknown): AppServerError {
	assertDefinition('AppServerError', value, '$.error');
	return value as AppServerError;
}

export function decodeJsonRpcError(value: unknown): JsonRpcError {
	assertDefinition('JsonRpcError', value, '$.error');
	return value as JsonRpcError;
}

function assertDefinition(name: string, value: unknown, path: string): void {
	const definitions = typeof protocolSchema === 'boolean' ? undefined : protocolSchema.$defs;
	const schema = definitions?.[name];
	if (!schema) throw failure(path, `generated schema definition is missing: ${name}`);
	validate(schema, value, path);
}

function validate(schema: JsonSchema, value: unknown, path: string): void {
	if (schema === true) return;
	if (schema === false) throw failure(path, 'value is forbidden');
	if (schema.$ref) validate(resolveReference(schema.$ref, path), value, path);
	if (schema.type !== undefined && !matchesType(schema.type, value)) throw failure(path, `expected ${typeDescription(schema.type)}`);
	if (Object.hasOwn(schema, 'const') && !deepEqual(schema.const, value)) throw failure(path, `expected ${JSON.stringify(schema.const)}`);
	if (schema.enum && !schema.enum.some(item => deepEqual(item, value))) throw failure(path, 'value is not a registered enum member');
	validateComposition(schema, value, path);
	if (typeof value === 'number') validateNumber(schema, value, path);
	if (typeof value === 'string') validateString(schema, value, path);
	if (Array.isArray(value)) validateArray(schema, value, path);
	if (isRecord(value)) validateObject(schema, value, path);
}

function validateComposition(schema: Exclude<JsonSchema, boolean>, value: unknown, path: string): void {
	if (schema.oneOf) {
		const matchingSchemas = schema.oneOf.filter(candidate => matches(candidate, value, path));
		if (matchingSchemas.length !== 1) throw failure(path, `expected exactly one schema variant, matched ${matchingSchemas.length}`);
	}
	if (schema.anyOf && !schema.anyOf.some(candidate => matches(candidate, value, path))) {
		throw failure(path, 'value does not match any allowed schema');
	}
}

function validateNumber(schema: Exclude<JsonSchema, boolean>, value: number, path: string): void {
	if (!Number.isFinite(value)) throw failure(path, 'expected a finite number');
	const types = typeof schema.type === 'string' ? [schema.type] : schema.type;
	if (types?.includes('integer') && !Number.isSafeInteger(value)) throw failure(path, 'expected a safe integer');
	if (schema.minimum !== undefined && value < schema.minimum) throw failure(path, `expected at least ${schema.minimum}`);
	if (schema.maximum !== undefined && value > schema.maximum) throw failure(path, `expected at most ${schema.maximum}`);
}

function validateString(schema: Exclude<JsonSchema, boolean>, value: string, path: string): void {
	const length = [...value].length;
	if (schema.minLength !== undefined && length < schema.minLength) throw failure(path, `expected at least ${schema.minLength} characters`);
	if (schema.maxLength !== undefined && length > schema.maxLength) throw failure(path, `expected at most ${schema.maxLength} characters`);
}

function validateArray(schema: Exclude<JsonSchema, boolean>, value: readonly unknown[], path: string): void {
	if (schema.minItems !== undefined && value.length < schema.minItems) throw failure(path, `expected at least ${schema.minItems} items`);
	if (schema.maxItems !== undefined && value.length > schema.maxItems) throw failure(path, `expected at most ${schema.maxItems} items`);
	if (schema.items !== undefined) value.forEach((item, index) => validate(schema.items!, item, `${path}[${index}]`));
	if (schema.uniqueItems) {
		for (let left = 0; left < value.length; left += 1) {
			for (let right = left + 1; right < value.length; right += 1) {
				if (deepEqual(value[left], value[right])) throw failure(`${path}[${right}]`, 'expected unique items');
			}
		}
	}
}

function validateObject(schema: Exclude<JsonSchema, boolean>, value: Readonly<Record<string, unknown>>, path: string): void {
	for (const required of schema.required ?? []) {
		if (!Object.hasOwn(value, required)) throw failure(`${path}.${required}`, 'missing required field');
	}
	for (const [name, propertySchema] of Object.entries(schema.properties ?? {})) {
		if (Object.hasOwn(value, name)) validate(propertySchema, value[name], `${path}.${name}`);
	}
	const declared = declaredProperties(schema, value, new Set<string>());
	const unknown = Object.keys(value).filter(key => !declared.has(key));
	if (schema.additionalProperties === false || schema.unevaluatedProperties === false) {
		if (unknown.length > 0) throw failure(`${path}.${unknown[0]}`, 'unknown field');
		return;
	}
	const additional = schema.additionalProperties ?? schema.unevaluatedProperties;
	if (additional && typeof additional === 'object') {
		for (const key of unknown) validate(additional, value[key], `${path}.${key}`);
	}
}

function declaredProperties(schema: JsonSchema, value: unknown, result: Set<string>): Set<string> {
	if (typeof schema === 'boolean') return result;
	for (const name of Object.keys(schema.properties ?? {})) result.add(name);
	if (schema.$ref) declaredProperties(resolveReference(schema.$ref, '$'), value, result);
	for (const candidate of schema.oneOf ?? []) {
		if (matches(candidate, value, '$')) declaredProperties(candidate, value, result);
	}
	for (const candidate of schema.anyOf ?? []) {
		if (matches(candidate, value, '$')) declaredProperties(candidate, value, result);
	}
	return result;
}

function resolveReference(reference: string, path: string): JsonSchema {
	const prefix = '#/$defs/';
	if (!reference.startsWith(prefix)) throw failure(path, `unsupported schema reference: ${reference}`);
	const definitions = typeof protocolSchema === 'boolean' ? undefined : protocolSchema.$defs;
	const schema = definitions?.[reference.slice(prefix.length)];
	if (!schema) throw failure(path, `missing schema reference: ${reference}`);
	return schema;
}

function matches(schema: JsonSchema, value: unknown, path: string): boolean {
	try {
		validate(schema, value, path);
		return true;
	} catch (error) {
		if (error instanceof AppServerProtocolDecodeError) return false;
		throw error;
	}
}

function matchesType(type: string | readonly string[], value: unknown): boolean {
	const types = typeof type === 'string' ? [type] : type;
	return types.some(candidate => {
		switch (candidate) {
			case 'null': return value === null;
			case 'boolean': return typeof value === 'boolean';
			case 'string': return typeof value === 'string';
			case 'number': return typeof value === 'number' && Number.isFinite(value);
			case 'integer': return typeof value === 'number' && Number.isSafeInteger(value);
			case 'array': return Array.isArray(value);
			case 'object': return isRecord(value);
			default: return false;
		}
	});
}

function typeDescription(type: string | readonly string[]): string {
	return typeof type === 'string' ? type : type.join(' or ');
}

function assertJsonRpcId(value: unknown, path: string): asserts value is JsonRpcId {
	if (value === null || typeof value === 'string') return;
	if (typeof value === 'number' && Number.isSafeInteger(value) && value >= 0) return;
	throw failure(path, 'invalid JSON-RPC request ID');
}

function exactKeys(value: Readonly<Record<string, unknown>>, allowed: readonly string[], path: string): void {
	const allowedKeys = new Set(allowed);
	const unknown = Object.keys(value).find(key => !allowedKeys.has(key));
	if (unknown !== undefined) throw failure(`${path}.${unknown}`, 'unknown field');
}

function record(value: unknown, path: string): Readonly<Record<string, unknown>> {
	if (!isRecord(value)) throw failure(path, 'expected object');
	return value;
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function deepEqual(left: unknown, right: unknown): boolean {
	if (Object.is(left, right)) return true;
	if (Array.isArray(left) && Array.isArray(right)) {
		return left.length === right.length && left.every((value, index) => deepEqual(value, right[index]));
	}
	if (!isRecord(left) || !isRecord(right)) return false;
	const leftKeys = Object.keys(left);
	const rightKeys = Object.keys(right);
	return leftKeys.length === rightKeys.length && leftKeys.every(key => Object.hasOwn(right, key) && deepEqual(left[key], right[key]));
}

function failure(path: string, message: string): AppServerProtocolDecodeError {
	return new AppServerProtocolDecodeError(path, message);
}
