load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

cargo_build_script(
    name = "build_script",
    srcs = ["build.rs"],
    crate_root = "build.rs",
    edition = "2024",
)

rust_library(
    name = "build-info",
    crate_name = "ash_build_info",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    deps = all_crate_deps() + [":build_script"],
    visibility = ["//visibility:public"],
)

rust_test(
    name = "build-info-unit-tests",
    crate = ":build-info",
    deps = all_crate_deps(normal = True, normal_dev = True),
)
