[package]
name = "zeta-workbench-host"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_workbench_host"
path = "src/lib.rs"

[dependencies]
zeta-workbench = { workspace = true }
zeta-workbench-layout = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
zeta-protocol = { workspace = true }
