// Generated by `zeta-app-server-protocol export`. Do not edit.
export const APP_SERVER_SCHEMA_HASH = "sha256:2c22f59ea14febea99995d0a3f7e9b1f613daf9179792de47b647567bcfbe3df" as const;
export type JsonRpcVersion = "2.0";
export type JsonRpcId = number | string | null;
export type JsonRpcRequest<P> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P };
export type JsonRpcNotification<P> = { jsonrpc: JsonRpcVersion; method: string; params: P };
export type JsonRpcSuccess<R> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R };
export type JsonRpcFailure<E> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E };
export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;
export type ThreadId = string;
export type SessionId = string;
export type CommandId = string;
export type RequestId = string;
export type StreamInstanceId = string;
export type ItemId = string;
export type ToolCallId = string;
export type ToolName = string;
export type TurnId = string;
export type SchemaHash = string;
export type ClientInfo = { name: string, version: string, };
export type BrowserCapability = { version: number, observe: boolean, input: boolean, };
export type ClientCapabilities = { notifications?: boolean, browser?: BrowserCapability | null, };
export type ServerInfo = { name: string, version: string, };
export type ModelRef = { provider: string, model: string, };
export type ApprovalReviewModelSelection = { "type": "automatic" } | { "type": "explicit", model: ModelRef, };
export type ProviderConfigDto = { provider: string, baseUrl?: string | null, maxOutputTokens?: number | null, };
export type McpCredentialBindingDto = { "type": "unauthenticated" } | { "type": "reference", credentialRef: string, };
export type McpServerEnablementDto = "disabled" | "enabled";
export type McpTransportDto = { "type": "stdio", command: string, args: Array<string>, } | { "type": "streamableHttp", url: string, };
export type McpServerConfigDto = { id: string, displayName: string, transport: McpTransportDto, credential: McpCredentialBindingDto, enablement: McpServerEnablementDto, };
export type SkillSourceEnablementDto = "disabled" | "enabled";
export type SkillSourceConfigDto = { id: string, rootReference: string, enablement: SkillSourceEnablementDto, };
export type Theme = "light" | "dark" | "system";
export type ConfigReadResult = { revision: number, generation: number, preferredModel: ModelRef | null, approvalReviewModel: ApprovalReviewModelSelection, theme: Theme | null, providers: { [key in string]: ProviderConfigDto }, mcpServers: { [key in string]: McpServerConfigDto }, skillSources: { [key in string]: SkillSourceConfigDto }, };
export type ConfigCommandDispositionDto = "updated" | "replayed";
export type ConfigCommandResult = { revision: number, generation: number, disposition: ConfigCommandDispositionDto, };
export type ConfigUpdateParams = { commandId: CommandId, expectedRevision: number, preferredModel?: ModelRef | null, approvalReviewModel?: ApprovalReviewModelSelection | null, theme?: Theme | null, };
export type ProviderConfigureParams = { commandId: CommandId, expectedRevision: number, config: ProviderConfigDto, };
export type ProviderRemoveParams = { commandId: CommandId, expectedRevision: number, provider: string, };
export type McpServerUpsertParams = { commandId: CommandId, expectedRevision: number, server: McpServerConfigDto, };
export type McpServerRemoveParams = { commandId: CommandId, expectedRevision: number, serverId: string, };
export type McpServerSetEnablementParams = { commandId: CommandId, expectedRevision: number, serverId: string, enablement: McpServerEnablementDto, };
export type SkillSourceAddParams = { commandId: CommandId, expectedRevision: number, source: SkillSourceConfigDto, };
export type SkillSourceRemoveParams = { commandId: CommandId, expectedRevision: number, sourceId: string, };
export type SkillSourceSetEnablementParams = { commandId: CommandId, expectedRevision: number, sourceId: string, enablement: SkillSourceEnablementDto, };
export type ServerCapabilities = { sessions: boolean, threads: boolean, turns: boolean, resources: boolean, typst: boolean, updateReplay: boolean, };
export type InitializeParams = { clientInfo: ClientInfo, capabilities: ClientCapabilities, };
export type InitializeResult = { serverInfo: ServerInfo, schemaHash: SchemaHash, capabilities: ServerCapabilities, };
export type SessionStatus = "active" | "completed" | "archived";
export type ThreadOrigin = { "type": "root" } | { "type": "fork", parentThreadId: ThreadId, parentSequence: number, };
export type SessionThreadStatus = "creating" | "active" | "archived";
export type SessionThread = { threadId: ThreadId, origin: ThreadOrigin, status: SessionThreadStatus, };
export type Session = { sessionId: SessionId, title: string, status: SessionStatus, sequence: number, threads: Array<SessionThread>, };
export type SessionEvent = { "type": "sessionCreated", sessionId: SessionId, title: string, } | { "type": "threadCreationPlanned", sessionId: SessionId, thread: SessionThread, title: string, } | { "type": "threadAttached", sessionId: SessionId, threadId: ThreadId, } | { "type": "threadArchived", sessionId: SessionId, threadId: ThreadId, } | { "type": "sessionCompleted", sessionId: SessionId, } | { "type": "sessionArchived", sessionId: SessionId, };
export type SessionUpdate = { "type": "committed", event: SessionEvent, };
export type SessionUpdateEnvelope = { sessionId: SessionId, durableSequence: number, update: SessionUpdate, };
export type SessionCreateParams = { commandId: CommandId, title: string, };
export type SessionReadParams = { sessionId: SessionId, };
export type SessionSubscribeParams = { sessionId: SessionId, afterSequence: number, };
export type SessionUnsubscribeParams = { sessionId: SessionId, };
export type SessionCommandParams = { commandId: CommandId, sessionId: SessionId, expectedSequence: number, };
export type SessionThreadCreateParams = { commandId: CommandId, sessionId: SessionId, expectedSequence: number, title: string, };
export type SessionThreadForkParams = { commandId: CommandId, sessionId: SessionId, expectedSequence: number, parentThreadId: ThreadId, title: string, };
export type SessionThreadArchiveParams = { commandId: CommandId, sessionId: SessionId, expectedSequence: number, threadId: ThreadId, };
export type SessionResult = { session: Session, };
export type SessionListResult = { sessions: Array<Session>, };
export type SessionSubscribeResult = { session: Session, updates: Array<SessionUpdateEnvelope>, };
export type SessionThreadResult = { session: Session, threadId: ThreadId, };
export type StableTurnErrorCode = "modelInvocationFailed" | "completionPersistenceFailed";
export type StableTurnError = { code: StableTurnErrorCode, message: string, retryable: boolean, };
export type ThreadStatus = "active" | "archived";
export type TurnStatus = "created" | "running" | "waitingForApproval" | "waitingForUserInput" | "waitingForCapability" | "cancelling" | "completed" | "failed" | "interrupted";
export type ActionApprovalCapabilityKind = "fileRead" | "fileWrite" | "processSpawn" | "network" | "credentialUse" | "externalMutation" | "systemConfiguration" | "userInterface";
export type ActionApprovalCapability = { kind: ActionApprovalCapabilityKind, scope: string, };
export type ActionApprovalRequest = { actionDigest: string, policyRevision: string, capabilities: Array<ActionApprovalCapability>, reason: string, };
export type ActionApprovalDecision = "approveOnce" | "decline";
export type ActionApprovalResponse = { decision: ActionApprovalDecision, };
export type AgentInteractionKind = "approval" | "userInput" | "dynamicTool";
export type AgentRequest = { "type": "approval", request: ActionApprovalRequest, } | { "type": "userInput", request: RequestUserInput, } | { "type": "dynamicTool", call: DynamicToolCall, };
export type AgentResponse = { "type": "approval", response: ActionApprovalResponse, } | { "type": "userInput", response: RequestUserInputResponse, } | { "type": "dynamicTool", response: DynamicToolResponse, };
export type TurnInteraction = { requestId: RequestId, itemId?: ItemId | null, request: AgentRequest, deadline?: InteractionDeadline | null, };
export type PendingInteraction = { requestId: RequestId, itemId?: ItemId | null, kind: AgentInteractionKind, deadline?: InteractionDeadline | null, };
export type InteractionDeadline = { expiresAtUnixMs: number, };
export type InteractionCancelReason = "turnInterrupted" | "deadlineElapsed" | "ownerDisconnected" | "serverShutdown";
export type RequestUserInput = { questions: Array<UserInputQuestion>, };
export type RequestUserInputResponse = { answers: { [key in string]: UserInputAnswer }, };
export type UserInputQuestion = { id: string, header: string, question: string, options?: Array<UserInputOption>, allowFreeForm: boolean, };
export type UserInputOption = { label: string, description: string, };
export type UserInputAnswer = { value: string, };
export type DynamicToolCall = { callId: ToolCallId, name: ToolName, arguments: unknown, };
export type DynamicToolResponse = { callId: ToolCallId, content: Array<DynamicToolOutput>, success: boolean, };
export type DynamicToolOutput = { "type": "text", text: string, } | { "type": "image", dataUrl: string, };
export type ThreadItem = { "type": "userMessage", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "agentMessage", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "reasoning", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "plan", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "toolCall", itemId: ItemId, turnId: TurnId, toolCallId: ToolCallId, name: ToolName, argumentsJson: string, } | { "type": "toolResult", itemId: ItemId, turnId: TurnId, toolCallId: ToolCallId, text: string, isError: boolean, };
export type Turn = { turnId: TurnId, status: TurnStatus, items: Array<ThreadItem>, pendingInteraction?: PendingInteraction | null, error?: StableTurnError | null, };
export type Thread = { sessionId: SessionId, threadId: ThreadId, title: string, status: ThreadStatus, sequence: number, turns: Array<Turn>, };
export type ToolExecutionAuthority = { "type": "sandboxed" } | { "type": "unsandboxedGrant", grantId: string, } | { "type": "autoReviewed", assessmentId: string, } | { "type": "approvedOnce", requestId: RequestId, };
export type ProcessExitStatus = { "type": "code", "code": number } | { "type": "terminated" };
export type ProcessExecutionOutput = { exitStatus: ProcessExitStatus, stdout: string, stderr: string, aggregatedOutput: string, };
export type ToolReplaySafety = "safeToRetry" | "mayHaveSideEffects";
export type SandboxDenialOutput = { reason: string, output: ProcessExecutionOutput, replaySafety: ToolReplaySafety, };
export type ThreadEvent = { "type": "threadCreated", sessionId: SessionId, threadId: ThreadId, title: string, } | { "type": "turnAccepted", threadId: ThreadId, turnId: TurnId, } | { "type": "turnStarted", threadId: ThreadId, turnId: TurnId, } | { "type": "itemCompleted", threadId: ThreadId, turnId: TurnId, item: ThreadItem, } | { "type": "interactionRequested", threadId: ThreadId, turnId: TurnId, interaction: TurnInteraction, } | { "type": "interactionResolved", threadId: ThreadId, turnId: TurnId, requestId: RequestId, response: AgentResponse, } | { "type": "toolExecutionStarted", threadId: ThreadId, turnId: TurnId, toolCallId: ToolCallId, actionDigest: string, policyRevision: string, authority: ToolExecutionAuthority, } | { "type": "toolExecutionEscalated", threadId: ThreadId, turnId: TurnId, toolCallId: ToolCallId, actionDigest: string, policyRevision: string, denial: SandboxDenialOutput, authority: ToolExecutionAuthority, } | { "type": "interactionCancelled", threadId: ThreadId, turnId: TurnId, requestId: RequestId, reason: InteractionCancelReason, } | { "type": "turnCompleted", threadId: ThreadId, turnId: TurnId, } | { "type": "turnFailed", threadId: ThreadId, turnId: TurnId, error: StableTurnError, } | { "type": "turnCancelling", threadId: ThreadId, turnId: TurnId, } | { "type": "turnInterrupted", threadId: ThreadId, turnId: TurnId, };
export type PlanStepStatus = "pending" | "inProgress" | "completed";
export type PlanStep = { step: string, status: PlanStepStatus, };
export type PlanUpdate = { explanation?: string | null, steps: Array<PlanStep>, };
export type StreamCursor = { streamInstanceId: StreamInstanceId, sequence: number, };
export type ItemDelta = { "type": "agentMessage", text: string, } | { "type": "reasoning", text: string, } | { "type": "plan", text: string, };
export type ThreadUpdate = { "type": "committed", event: ThreadEvent, } | { "type": "itemStarted", turnId: TurnId, item: ThreadItem, } | { "type": "itemDelta", turnId: TurnId, itemId: ItemId, delta: ItemDelta, } | { "type": "planUpdated", turnId: TurnId, plan: PlanUpdate, };
export type ThreadUpdateEnvelope = { sessionId: SessionId, threadId: ThreadId, durableSequence: number, streamCursor?: StreamCursor | null, update: ThreadUpdate, };
export type ThreadReadParams = { threadId: ThreadId, };
export type ThreadSubscribeParams = { threadId: ThreadId, afterSequence: number, };
export type ThreadUnsubscribeParams = { threadId: ThreadId, };
export type ThreadReadResult = { thread: Thread, };
export type ThreadSubscribeResult = { thread: Thread, updates: Array<ThreadUpdateEnvelope>, };
export type InputItemKind = "text";
export type InputItem = { type: InputItemKind, text: string, };
export type TurnStartParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, expectedSequence: number, input: Array<InputItem>, };
export type TurnStartResult = { turnId: TurnId, sequence: number, };
export type TurnInterruptParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, turnId: TurnId, expectedSequence: number, };
export type TurnInterruptResult = { sequence: number, };
export type TurnInteractionResolveParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, turnId: TurnId, requestId: RequestId, expectedSequence: number, response: AgentResponse, };
export type TurnInteractionResolveResult = { sequence: number, };
export type TypstCompileParams = { source: string, };
export type TypstCompileResult = { "status": "success", resource: ResourceMetadataResult, warnings: Array<TypstDiagnosticDto>, } | { "status": "failed", diagnostics: Array<TypstDiagnosticDto>, };
export type TypstDiagnosticDto = { severity: TypstDiagnosticSeverityDto, message: string, hints: Array<string>, range: TypstSourceRangeDto | null, };
export type TypstDiagnosticSeverityDto = "error" | "warning";
export type TypstSourceRangeDto = { start: number, end: number, };
export type ResourceMetadataParams = { resourceId: string, };
export type ResourceMetadataResult = { resourceId: string, mimeType: string, size: number, sha256: string, };
export type ResourceReadParams = { resourceId: string, offset: number, maxBytes: number, };
export type ResourceReadResult = { resourceId: string, offset: number, dataBase64: string, decodedLength: number, eof: boolean, };
export type ResourceReleaseParams = { resourceId: string, };
export type AppServerErrorName = "ParseError" | "InvalidRequest" | "MethodNotFound" | "InvalidParams" | "InternalError" | "ServerOverloaded" | "NotInitialized" | "AlreadyInitialized" | "CommandConflict" | "CoreOperationFailed" | "ResourceNotFound" | "ResourceNotOwner" | "ResourceTooLarge" | "InvalidResourceChunkSize" | "InvalidResourceOffset" | "ConfigUnavailable" | "ConfigRevisionConflict";
export type AppServerError = { code: number, message: AppServerErrorName, data: null, };
export type ServerNotification =
  { method: "session/update"; params: SessionUpdateEnvelope }
  | { method: "thread/update"; params: ThreadUpdateEnvelope }
;
export type AppServerWireNotification = JsonRpcNotification<ServerNotification>;
export interface AppServerMethodMap {
  "initialize": { params: InitializeParams; result: InitializeResult };
  "session/create": { params: SessionCreateParams; result: SessionResult };
  "session/read": { params: SessionReadParams; result: SessionResult };
  "session/list": { params: Record<string, never>; result: SessionListResult };
  "session/subscribe": { params: SessionSubscribeParams; result: SessionSubscribeResult };
  "session/unsubscribe": { params: SessionUnsubscribeParams; result: null };
  "session/thread/create": { params: SessionThreadCreateParams; result: SessionThreadResult };
  "session/thread/fork": { params: SessionThreadForkParams; result: SessionThreadResult };
  "session/thread/archive": { params: SessionThreadArchiveParams; result: SessionResult };
  "session/complete": { params: SessionCommandParams; result: SessionResult };
  "session/archive": { params: SessionCommandParams; result: SessionResult };
  "thread/read": { params: ThreadReadParams; result: ThreadReadResult };
  "thread/subscribe": { params: ThreadSubscribeParams; result: ThreadSubscribeResult };
  "thread/unsubscribe": { params: ThreadUnsubscribeParams; result: null };
  "config/read": { params: Record<string, never>; result: ConfigReadResult };
  "config/update": { params: ConfigUpdateParams; result: ConfigCommandResult };
  "provider/configure": { params: ProviderConfigureParams; result: ConfigCommandResult };
  "provider/remove": { params: ProviderRemoveParams; result: ConfigCommandResult };
  "mcp/server/upsert": { params: McpServerUpsertParams; result: ConfigCommandResult };
  "mcp/server/remove": { params: McpServerRemoveParams; result: ConfigCommandResult };
  "mcp/server/enablement/set": { params: McpServerSetEnablementParams; result: ConfigCommandResult };
  "skill/source/add": { params: SkillSourceAddParams; result: ConfigCommandResult };
  "skill/source/remove": { params: SkillSourceRemoveParams; result: ConfigCommandResult };
  "skill/source/enablement/set": { params: SkillSourceSetEnablementParams; result: ConfigCommandResult };
  "turn/start": { params: TurnStartParams; result: TurnStartResult };
  "turn/interrupt": { params: TurnInterruptParams; result: TurnInterruptResult };
  "turn/interaction/resolve": { params: TurnInteractionResolveParams; result: TurnInteractionResolveResult };
  "document/typst/compile": { params: TypstCompileParams; result: TypstCompileResult };
  "resource/metadata": { params: ResourceMetadataParams; result: ResourceMetadataResult };
  "resource/read": { params: ResourceReadParams; result: ResourceReadResult };
  "resource/release": { params: ResourceReleaseParams; result: null };
}
export type AppServerMethod = keyof AppServerMethodMap;
export type MethodParams<M extends AppServerMethod> = AppServerMethodMap[M]["params"];
export type MethodResult<M extends AppServerMethod> = AppServerMethodMap[M]["result"];
export type AppServerRequest<M extends AppServerMethod> = JsonRpcRequest<MethodParams<M>>;
export type AppServerResponse<M extends AppServerMethod> = JsonRpcResponse<MethodResult<M>, AppServerError>;
export type AppServerMethodDefinition<M extends AppServerMethod> = {
readonly method: M;
readonly __params?: MethodParams<M>;
readonly __result?: MethodResult<M>;
};
export const APP_SERVER_METHODS: { [M in AppServerMethod]: AppServerMethodDefinition<M> } = {
  "initialize": { method: "initialize" },
  "session/create": { method: "session/create" },
  "session/read": { method: "session/read" },
  "session/list": { method: "session/list" },
  "session/subscribe": { method: "session/subscribe" },
  "session/unsubscribe": { method: "session/unsubscribe" },
  "session/thread/create": { method: "session/thread/create" },
  "session/thread/fork": { method: "session/thread/fork" },
  "session/thread/archive": { method: "session/thread/archive" },
  "session/complete": { method: "session/complete" },
  "session/archive": { method: "session/archive" },
  "thread/read": { method: "thread/read" },
  "thread/subscribe": { method: "thread/subscribe" },
  "thread/unsubscribe": { method: "thread/unsubscribe" },
  "config/read": { method: "config/read" },
  "config/update": { method: "config/update" },
  "provider/configure": { method: "provider/configure" },
  "provider/remove": { method: "provider/remove" },
  "mcp/server/upsert": { method: "mcp/server/upsert" },
  "mcp/server/remove": { method: "mcp/server/remove" },
  "mcp/server/enablement/set": { method: "mcp/server/enablement/set" },
  "skill/source/add": { method: "skill/source/add" },
  "skill/source/remove": { method: "skill/source/remove" },
  "skill/source/enablement/set": { method: "skill/source/enablement/set" },
  "turn/start": { method: "turn/start" },
  "turn/interrupt": { method: "turn/interrupt" },
  "turn/interaction/resolve": { method: "turn/interaction/resolve" },
  "document/typst/compile": { method: "document/typst/compile" },
  "resource/metadata": { method: "resource/metadata" },
  "resource/read": { method: "resource/read" },
  "resource/release": { method: "resource/release" },
};
export type AppServerNotificationMethod = ServerNotification["method"];
export type NotificationParams<M extends AppServerNotificationMethod> =
Extract<ServerNotification, { method: M }>["params"];
export type AppServerNotificationDefinition<M extends AppServerNotificationMethod> = {
readonly method: M;
readonly __params?: NotificationParams<M>;
};
export const APP_SERVER_NOTIFICATIONS: {
[M in AppServerNotificationMethod]: AppServerNotificationDefinition<M>
} = {
  "session/update": { method: "session/update" },
  "thread/update": { method: "thread/update" },
};
