// Generated by `zeta-app-server-protocol export`. Do not edit.
export const APP_SERVER_SCHEMA_HASH = "sha256:f79516170feff654e7a472556000ee0edad072c0d1b386e0f744483e6009ed34" as const;
export type JsonRpcVersion = "2.0";
export type JsonRpcId = number | string | null;
export type JsonRpcRequest<P> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P };
export type JsonRpcNotification<P> = { jsonrpc: JsonRpcVersion; method: string; params: P };
export type JsonRpcSuccess<R> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R };
export type JsonRpcFailure<E> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E };
export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;
export type ThreadId = string;
export type SessionId = string;
export type CommandId = string;
export type RequestId = string;
export type StreamInstanceId = string;
export type ItemId = string;
export type ToolCallId = string;
export type ToolName = string;
export type TurnId = string;
export type SchemaHash = string;
export type ClientInfo = { name: string, version: string, };
export type BrowserCapability = { version: number, observe: boolean, input: boolean, };
export type ClientCapabilities = { notifications?: boolean, browser?: BrowserCapability | null, };
export type ServerInfo = { name: string, version: string, };
export type DocumentCollaborationOpenParams = { roomId?: string | null, clientId: string, schemaId: string,
/**
 * Serialized, schema-validated document supplied only when creating a room.
 */
document: string, };
export type DocumentCollaborationSnapshot = { roomId: string, version: number, document: string, };
export type DocumentCollaborationOpenResult = { clientId: string, schemaId: string, snapshot: DocumentCollaborationSnapshot, };
export type DocumentCollaborationPresence = { clientId: string,
/**
 * Serialized Gama selection, validated as a bounded selection envelope by the authority.
 */
selection: string, };
export type DocumentCollaborationPresenceParams = { roomId: string, clientId: string,
/**
 * Omitting the selection clears this client's ephemeral presence record.
 */
selection?: string | null, };
export type DocumentCollaborationPresenceReadParams = { roomId: string, };
export type DocumentCollaborationPresenceSnapshot = { roomId: string, generation: number, presences: Array<DocumentCollaborationPresence>, };
export type DocumentCollaborationUpdate = { roomId: string, clientId: string, sequence: number, baseVersion: number, version: number,
/**
 * Serialized Gama transaction. The renderer validates it against its schema before use.
 */
transaction: string, };
export type DocumentCollaborationSubmitParams = { roomId: string, clientId: string, sequence: number, baseVersion: number, transaction: string,
/**
 * Serialized, schema-validated document after applying `transaction` optimistically.
 */
document: string, };
export type DocumentCollaborationSubmitResult = { "status": "accepted", update: DocumentCollaborationUpdate, } | { "status": "conflict", updates: Array<DocumentCollaborationUpdate>, } | { "status": "resync", snapshot: DocumentCollaborationSnapshot, };
export type ModelRef = { provider: string, model: string, };
export type ApprovalReviewModelSelection = { "type": "automatic" } | { "type": "explicit", model: ModelRef, };
export type ProviderConfigDto = { provider: string, baseUrl?: string | null, maxOutputTokens?: number | null, };
export type McpCredentialBindingDto = { "type": "unauthenticated" } | { "type": "reference", credentialRef: string, };
export type McpServerEnablementDto = "disabled" | "enabled";
export type McpTransportDto = { "type": "stdio", command: string, args: Array<string>, } | { "type": "streamableHttp", url: string, };
export type McpServerConfigDto = { id: string, displayName: string, transport: McpTransportDto, credential: McpCredentialBindingDto, enablement: McpServerEnablementDto, };
export type SkillSourceEnablementDto = "disabled" | "enabled";
export type SkillSourceConfigDto = { id: string, rootReference: string, enablement: SkillSourceEnablementDto, };
export type PluginRequestEnablementDto = "disabled" | "enabled";
export type PluginRequestDto = { pluginId: string, version: string, enablement: PluginRequestEnablementDto, };
export type HookEventDto = "beforeTool" | "afterTool" | "turnCompleted";
export type HookEnablementDto = "disabled" | "enabled";
export type HookMatcherDto = { toolNames: Array<string>, };
export type HookActionDto = { "type": "process", program: string, args: Array<string>, };
export type HookConfigDto = { id: string, event: HookEventDto, matcher: HookMatcherDto, action: HookActionDto, enablement: HookEnablementDto, };
export type LanguageServerModeDto = "disabled" | "automatic" | "enabled";
export type LanguageServerConfigDto = { mode: LanguageServerModeDto, executable?: string | null, };
export type ConfigReadResult = { revision: number, generation: number, preferredModel: ModelRef | null, approvalReviewModel: ApprovalReviewModelSelection, providers: { [key in string]: ProviderConfigDto }, mcpServers: { [key in string]: McpServerConfigDto }, skillSources: { [key in string]: SkillSourceConfigDto }, pluginRequests: { [key in string]: PluginRequestDto }, hooks: { [key in string]: HookConfigDto }, languageServers: { [key in string]: LanguageServerConfigDto }, };
export type ConfigChanged = { revision: number, generation: number, };
export type ConfigCommandDispositionDto = "updated" | "replayed";
export type ConfigCommandResult = { revision: number, generation: number, disposition: ConfigCommandDispositionDto, };
export type ConfigUpdateParams = { commandId: CommandId, expectedRevision: number, preferredModel?: ModelRef | null, approvalReviewModel?: ApprovalReviewModelSelection | null, };
export type LanguageServerConfigureParams = { commandId: CommandId, expectedRevision: number, serverId: string, config: LanguageServerConfigDto, };
export type LanguageServerRemoveParams = { commandId: CommandId, expectedRevision: number, serverId: string, };
export type ProviderConfigureParams = { commandId: CommandId, expectedRevision: number, config: ProviderConfigDto, };
export type ProviderRemoveParams = { commandId: CommandId, expectedRevision: number, provider: string, };
export type McpServerUpsertParams = { commandId: CommandId, expectedRevision: number, server: McpServerConfigDto, };
export type McpServerRemoveParams = { commandId: CommandId, expectedRevision: number, serverId: string, };
export type McpServerSetEnablementParams = { commandId: CommandId, expectedRevision: number, serverId: string, enablement: McpServerEnablementDto, };
export type SkillSourceAddParams = { commandId: CommandId, expectedRevision: number, source: SkillSourceConfigDto, };
export type SkillSourceRemoveParams = { commandId: CommandId, expectedRevision: number, sourceId: string, };
export type SkillSourceSetEnablementParams = { commandId: CommandId, expectedRevision: number, sourceId: string, enablement: SkillSourceEnablementDto, };
export type PluginRequestUpsertParams = { commandId: CommandId, expectedRevision: number, request: PluginRequestDto, };
export type PluginRequestRemoveParams = { commandId: CommandId, expectedRevision: number, pluginId: string, };
export type PluginRequestSetEnablementParams = { commandId: CommandId, expectedRevision: number, pluginId: string, enablement: PluginRequestEnablementDto, };
export type HookUpsertParams = { commandId: CommandId, expectedRevision: number, hook: HookConfigDto, };
export type HookRemoveParams = { commandId: CommandId, expectedRevision: number, hookId: string, };
export type HookSetEnablementParams = { commandId: CommandId, expectedRevision: number, hookId: string, enablement: HookEnablementDto, };
export type SkillName = string;
export type SkillSourceId = string;
export type SkillId = { source: SkillSourceId, name: SkillName, };
export type SkillCatalogReloadDto = "cached" | "refresh";
export type SkillEnablementDto = "disabled" | "enabled";
export type SkillSourceKindDto = "builtIn" | "user";
export type SkillCompatibilityDto = { "type": "compatible" } | { "type": "unknown", note: string, };
export type SkillDto = { id: SkillId, description: string, sourceKind: SkillSourceKindDto, contentDigest: string, enablement: SkillEnablementDto, compatibility: SkillCompatibilityDto, };
export type SkillDiagnosticCodeDto = "sourceUnavailable" | "sourceLimitExceeded" | "skillNotFound" | "invalidFrontmatter" | "invalidSkillName" | "descriptionInvalid" | "pathEscapesRoot" | "unsupportedFileType" | "contentTooLarge";
export type SkillDiagnosticDto = { source: string, subject: string | null, code: SkillDiagnosticCodeDto, message: string, };
export type SkillListParams = { reload: SkillCatalogReloadDto, };
export type SkillListResult = { generation: number, skills: Array<SkillDto>, diagnostics: Array<SkillDiagnosticDto>, };
export type SkillSetEnablementParams = { commandId: CommandId, expectedRevision: number, skillId: SkillId, enablement: SkillEnablementDto, };
export type SkillsChanged = { generation: number, };
export type ExtensionCatalogReloadDto = "cached" | "refresh";
export type ExtensionSourceKindDto = "builtIn" | "user";
export type ExtensionDiagnosticCodeDto = "sourceUnavailable" | "invalidManifest" | "duplicateExtension" | "pathEscapesRoot" | "resourceNotFound" | "resourceTooLarge";
export type ExtensionDto = { id: string, name: string, publisher: string, version: string, displayName: string, sourceKind: ExtensionSourceKindDto, manifestJson: string, manifestSha256: string, };
export type ExtensionDiagnosticDto = { source: string, subject: string | null, code: ExtensionDiagnosticCodeDto, message: string, };
export type ExtensionListParams = { reload: ExtensionCatalogReloadDto, };
export type ExtensionListResult = { generation: number, extensions: Array<ExtensionDto>, diagnostics: Array<ExtensionDiagnosticDto>, };
export type ExtensionResourceOpenParams = { extensionId: string, path: string, };
export type ExtensionResourceOpenResult = { resource: ResourceMetadataResult, };
export type SlashCommandArgumentModeDto = "none" | "optional";
export type SlashCommandDefinition = { name: string, description: string, argumentMode: SlashCommandArgumentModeDto, };
export type ServerCapabilities = { documentCollaboration: boolean, sessions: boolean, threads: boolean, turns: boolean, resources: boolean, fileSystem: boolean, git: boolean, workspaceSearch: boolean, terminal: boolean, typst: boolean, updateReplay: boolean, extensions: boolean, };
export type InitializeParams = { clientInfo: ClientInfo, capabilities: ClientCapabilities, };
export type InitializeResult = { serverInfo: ServerInfo, schemaHash: SchemaHash, capabilities: ServerCapabilities, slashCommands: Array<SlashCommandDefinition>, };
export type WorkspaceSwitchParams = { root: string, };
export type WorkspaceSwitchResult = { root: string, };
export type SessionStatus = "active" | "completed" | "archived";
export type ThreadOrigin = { "type": "root" } | { "type": "fork", parentThreadId: ThreadId, parentSequence: number, } | { "type": "rewind", parentThreadId: ThreadId, parentSequence: number, beforeTurnId: TurnId, };
export type SessionThreadStatus = "creating" | "active" | "archived";
export type SessionThread = { threadId: ThreadId, origin: ThreadOrigin, status: SessionThreadStatus, };
export type Session = { sessionId: SessionId, title: string, status: SessionStatus, model?: ModelRef | null, sequence: number, threads: Array<SessionThread>, };
export type SessionEvent = { "type": "sessionCreated", sessionId: SessionId, title: string, model?: ModelRef | null, } | { "type": "sessionModelChanged", sessionId: SessionId, model: ModelRef, } | { "type": "threadCreationPlanned", sessionId: SessionId, thread: SessionThread, title: string, } | { "type": "threadAttached", sessionId: SessionId, threadId: ThreadId, } | { "type": "threadArchived", sessionId: SessionId, threadId: ThreadId, } | { "type": "sessionCompleted", sessionId: SessionId, } | { "type": "sessionArchived", sessionId: SessionId, };
export type SessionUpdate = { "type": "committed", event: SessionEvent, };
export type SessionUpdateEnvelope = { sessionId: SessionId, durableSequence: number, update: SessionUpdate, };
export type SessionCreateParams = { commandId: CommandId, title: string, };
export type SessionReadParams = { sessionId: SessionId, };
export type SessionSubscribeParams = { sessionId: SessionId, afterSequence: number, };
export type SessionUnsubscribeParams = { sessionId: SessionId, };
export type SessionRequest = { "type": "complete" } | { "type": "archive" } | { "type": "stop" } | { "type": "setModel", model: ModelRef, } | { "type": "createThread", title: string, } | { "type": "forkThread", parentThreadId: ThreadId, title: string, } | { "type": "rewindThread", parentThreadId: ThreadId, beforeTurnId: TurnId, title: string, } | { "type": "archiveThread", threadId: ThreadId, } | { "type": "startTurn", threadId: ThreadId, input: Array<InputItem>, } | { "type": "startShellTurn", threadId: ThreadId, command: string, workingDirectory: string, } | { "type": "interruptTurn", threadId: ThreadId, turnId: TurnId, } | { "type": "resolveInteraction", threadId: ThreadId, turnId: TurnId, requestId: RequestId, response: AgentResponse, };
export type SessionRequestParams = { commandId: CommandId, sessionId: SessionId, expectedSequence: number, request: SessionRequest, };
export type SessionRequestResult = { "type": "session", "value": SessionResult } | { "type": "thread", "value": SessionThreadResult } | { "type": "turn", "value": TurnStartResult } | { "type": "turnInterrupt", "value": TurnInterruptResult } | { "type": "interaction", "value": TurnInteractionResolveResult };
export type SessionThreadReadParams = { sessionId: SessionId, threadId: ThreadId, };
export type SessionThreadReadResult = { thread: Thread, };
export type SessionThreadSubscribeParams = { sessionId: SessionId, threadId: ThreadId, afterSequence: number, };
export type SessionThreadSubscribeResult = { thread: Thread, updates: Array<ThreadUpdateEnvelope>, };
export type SessionThreadUnsubscribeParams = { sessionId: SessionId, threadId: ThreadId, };
export type SessionResult = { session: Session, };
export type SessionListResult = { sessions: Array<Session>, };
export type SessionSubscribeResult = { session: Session, updates: Array<SessionUpdateEnvelope>, threadProjections: Array<SessionThreadProjection>, };
export type SessionThreadProjection = { thread: Thread, updates: Array<ThreadUpdateEnvelope>, };
export type SessionThreadResult = { session: Session, threadId: ThreadId, };
export type ModelCatalogEntry = { model: ModelRef, displayName: string, };
export type ModelListResult = { models: Array<ModelCatalogEntry>, };
export type StableTurnErrorCode = "modelInvocationFailed" | "completionPersistenceFailed";
export type StableTurnError = { code: StableTurnErrorCode, message: string, retryable: boolean, };
export type ThreadStatus = "active" | "archived";
export type TurnStatus = "created" | "running" | "waitingForApproval" | "waitingForUserInput" | "waitingForCapability" | "cancelling" | "completed" | "failed" | "interrupted";
export type ActionApprovalCapabilityKind = "fileRead" | "fileWrite" | "processSpawn" | "network" | "credentialUse" | "externalMutation" | "systemConfiguration" | "userInterface";
export type ActionApprovalCapability = { kind: ActionApprovalCapabilityKind, scope: string, };
export type ActionApprovalRequest = { actionDigest: string, policyRevision: string, capabilities: Array<ActionApprovalCapability>, reason: string, sandboxDenial?: SandboxDenialOutput | null, };
export type ActionApprovalDecision = "approveOnce" | "decline";
export type ActionApprovalResponse = { decision: ActionApprovalDecision, };
export type AgentInteractionKind = "approval" | "userInput" | "dynamicTool";
export type AgentRequest = { "type": "approval", request: ActionApprovalRequest, } | { "type": "userInput", request: RequestUserInput, } | { "type": "dynamicTool", call: DynamicToolCall, };
export type AgentResponse = { "type": "approval", response: ActionApprovalResponse, } | { "type": "userInput", response: RequestUserInputResponse, } | { "type": "dynamicTool", response: DynamicToolResponse, };
export type TurnInteraction = { requestId: RequestId, itemId?: ItemId | null, request: AgentRequest, deadline?: InteractionDeadline | null, };
export type PendingInteraction = { requestId: RequestId, itemId?: ItemId | null, kind: AgentInteractionKind, deadline?: InteractionDeadline | null, };
export type InteractionDeadline = { expiresAtUnixMs: number, };
export type InteractionCancelReason = "turnInterrupted" | "deadlineElapsed" | "ownerDisconnected" | "serverShutdown";
export type RequestUserInput = { questions: Array<UserInputQuestion>, };
export type RequestUserInputResponse = { answers: { [key in string]: UserInputAnswer }, };
export type UserInputQuestion = { id: string, header: string, question: string, options?: Array<UserInputOption>, allowFreeForm: boolean, };
export type UserInputOption = { label: string, description: string, };
export type UserInputAnswer = { value: string, };
export type DynamicToolCall = { callId: ToolCallId, name: ToolName, arguments: unknown, };
export type DynamicToolResponse = { callId: ToolCallId, content: Array<DynamicToolOutput>, success: boolean, };
export type DynamicToolOutput = { "type": "text", text: string, } | { "type": "image", dataUrl: string, };
export type ThreadItem = { "type": "userMessage", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "userImage", itemId: ItemId, turnId: TurnId, url: string, } | { "type": "agentMessage", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "reasoning", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "plan", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "toolCall", itemId: ItemId, turnId: TurnId, toolCallId: ToolCallId, name: ToolName, argumentsJson: string, } | { "type": "toolResult", itemId: ItemId, turnId: TurnId, toolCallId: ToolCallId, text: string, isError: boolean, };
export type Turn = { turnId: TurnId, status: TurnStatus, model?: ModelRef | null, items: Array<ThreadItem>, pendingInteraction?: PendingInteraction | null, error?: StableTurnError | null, };
export type Thread = { sessionId: SessionId, threadId: ThreadId, title: string, status: ThreadStatus, sequence: number, turns: Array<Turn>, };
export type ToolExecutionAuthority = { "type": "sandboxed" } | { "type": "unsandboxedGrant", grantId: string, } | { "type": "autoReviewed", assessmentId: string, } | { "type": "approvedOnce", requestId: RequestId, };
export type ToolOutputStream = "stdout" | "stderr";
export type ProcessExitStatus = { "type": "code", "code": number } | { "type": "terminated" };
export type ProcessExecutionOutput = { exitStatus: ProcessExitStatus, stdout: string, stderr: string, aggregatedOutput: string, };
export type ToolReplaySafety = "safeToRetry" | "mayHaveSideEffects";
export type SandboxDenialOutput = { reason: string, output: ProcessExecutionOutput, replaySafety: ToolReplaySafety, };
export type ThreadEvent = { "type": "threadCreated", sessionId: SessionId, threadId: ThreadId, title: string, } | { "type": "historyImported", threadId: ThreadId, sourceThreadId: ThreadId, beforeTurnId: TurnId, turns: Array<Turn>, } | { "type": "turnAccepted", threadId: ThreadId, turnId: TurnId, model?: ModelRef | null, } | { "type": "turnStarted", threadId: ThreadId, turnId: TurnId, } | { "type": "itemCompleted", threadId: ThreadId, turnId: TurnId, item: ThreadItem, } | { "type": "interactionRequested", threadId: ThreadId, turnId: TurnId, interaction: TurnInteraction, } | { "type": "interactionResolved", threadId: ThreadId, turnId: TurnId, requestId: RequestId, response: AgentResponse, } | { "type": "toolExecutionStarted", threadId: ThreadId, turnId: TurnId, toolCallId: ToolCallId, actionDigest: string, policyRevision: string, authority: ToolExecutionAuthority, } | { "type": "toolExecutionEscalated", threadId: ThreadId, turnId: TurnId, toolCallId: ToolCallId, actionDigest: string, policyRevision: string, denial: SandboxDenialOutput, authority: ToolExecutionAuthority, } | { "type": "interactionCancelled", threadId: ThreadId, turnId: TurnId, requestId: RequestId, reason: InteractionCancelReason, } | { "type": "turnCompleted", threadId: ThreadId, turnId: TurnId, } | { "type": "turnFailed", threadId: ThreadId, turnId: TurnId, error: StableTurnError, } | { "type": "turnCancelling", threadId: ThreadId, turnId: TurnId, } | { "type": "turnInterrupted", threadId: ThreadId, turnId: TurnId, };
export type PlanStepStatus = "pending" | "inProgress" | "completed";
export type PlanStep = { step: string, status: PlanStepStatus, };
export type PlanUpdate = { explanation?: string | null, steps: Array<PlanStep>, };
export type StreamCursor = { streamInstanceId: StreamInstanceId, sequence: number, };
export type ItemDelta = { "type": "agentMessage", text: string, } | { "type": "reasoning", text: string, } | { "type": "plan", text: string, };
export type ThreadUpdate = { "type": "committed", event: ThreadEvent, } | { "type": "itemStarted", turnId: TurnId, item: ThreadItem, } | { "type": "itemDelta", turnId: TurnId, itemId: ItemId, delta: ItemDelta, } | { "type": "planUpdated", turnId: TurnId, plan: PlanUpdate, } | { "type": "toolOutputDelta", turnId: TurnId, toolCallId: ToolCallId, stream: ToolOutputStream, text: string, };
export type ThreadUpdateEnvelope = { sessionId: SessionId, threadId: ThreadId, durableSequence: number, streamCursor?: StreamCursor | null, update: ThreadUpdate, };
export type InputItem = { "type": "text", text: string, } | { "type": "image", url: string, };
export type TurnStartResult = { turnId: TurnId, sequence: number, };
export type TurnInterruptResult = { sequence: number, };
export type TurnInteractionResolveResult = { sequence: number, };
export type TypstCompileParams = { source: string, };
export type TypstCompileResult = { "status": "success", resource: ResourceMetadataResult, warnings: Array<TypstDiagnosticDto>, } | { "status": "failed", diagnostics: Array<TypstDiagnosticDto>, };
export type TypstDiagnosticDto = { severity: TypstDiagnosticSeverityDto, message: string, hints: Array<string>, range: TypstSourceRangeDto | null, };
export type TypstDiagnosticSeverityDto = "error" | "warning";
export type TypstSourceRangeDto = { start: number, end: number, };
export type ResourceMetadataParams = { resourceId: string, };
export type ResourceMetadataResult = { resourceId: string, mimeType: string, size: number, sha256: string, };
export type ResourceReadParams = { resourceId: string, offset: number, maxBytes: number, };
export type ResourceReadResult = { resourceId: string, offset: number, dataBase64: string, decodedLength: number, eof: boolean, };
export type ResourceReleaseParams = { resourceId: string, };
export type FsFileType = "directory" | "file" | "symbolicLink" | "other";
export type FsGetMetadataParams = { path: string, };
export type FsGetMetadataResult = { fileType: FsFileType, sizeBytes: number, readonly: boolean, modifiedAtMillis: number | null, };
export type FsReadDirectoryParams = { path: string, };
export type FsReadDirectoryEntry = { name: string, fileType: FsFileType, };
export type FsReadDirectoryResult = { entries: Array<FsReadDirectoryEntry>, };
export type FsReadBinaryFileParams = { path: string, };
export type FsReadBinaryFileResult = { resource: ResourceMetadataResult,
/**
 * Opaque exact-content revision of the resource bytes.
 */
revision: string, };
export type FsReadFileParams = { path: string, };
export type FsReadFileResult = { content: string,
/**
 * Opaque exact-content revision required to protect a later conditional write.
 */
revision: string, };
export type DiffComputeParams = { original: string, modified: string, };
export type DiffRowKindDto = "context" | "added" | "removed" | "modified";
export type DiffRangeDto = { startColumn: number, endColumn: number, };
export type DiffComputeRowDto = { kind: DiffRowKindDto, originalLineIndex: number | null, modifiedLineIndex: number | null, originalChanges: Array<DiffRangeDto>, modifiedChanges: Array<DiffRangeDto>, };
export type DiffHunkDto = { rowStart: number, rowEnd: number, originalStartLineIndex: number, originalLineCount: number, modifiedStartLineIndex: number, modifiedLineCount: number, };
export type DiffComputeResult = { rows: Array<DiffComputeRowDto>, hunks: Array<DiffHunkDto>, originalLineCount: number, modifiedLineCount: number, };
export type SyntaxLanguageDto = "javascript" | "javascriptreact" | "json" | "jsonc" | "rust" | "shell" | "typescript" | "typescriptreact";
export type SyntaxPositionDto = { lineIndex: number, columnIndex: number, };
export type SyntaxRangeDto = { start: SyntaxPositionDto, end: SyntaxPositionDto, };
export type SyntaxTokenKindDto = "attribute" | "comment" | "constant" | "constructor" | "embedded" | "function" | "keyword" | "label" | "module" | "number" | "operator" | "property" | "punctuation" | "string" | "type" | "variable";
export type SyntaxTokenDto = { range: SyntaxRangeDto, kind: SyntaxTokenKindDto, };
export type SyntaxFoldingRangeDto = { range: SyntaxRangeDto, };
export type SyntaxSymbolKindDto = "constant" | "enum" | "field" | "function" | "macro" | "method" | "module" | "static" | "struct" | "trait" | "type" | "variable";
export type SyntaxSymbolDto = { name: string, kind: SyntaxSymbolKindDto, range: SyntaxRangeDto, selectionRange: SyntaxRangeDto, };
export type SyntaxDiagnosticKindDto = "error" | "missing";
export type SyntaxDiagnosticDto = { range: SyntaxRangeDto, kind: SyntaxDiagnosticKindDto, };
export type SyntaxAnalyzeParams = { language: SyntaxLanguageDto, revision: number, text: string, };
export type SyntaxAnalyzeResult = { revision: number, hasErrors: boolean, tokens: Array<SyntaxTokenDto>, foldingRanges: Array<SyntaxFoldingRangeDto>, symbols: Array<SyntaxSymbolDto>, diagnostics: Array<SyntaxDiagnosticDto>, };
export type FsWriteFileParams = { path: string, content: string,
/**
 * When supplied, rejects the write if the file no longer has this exact revision.
 */
expectedRevision?: string | null, };
export type FsWriteFileResult = { metadata: FsGetMetadataResult,
/**
 * Opaque exact-content revision of the successfully written file.
 */
revision: string, };
export type FsChanged = { "type": "pathsChanged", paths: Array<string>, } | { "type": "rescanRequired" };
export type GitChangeStatusDto = "unmodified" | "modified" | "added" | "deleted" | "renamed" | "copied" | "typeChanged" | "unmerged" | "untracked" | "ignored";
export type GitUpstreamDto = { name: string, ahead: number, behind: number, };
export type GitHeadDto = { "type": "branch", name: string, objectId: string, upstream: GitUpstreamDto | null, } | { "type": "detached", objectId: string, } | { "type": "unborn", name: string, };
export type GitSubmoduleStateDto = { isSubmodule: boolean, commitChanged: boolean, trackedChanges: boolean, untrackedChanges: boolean, };
export type GitRepositoryChangeDto = { path: string, originalPath: string | null, indexStatus: GitChangeStatusDto, worktreeStatus: GitChangeStatusDto, conflicted: boolean, submodule: GitSubmoduleStateDto, };
export type GitStatusResult = { streamInstanceId: StreamInstanceId, revision: number, workspacePath: string, head: GitHeadDto, changes: Array<GitRepositoryChangeDto>, };
export type GitStatusChanged = { status: GitStatusResult, };
export type GitBranchDto = { name: string, objectId: string, current: boolean, upstream: string | null, };
export type GitBranchListResult = { branches: Array<GitBranchDto>, };
export type GitCommitSummaryDto = { objectId: string, timestampSeconds: number, subject: string, };
export type GitHistoryResult = { commits: Array<GitCommitSummaryDto>, };
export type GitBranchSwitchParams = { name: string, };
export type GitTextDiffDto = { path: string, original: string, modified: string, additions: number, deletions: number, };
export type GitDiffStatisticsDto = { files: number, additions: number, deletions: number, };
export type GitTextDiffResult = { status: GitStatusResult, diffs: Array<GitTextDiffDto>, statistics: GitDiffStatisticsDto, };
export type GitPathsParams = { paths: Array<string>, };
export type GitCommitParams = { message: string, };
export type GitOperationResult = { status: GitStatusResult, };
export type GitCommitResult = { objectId: string, status: GitStatusResult, };
export type WorkspaceSearchPatternKind = "literal" | "regex";
export type WorkspaceSearchCaseSensitivity = "smart" | "sensitive" | "insensitive";
export type WorkspaceSearchStartParams = { query: string, patternKind: WorkspaceSearchPatternKind, caseSensitivity: WorkspaceSearchCaseSensitivity, includePatterns: Array<string>, excludePatterns: Array<string>, maxResults: number, };
export type WorkspaceSearchStartResult = { searchId: string, };
export type WorkspaceSearchReadParams = { searchId: string, afterMatch: number, maxMatches: number, };
export type WorkspaceSearchMatchRange = { start: number, end: number, };
export type WorkspaceSearchMatch = { path: string, lineNumber: number, preview: string, ranges: Array<WorkspaceSearchMatchRange>, };
export type WorkspaceSearchReadResult = { searchId: string, matches: Array<WorkspaceSearchMatch>, nextMatch: number, completed: boolean, limitHit: boolean, error: string | null, };
export type WorkspaceSearchCancelParams = { searchId: string, };
export type TerminalProfile = { profileId: string, title: string, isDefault: boolean, };
export type TerminalProfileListResult = { profiles: Array<TerminalProfile>, };
export type TerminalProfileSelection = { "type": "default" } | { "type": "profile", profileId: string, };
export type TerminalCreateParams = { rows: number, cols: number, profile: TerminalProfileSelection, };
export type TerminalCreateResult = { terminalId: string, profile: TerminalProfile, };
export type TerminalWriteParams = { terminalId: string, data: string, };
export type TerminalResizeParams = { terminalId: string, rows: number, cols: number, };
export type TerminalReadParams = { terminalId: string, afterSequence: number, afterCommandSequence: number, maxChunks: number, };
export type TerminalOutputChunk = { sequence: number, dataBase64: string, };
export type TerminalCommandStatus = "running" | "completed" | "succeeded" | "failed" | "canceled";
export type TerminalCommandStatusEvent = { sequence: number, commandId: string, status: TerminalCommandStatus, exitCode: number | null, afterOutputSequence: number, };
export type TerminalReadResult = { terminalId: string, chunks: Array<TerminalOutputChunk>, nextSequence: number, outputGap: boolean, commandEvents: Array<TerminalCommandStatusEvent>, nextCommandSequence: number, commandEventGap: boolean, exited: boolean, exitCode: number | null, };
export type TerminalCloseParams = { terminalId: string, };
export type AppServerErrorName = "ParseError" | "InvalidRequest" | "MethodNotFound" | "InvalidParams" | "InternalError" | "ServerOverloaded" | "NotInitialized" | "AlreadyInitialized" | "CommandConflict" | "CoreOperationFailed" | "ResourceNotFound" | "ResourceNotOwner" | "ResourceTooLarge" | "InvalidResourceChunkSize" | "InvalidResourceOffset" | "FileSystemUnavailable" | "FileSystemOperationFailed" | "FileSystemRevisionConflict" | "GitUnavailable" | "GitNotRepository" | "GitOperationFailed" | "DiffOperationFailed" | "SyntaxAnalysisFailed" | "SearchUnavailable" | "SearchNotFound" | "SearchNotOwner" | "SearchBusy" | "TerminalUnavailable" | "TerminalNotFound" | "TerminalNotOwner" | "TerminalBusy" | "TerminalOperationFailed" | "ConfigUnavailable" | "ConfigRevisionConflict" | "SkillsUnavailable" | "SkillOperationFailed" | "SkillNotFound" | "WorkspaceSwitchUnavailable" | "WorkspaceSwitchBusy" | "WorkspaceSwitchFailed" | "WorkspaceTrustRequired" | "ExtensionsUnavailable" | "ExtensionNotFound" | "ExtensionResourceNotFound" | "ExtensionResourceInvalidPath" | "ExtensionOperationFailed";
export type AppServerError = { code: number, message: AppServerErrorName, data: null, };
export type ServerNotification =
  { method: "document/collaboration/update"; params: DocumentCollaborationUpdate }
  | { method: "document/collaboration/presence"; params: DocumentCollaborationPresenceSnapshot }
  | { method: "session/update"; params: SessionUpdateEnvelope }
  | { method: "session/thread/update"; params: ThreadUpdateEnvelope }
  | { method: "config/changed"; params: ConfigChanged }
  | { method: "skills/changed"; params: SkillsChanged }
  | { method: "git/statusChanged"; params: GitStatusChanged }
  | { method: "fs/changed"; params: FsChanged }
;
export type AppServerWireNotification = JsonRpcNotification<ServerNotification>;
export interface AppServerMethodMap {
  "initialize": { params: InitializeParams; result: InitializeResult };
  "workspace/switch": { params: WorkspaceSwitchParams; result: WorkspaceSwitchResult };
  "document/collaboration/open": { params: DocumentCollaborationOpenParams; result: DocumentCollaborationOpenResult };
  "document/collaboration/submit": { params: DocumentCollaborationSubmitParams; result: DocumentCollaborationSubmitResult };
  "document/collaboration/presence/publish": { params: DocumentCollaborationPresenceParams; result: DocumentCollaborationPresenceSnapshot };
  "document/collaboration/presence/read": { params: DocumentCollaborationPresenceReadParams; result: DocumentCollaborationPresenceSnapshot };
  "session/create": { params: SessionCreateParams; result: SessionResult };
  "session/read": { params: SessionReadParams; result: SessionResult };
  "session/list": { params: Record<string, never>; result: SessionListResult };
  "session/subscribe": { params: SessionSubscribeParams; result: SessionSubscribeResult };
  "session/request": { params: SessionRequestParams; result: SessionRequestResult };
  "session/unsubscribe": { params: SessionUnsubscribeParams; result: null };
  "session/thread/read": { params: SessionThreadReadParams; result: SessionThreadReadResult };
  "session/thread/subscribe": { params: SessionThreadSubscribeParams; result: SessionThreadSubscribeResult };
  "session/thread/unsubscribe": { params: SessionThreadUnsubscribeParams; result: null };
  "config/read": { params: Record<string, never>; result: ConfigReadResult };
  "model/list": { params: Record<string, never>; result: ModelListResult };
  "config/update": { params: ConfigUpdateParams; result: ConfigCommandResult };
  "languageServer/configure": { params: LanguageServerConfigureParams; result: ConfigCommandResult };
  "languageServer/remove": { params: LanguageServerRemoveParams; result: ConfigCommandResult };
  "provider/configure": { params: ProviderConfigureParams; result: ConfigCommandResult };
  "provider/remove": { params: ProviderRemoveParams; result: ConfigCommandResult };
  "mcp/server/upsert": { params: McpServerUpsertParams; result: ConfigCommandResult };
  "mcp/server/remove": { params: McpServerRemoveParams; result: ConfigCommandResult };
  "mcp/server/enablement/set": { params: McpServerSetEnablementParams; result: ConfigCommandResult };
  "skill/source/add": { params: SkillSourceAddParams; result: ConfigCommandResult };
  "skill/source/remove": { params: SkillSourceRemoveParams; result: ConfigCommandResult };
  "skill/source/enablement/set": { params: SkillSourceSetEnablementParams; result: ConfigCommandResult };
  "plugin/request/upsert": { params: PluginRequestUpsertParams; result: ConfigCommandResult };
  "plugin/request/remove": { params: PluginRequestRemoveParams; result: ConfigCommandResult };
  "plugin/request/enablement/set": { params: PluginRequestSetEnablementParams; result: ConfigCommandResult };
  "hook/upsert": { params: HookUpsertParams; result: ConfigCommandResult };
  "hook/remove": { params: HookRemoveParams; result: ConfigCommandResult };
  "hook/enablement/set": { params: HookSetEnablementParams; result: ConfigCommandResult };
  "skills/list": { params: SkillListParams; result: SkillListResult };
  "skill/enablement/set": { params: SkillSetEnablementParams; result: ConfigCommandResult };
  "extensions/list": { params: ExtensionListParams; result: ExtensionListResult };
  "extensions/resource/open": { params: ExtensionResourceOpenParams; result: ExtensionResourceOpenResult };
  "document/typst/compile": { params: TypstCompileParams; result: TypstCompileResult };
  "resource/metadata": { params: ResourceMetadataParams; result: ResourceMetadataResult };
  "resource/read": { params: ResourceReadParams; result: ResourceReadResult };
  "resource/release": { params: ResourceReleaseParams; result: null };
  "fs/getMetadata": { params: FsGetMetadataParams; result: FsGetMetadataResult };
  "fs/readDirectory": { params: FsReadDirectoryParams; result: FsReadDirectoryResult };
  "fs/readFile": { params: FsReadFileParams; result: FsReadFileResult };
  "fs/readBinaryFile": { params: FsReadBinaryFileParams; result: FsReadBinaryFileResult };
  "diff/compute": { params: DiffComputeParams; result: DiffComputeResult };
  "syntax/analyze": { params: SyntaxAnalyzeParams; result: SyntaxAnalyzeResult };
  "fs/writeFile": { params: FsWriteFileParams; result: FsWriteFileResult };
  "git/status": { params: Record<string, never>; result: GitStatusResult };
  "git/textDiff": { params: Record<string, never>; result: GitTextDiffResult };
  "git/branch/list": { params: Record<string, never>; result: GitBranchListResult };
  "git/history": { params: Record<string, never>; result: GitHistoryResult };
  "git/branch/switch": { params: GitBranchSwitchParams; result: GitOperationResult };
  "git/stage": { params: GitPathsParams; result: GitOperationResult };
  "git/unstage": { params: GitPathsParams; result: GitOperationResult };
  "git/discardWorktree": { params: GitPathsParams; result: GitOperationResult };
  "git/commit": { params: GitCommitParams; result: GitCommitResult };
  "git/fetch": { params: Record<string, never>; result: GitOperationResult };
  "git/pull": { params: Record<string, never>; result: GitOperationResult };
  "git/push": { params: Record<string, never>; result: GitOperationResult };
  "workspace/search/start": { params: WorkspaceSearchStartParams; result: WorkspaceSearchStartResult };
  "workspace/search/read": { params: WorkspaceSearchReadParams; result: WorkspaceSearchReadResult };
  "workspace/search/cancel": { params: WorkspaceSearchCancelParams; result: null };
  "terminal/profile/list": { params: Record<string, never>; result: TerminalProfileListResult };
  "terminal/create": { params: TerminalCreateParams; result: TerminalCreateResult };
  "terminal/write": { params: TerminalWriteParams; result: null };
  "terminal/resize": { params: TerminalResizeParams; result: null };
  "terminal/read": { params: TerminalReadParams; result: TerminalReadResult };
  "terminal/close": { params: TerminalCloseParams; result: null };
}
export type AppServerMethod = keyof AppServerMethodMap;
export type MethodParams<M extends AppServerMethod> = AppServerMethodMap[M]["params"];
export type MethodResult<M extends AppServerMethod> = AppServerMethodMap[M]["result"];
export type AppServerRequest<M extends AppServerMethod> = JsonRpcRequest<MethodParams<M>>;
export type AppServerResponse<M extends AppServerMethod> = JsonRpcResponse<MethodResult<M>, AppServerError>;
export type AppServerMethodDefinition<M extends AppServerMethod> = {
readonly method: M;
readonly __params?: MethodParams<M>;
readonly __result?: MethodResult<M>;
};
export const APP_SERVER_METHODS: { [M in AppServerMethod]: AppServerMethodDefinition<M> } = {
  "initialize": { method: "initialize" },
  "workspace/switch": { method: "workspace/switch" },
  "document/collaboration/open": { method: "document/collaboration/open" },
  "document/collaboration/submit": { method: "document/collaboration/submit" },
  "document/collaboration/presence/publish": { method: "document/collaboration/presence/publish" },
  "document/collaboration/presence/read": { method: "document/collaboration/presence/read" },
  "session/create": { method: "session/create" },
  "session/read": { method: "session/read" },
  "session/list": { method: "session/list" },
  "session/subscribe": { method: "session/subscribe" },
  "session/request": { method: "session/request" },
  "session/unsubscribe": { method: "session/unsubscribe" },
  "session/thread/read": { method: "session/thread/read" },
  "session/thread/subscribe": { method: "session/thread/subscribe" },
  "session/thread/unsubscribe": { method: "session/thread/unsubscribe" },
  "config/read": { method: "config/read" },
  "model/list": { method: "model/list" },
  "config/update": { method: "config/update" },
  "languageServer/configure": { method: "languageServer/configure" },
  "languageServer/remove": { method: "languageServer/remove" },
  "provider/configure": { method: "provider/configure" },
  "provider/remove": { method: "provider/remove" },
  "mcp/server/upsert": { method: "mcp/server/upsert" },
  "mcp/server/remove": { method: "mcp/server/remove" },
  "mcp/server/enablement/set": { method: "mcp/server/enablement/set" },
  "skill/source/add": { method: "skill/source/add" },
  "skill/source/remove": { method: "skill/source/remove" },
  "skill/source/enablement/set": { method: "skill/source/enablement/set" },
  "plugin/request/upsert": { method: "plugin/request/upsert" },
  "plugin/request/remove": { method: "plugin/request/remove" },
  "plugin/request/enablement/set": { method: "plugin/request/enablement/set" },
  "hook/upsert": { method: "hook/upsert" },
  "hook/remove": { method: "hook/remove" },
  "hook/enablement/set": { method: "hook/enablement/set" },
  "skills/list": { method: "skills/list" },
  "skill/enablement/set": { method: "skill/enablement/set" },
  "extensions/list": { method: "extensions/list" },
  "extensions/resource/open": { method: "extensions/resource/open" },
  "document/typst/compile": { method: "document/typst/compile" },
  "resource/metadata": { method: "resource/metadata" },
  "resource/read": { method: "resource/read" },
  "resource/release": { method: "resource/release" },
  "fs/getMetadata": { method: "fs/getMetadata" },
  "fs/readDirectory": { method: "fs/readDirectory" },
  "fs/readFile": { method: "fs/readFile" },
  "fs/readBinaryFile": { method: "fs/readBinaryFile" },
  "diff/compute": { method: "diff/compute" },
  "syntax/analyze": { method: "syntax/analyze" },
  "fs/writeFile": { method: "fs/writeFile" },
  "git/status": { method: "git/status" },
  "git/textDiff": { method: "git/textDiff" },
  "git/branch/list": { method: "git/branch/list" },
  "git/history": { method: "git/history" },
  "git/branch/switch": { method: "git/branch/switch" },
  "git/stage": { method: "git/stage" },
  "git/unstage": { method: "git/unstage" },
  "git/discardWorktree": { method: "git/discardWorktree" },
  "git/commit": { method: "git/commit" },
  "git/fetch": { method: "git/fetch" },
  "git/pull": { method: "git/pull" },
  "git/push": { method: "git/push" },
  "workspace/search/start": { method: "workspace/search/start" },
  "workspace/search/read": { method: "workspace/search/read" },
  "workspace/search/cancel": { method: "workspace/search/cancel" },
  "terminal/profile/list": { method: "terminal/profile/list" },
  "terminal/create": { method: "terminal/create" },
  "terminal/write": { method: "terminal/write" },
  "terminal/resize": { method: "terminal/resize" },
  "terminal/read": { method: "terminal/read" },
  "terminal/close": { method: "terminal/close" },
};
export type AppServerNotificationMethod = ServerNotification["method"];
export type NotificationParams<M extends AppServerNotificationMethod> =
Extract<ServerNotification, { method: M }>["params"];
export type AppServerNotificationDefinition<M extends AppServerNotificationMethod> = {
readonly method: M;
readonly __params?: NotificationParams<M>;
};
export const APP_SERVER_NOTIFICATIONS: {
[M in AppServerNotificationMethod]: AppServerNotificationDefinition<M>
} = {
  "document/collaboration/update": { method: "document/collaboration/update" },
  "document/collaboration/presence": { method: "document/collaboration/presence" },
  "session/update": { method: "session/update" },
  "session/thread/update": { method: "session/thread/update" },
  "config/changed": { method: "config/changed" },
  "skills/changed": { method: "skills/changed" },
  "git/statusChanged": { method: "git/statusChanged" },
  "fs/changed": { method: "fs/changed" },
};
