[package]
name = "zeta-file-system"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
name = "zeta_file_system"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
zeta-sandboxing = { workspace = true }
zeta-tools = { workspace = true }

[dev-dependencies]
zeta-async-utils = { workspace = true }
zeta-protocol = { workspace = true }

[lints]
workspace = true
