/** Stable Stanza API for standalone editors and programmatic document consumers. */
import { createEditorBaseApi } from './common/services/editorBaseApi.js';
import { createStandaloneEditorApi } from "./standalone/browser/standaloneEditor.js";
import { createStandaloneLanguagesApi } from './standalone/browser/standaloneLanguages.js';

const baseApi = createEditorBaseApi();
export const editor = createStandaloneEditorApi();
export const languages = createStandaloneLanguagesApi();

export const URI = baseApi.URI;
export type { CancellationToken } from "../base/common/cancellation.js";
export type { IDisposable } from "../base/common/lifecycle.js";
export { EditorLineWrapping, WrappingIndent } from "./common/config/editorOptions.js";
export type { IEditorMinimapOptions } from './common/config/editorOptions.js';
export { EditorTextDirection } from "./browser/view.js";
export { ContentWidgetPositionPreference, OverlayWidgetPositionPreference } from './browser/editorBrowser.js';
export type { IContentWidget, IContentWidgetPosition, IContentWidgetRenderedCoordinate, IOverlayWidget, IOverlayWidgetPosition, IOverlayWidgetPositionCoordinates } from './browser/editorBrowser.js';
export type { IViewZone, IViewZoneChangeAccessor } from './browser/editorBrowser.js';
export { PositionAffinity } from './common/model.js';
export { ColorScheme } from "../platform/theme/common/theme.js";
export type { IStandaloneCodeEditor } from './standalone/browser/standaloneCodeEditor.js';
export type { IStandaloneEditorApi, IStandaloneEditorConstructionOptions } from "./standalone/browser/standaloneEditor.js";
export type { IStandaloneLanguagesApi } from './standalone/browser/standaloneLanguages.js';
export type { LanguageDescription, LanguageDescriptionChangeEvent, LanguageDescriptionContribution, LanguageDescriptionRegistration, LanguageRegistrationOptions } from './common/languages/languageRegistry.js';
export type { TextResourceLanguageInput } from '../platform/language/common/textResourceLanguage.js';
export type { LanguageProviderBatch, LanguageProviderBatchRegistration } from './common/services/languageFeatures.js';
export type { CharacterPair, IAutoClosingPair, IAutoClosingPairConditional, LanguageConfiguration } from './common/languages/languageConfiguration.js';
export { RGBA8 } from './common/core/misc/rgba.js';
export type { DocumentColorProvider, IColor, IColorInformation, IColorPresentation, TextEdit } from './common/languages.js';
export type { TextSnapshot } from './common/core/textChange.js';
export { LanguageCompletionInsertTextFormat, LanguageCompletionItemKind } from './common/languages/completion/languageCompletions.js';
export type { LanguageCompletionCommand, LanguageCompletionItem, LanguageCompletionItemDetails, LanguageCompletionResult, LanguageCompletionTextEdit } from './common/languages/completion/languageCompletions.js';
export { LanguageCompletionTriggerKind } from './common/languages/completion/languageCompletionProviders.js';
export type { LanguageCompletionContext, LanguageCompletionIncompleteRefreshContext, LanguageCompletionInvokeContext, LanguageCompletionProvider, LanguageCompletionProviderCommandRequest, LanguageCompletionProviderItem, LanguageCompletionProviderRequest, LanguageCompletionProviderResolveRequest, LanguageCompletionProviderResult, LanguageCompletionRequest, LanguageCompletionTriggerCharacterContext } from './common/languages/completion/languageCompletionProviders.js';
export { DocumentHighlightKind } from './common/languages.js';
export type { DocumentHighlight, DocumentHighlightProvider, MultiDocumentHighlightProvider } from './common/languages.js';
export type { LanguageFeatureRequest } from './common/languages/languageFeatureRequest.js';
export { LanguageDiagnosticSeverity } from './common/languages/languageResults.js';
export type { LanguageDiagnostic, LanguageDiagnosticCode, LanguageDiagnosticResult, LanguageToken, LanguageTokenResult, LanguageTokenResultDelta, LanguageTokenResultSplice } from './common/languages/languageResults.js';
export type { LanguageWorkerDocumentSynchronization } from './common/services/textModelSync/textModelSync.protocol.js';
export type { LanguageCreateFileEdit, LanguageDeleteFileEdit, LanguageDeleteMode, LanguageExistingTargetBehavior, LanguageMissingTargetBehavior, LanguageRenameFileEdit, LanguageTextDocumentEdit, LanguageWorkspaceEdit, LanguageWorkspaceEditEntry } from './common/languages/languageWorkspaceEdit.js';
export type { SyntaxProvider, SyntaxProviderRequest, SyntaxRequest } from './common/languages/syntax/syntaxProviders.js';
export type { LanguageWorkspaceSymbol, LanguageWorkspaceSymbolKind, LanguageWorkspaceSymbolProvider } from './common/languages/workspaceSymbols.js';
export type { LanguageCallHierarchyEntry, LanguageCallHierarchyProvider, LanguageHierarchyFollowupRequest, LanguageHierarchyItem, LanguageHierarchyRequest, LanguageTypeHierarchyProvider } from './contrib/callHierarchy/common/languageHierarchy.js';
export type { LanguageCodeAction, LanguageCodeActionProvider, LanguageCodeActionRequest } from './contrib/codeAction/common/languageCodeActions.js';
export type { LanguageCodeLens, LanguageCodeLensCommand, LanguageCodeLensProvider, LanguageCodeLensRequest } from './contrib/codelens/common/languageCodeLenses.js';
export type { LanguageColorPresentationRequest, LanguageColorProvider, LanguageColorRequest } from './contrib/colorPicker/common/languageColors.js';
export type { LanguageDocumentSymbol, LanguageDocumentSymbolProvider, LanguageDocumentSymbolRequest, LanguageSymbolKind } from './contrib/documentSymbols/common/languageDocumentSymbols.js';
export type { LanguageFoldingRange, LanguageFoldingRangeKind, LanguageFoldingRangeProvider, LanguageFoldingRangeRequest } from './contrib/folding/common/languageFoldingRanges.js';
export type { LanguageFormattingOptions, LanguageFormattingProvider, LanguageFormattingRequest } from './contrib/format/common/formatCommands.js';
export type { LanguageDeclarationProvider, LanguageDefinitionProvider, LanguageImplementationProvider, LanguageLocation, LanguageLocationRequest, LanguageReferenceProvider, LanguageReferenceRequest, LanguageTypeDefinitionProvider } from './contrib/gotoSymbol/common/languageNavigation.js';
export type { LanguageHover, LanguageHoverContent, LanguageHoverProvider, LanguageHoverRequest } from './contrib/hover/common/hover.js';
export type { LanguageInlayHint, LanguageInlayHintKind, LanguageInlayHintLabel, LanguageInlayHintsProvider, LanguageInlayHintsRequest } from './contrib/inlayHints/common/languageInlayHints.js';
export type { LanguageInlineCompletionItem, LanguageInlineCompletionsProvider, LanguageInlineCompletionsRequest } from './contrib/inlineCompletions/common/inlineCompletions.js';
export type { LanguageLinkedEditingProvider, LanguageLinkedEditingRanges, LanguageLinkedEditingRequest } from './contrib/linkedEditing/common/languageLinkedEditing.js';
export type { LanguageLink, LanguageLinkProvider, LanguageLinkRequest } from './contrib/links/common/languageLinks.js';
export type { LanguageParameterHints, LanguageParameterHintsContext, LanguageParameterHintsProvider, LanguageParameterHintsRequest, LanguageParameterInformation, LanguageSignatureInformation } from './contrib/parameterHints/common/languageParameterHints.js';
export type { LanguageRenamePreparation, LanguageRenameProvider, LanguageRenameRequest } from './contrib/rename/common/languageRename.js';
export type { LanguageSelectionRangeProvider, LanguageSelectionRangeRequest } from './contrib/smartSelect/common/selectionRanges.js';
export type { LanguageSemanticTokensProvider, LanguageSemanticTokensRequest } from './common/languages.js';
export type { StandaloneServiceOverrides } from "./standalone/browser/standaloneServices.js";
export type { NamedEditorThemeData } from "./standalone/common/namedEditorTheme.js";
export const Position = baseApi.Position;
export type { IPosition } from "./common/core/position.js";
export const Range = baseApi.Range;
export type { IRange } from "./common/core/range.js";
export const SelectionDirection = baseApi.SelectionDirection;
export const Selection = baseApi.Selection;
export type { ISelection } from "./common/core/selection.js";
export { TextModel } from "./common/model/textModel.js";
export type { TextEditOptions } from "./common/model/textModel.js";
export type { TextModelHistoryLimit } from "./common/model/textModel.js";
export type { TextModelMaintenanceOptions } from "./common/model/textModel.js";
export type { TextModelOptions } from "./common/model/textModel.js";
export { TextModelRemoteHistoryPolicy } from "./common/model/textModelBlockState.js";
export type { TextModelBlockChange, TextModelBlockOptions } from "./common/model/textModelBlockState.js";
export { createLineDocumentSnapshot, LineFacetStore, LineSequence, PointStore, RangeStore, RegionStore, RelationStore, linePoint } from "./common/model/lineDocument.js";
export type { AtomId, FacetId, InlineAtom, LineDocumentSnapshot, LineDocumentSnapshotInput, LineFacet, LineId, LinePoint, LineRegion, LineRelation, LineRelationTarget, LineSemanticAttributes, LineSemanticValue, MarkId, ModelLine, PersistentMark, RegionId, RelationId } from "./common/model/lineDocument.js";
export { createDocumentNode } from "./common/model/document.js";
export { createDocumentRoot } from "./common/model/document.js";
export { createTextNode } from "./common/model/document.js";
export type { DocumentAttributes } from "./common/model/document.js";
export type { DocumentMark } from "./common/model/document.js";
export type { DocumentNode } from "./common/model/document.js";
export type { DocumentNodeId } from "./common/model/document.js";
export { createDefaultDocumentSchema } from "./common/model/documentSchema.js";
export { DocumentSchema } from "./common/model/documentSchema.js";
export type { DocumentSchemaOptions } from "./common/model/documentSchema.js";
export { DocumentTransaction } from "./common/model/documentTransaction.js";
export type { DocumentStep } from "./common/model/documentTransaction.js";
export { DocumentSerializationError } from "./common/model/documentSerialization.js";
export { deserializeDocument } from "./common/model/documentSerialization.js";
export { serializeDocument } from "./common/model/documentSerialization.js";
export { allSelection } from "./common/core/documentSelection.js";
export { nodeSelection } from "./common/core/documentSelection.js";
export { textSelection } from "./common/core/documentSelection.js";
export type { DocumentSelection } from "./common/core/documentSelection.js";
