/** Stable Stanza API for standalone editors and programmatic document consumers. */
import { createStandaloneEditorApi } from "./standalone/browser/standaloneEditor.js";

export const editor = createStandaloneEditorApi();

export { URI } from "../base/common/uri.js";
export { EditorLineWrapping, WrappingIndent } from "./common/config/editorOptions.js";
export { EditorMinimap, EditorTextDirection } from "./browser/view.js";
export { ColorScheme } from "../platform/theme/common/theme.js";
export type { IStandaloneCodeEditor, IStandaloneEditorApi, IStandaloneEditorConstructionOptions } from "./standalone/browser/standaloneEditor.js";
export type { StandaloneServiceOverrides } from "./standalone/browser/standaloneServices.js";
export type { IStandaloneThemeData } from "./standalone/common/standaloneTheme.js";
export { TextPosition } from "./common/core/position.js";
export type { IPosition } from "./common/core/position.js";
export { TextRange } from "./common/core/range.js";
export type { IRange } from "./common/core/range.js";
export type { ITextRange } from "./common/core/range.js";
export { SelectionDirection } from "./common/core/selection.js";
export { TextSelection } from "./common/core/selection.js";
export type { ISelection } from "./common/core/selection.js";
export { TextModel } from "./common/model/textModel.js";
export type { TextEditOptions } from "./common/model/textModel.js";
export type { TextModelHistoryLimit } from "./common/model/textModel.js";
export type { TextModelMaintenanceOptions } from "./common/model/textModel.js";
export type { TextModelOptions } from "./common/model/textModel.js";
export { TextModelRemoteHistoryPolicy } from "./common/model/textModelBlockState.js";
export type { TextModelBlockChange, TextModelBlockOptions } from "./common/model/textModelBlockState.js";
export { createLineDocumentSnapshot, LineFacetStore, LineSequence, PointStore, RangeStore, RegionStore, RelationStore, linePoint } from "./common/model/lineDocument.js";
export type { AtomId, FacetId, InlineAtom, LineDocumentSnapshot, LineDocumentSnapshotInput, LineFacet, LineId, LinePoint, LineRegion, LineRelation, LineRelationTarget, LineSemanticAttributes, LineSemanticValue, MarkId, ModelLine, PersistentMark, RegionId, RelationId } from "./common/model/lineDocument.js";
export { createDocumentNode } from "./common/model/document.js";
export { createDocumentRoot } from "./common/model/document.js";
export { createTextNode } from "./common/model/document.js";
export type { DocumentAttributes } from "./common/model/document.js";
export type { DocumentMark } from "./common/model/document.js";
export type { DocumentNode } from "./common/model/document.js";
export type { DocumentNodeId } from "./common/model/document.js";
export { createDefaultDocumentSchema } from "./common/model/documentSchema.js";
export { DocumentSchema } from "./common/model/documentSchema.js";
export type { DocumentSchemaOptions } from "./common/model/documentSchema.js";
export { DocumentTransaction } from "./common/model/documentTransaction.js";
export type { DocumentStep } from "./common/model/documentTransaction.js";
export { DocumentSerializationError } from "./common/model/documentSerialization.js";
export { deserializeDocument } from "./common/model/documentSerialization.js";
export { serializeDocument } from "./common/model/documentSerialization.js";
export { allSelection } from "./common/core/documentSelection.js";
export { nodeSelection } from "./common/core/documentSelection.js";
export { textSelection } from "./common/core/documentSelection.js";
export type { DocumentSelection } from "./common/core/documentSelection.js";
