/** Stable Stanza API for standalone editors and programmatic document consumers. */
import { createEditorBaseApi } from './common/services/editorBaseApi.js';
import { createStandaloneEditorApi } from "./standalone/browser/standaloneEditor.js";
import { createStandaloneLanguagesApi } from './standalone/browser/standaloneLanguages.js';

const baseApi = createEditorBaseApi();
export const editor = createStandaloneEditorApi();
export const languages = createStandaloneLanguagesApi();

export const URI = baseApi.URI;
export { EditorLineWrapping, WrappingIndent } from "./common/config/editorOptions.js";
export { EditorMinimap, EditorTextDirection } from "./browser/view.js";
export { ColorScheme } from "../platform/theme/common/theme.js";
export type { IStandaloneCodeEditor, IStandaloneEditorApi, IStandaloneEditorConstructionOptions } from "./standalone/browser/standaloneEditor.js";
export type { IStandaloneLanguagesApi } from './standalone/browser/standaloneLanguages.js';
export type { LanguageDescription, LanguageRegistrationOptions } from './common/languages/languageRegistry.js';
export type { LanguageConfiguration, LanguageConfigurationRegistrationOptions } from './common/languages/languageConfiguration.js';
export type { SyntaxProvider } from './common/languages/syntax/syntaxProviders.js';
export type { LanguageCompletionProvider } from './common/languages/completion/languageCompletionProviders.js';
export type { DocumentHighlightProvider, MultiDocumentHighlightProvider } from './common/languages/documentHighlights.js';
export type { LanguageWorkspaceSymbolProvider } from './common/languages/workspaceSymbols.js';
export type { LanguageCallHierarchyProvider, LanguageTypeHierarchyProvider } from './contrib/callHierarchy/common/languageHierarchy.js';
export type { LanguageCodeActionProvider } from './contrib/codeAction/common/codeAction.js';
export type { LanguageCodeLensProvider } from './contrib/codelens/common/codelens.js';
export type { LanguageColorProvider } from './contrib/colorPicker/common/color.js';
export type { LanguageDocumentSymbolProvider } from './contrib/documentSymbols/common/documentSymbols.js';
export type { LanguageFoldingRangeProvider } from './contrib/folding/common/folding.js';
export type { LanguageFormattingProvider } from './contrib/format/common/formatCommands.js';
export type { LanguageDeclarationProvider, LanguageDefinitionProvider, LanguageImplementationProvider, LanguageReferenceProvider, LanguageTypeDefinitionProvider } from './contrib/gotoSymbol/common/languageNavigation.js';
export type { LanguageHoverProvider } from './contrib/hover/common/hover.js';
export type { LanguageInlayHintsProvider } from './contrib/inlayHints/common/inlayHints.js';
export type { LanguageInlineCompletionsProvider } from './contrib/inlineCompletions/common/inlineCompletions.js';
export type { LanguageLinkedEditingProvider } from './contrib/linkedEditing/common/linkedEditing.js';
export type { LanguageLinkProvider } from './contrib/links/common/links.js';
export type { LanguageParameterHintsProvider } from './contrib/parameterHints/common/parameterHints.js';
export type { LanguageRenameProvider } from './contrib/rename/common/rename.js';
export type { LanguageSelectionRangeProvider } from './contrib/smartSelect/common/selectionRanges.js';
export type { LanguageSemanticTokensProvider } from './contrib/semanticTokens/common/semanticTokens.js';
export type { StandaloneServiceOverrides } from "./standalone/browser/standaloneServices.js";
export type { IStandaloneThemeData } from "./standalone/common/standaloneTheme.js";
export const TextPosition = baseApi.TextPosition;
export type { IPosition } from "./common/core/position.js";
export const TextRange = baseApi.TextRange;
export type { IRange } from "./common/core/range.js";
export type { ITextRange } from "./common/core/range.js";
export const SelectionDirection = baseApi.SelectionDirection;
export const TextSelection = baseApi.TextSelection;
export type { ISelection } from "./common/core/selection.js";
export { TextModel } from "./common/model/textModel.js";
export type { TextEditOptions } from "./common/model/textModel.js";
export type { TextModelHistoryLimit } from "./common/model/textModel.js";
export type { TextModelMaintenanceOptions } from "./common/model/textModel.js";
export type { TextModelOptions } from "./common/model/textModel.js";
export { TextModelRemoteHistoryPolicy } from "./common/model/textModelBlockState.js";
export type { TextModelBlockChange, TextModelBlockOptions } from "./common/model/textModelBlockState.js";
export { createLineDocumentSnapshot, LineFacetStore, LineSequence, PointStore, RangeStore, RegionStore, RelationStore, linePoint } from "./common/model/lineDocument.js";
export type { AtomId, FacetId, InlineAtom, LineDocumentSnapshot, LineDocumentSnapshotInput, LineFacet, LineId, LinePoint, LineRegion, LineRelation, LineRelationTarget, LineSemanticAttributes, LineSemanticValue, MarkId, ModelLine, PersistentMark, RegionId, RelationId } from "./common/model/lineDocument.js";
export { createDocumentNode } from "./common/model/document.js";
export { createDocumentRoot } from "./common/model/document.js";
export { createTextNode } from "./common/model/document.js";
export type { DocumentAttributes } from "./common/model/document.js";
export type { DocumentMark } from "./common/model/document.js";
export type { DocumentNode } from "./common/model/document.js";
export type { DocumentNodeId } from "./common/model/document.js";
export { createDefaultDocumentSchema } from "./common/model/documentSchema.js";
export { DocumentSchema } from "./common/model/documentSchema.js";
export type { DocumentSchemaOptions } from "./common/model/documentSchema.js";
export { DocumentTransaction } from "./common/model/documentTransaction.js";
export type { DocumentStep } from "./common/model/documentTransaction.js";
export { DocumentSerializationError } from "./common/model/documentSerialization.js";
export { deserializeDocument } from "./common/model/documentSerialization.js";
export { serializeDocument } from "./common/model/documentSerialization.js";
export { allSelection } from "./common/core/documentSelection.js";
export { nodeSelection } from "./common/core/documentSelection.js";
export { textSelection } from "./common/core/documentSelection.js";
export type { DocumentSelection } from "./common/core/documentSelection.js";
