//! Product owner for Plugin discovery, installation, activation, and Marketplace sources.

mod manager;
mod marketplace_activation;
mod marketplace_store;
mod plugin_activation;
mod plugin_authority;
mod plugin_discovery;
mod plugin_package;
mod provider;
mod registry;

use ash_plugin::InstalledPluginRef;
use ash_plugin::LocalPluginCatalog;
use ash_plugin::LocalPluginPackage;
use ash_plugin::PluginError;
use ash_plugin::PluginErrorKind;
use ash_plugin::PluginManifest;
use ash_plugin::PluginPackageDigest;
use ash_plugin::PluginPackageDigestAlgorithm;
use ash_plugin::PluginPackageId;
use ash_plugin::PluginPackageSource;
use ash_plugin::PluginPath;
use ash_plugin::PluginVersion;

pub use manager::LocalCapabilitySource;
pub use manager::PluginsManager;
pub use plugin_activation::PluginActivationSnapshot;
pub use plugin_authority::PluginActivationAuthority;
pub use plugin_authority::PluginAuthorityChange;
pub use plugin_authority::PluginAuthorityCommand;
pub use plugin_authority::PluginAuthorityCommandId;
pub use plugin_authority::PluginAuthorityCommandRequest;
pub use plugin_authority::PluginAuthorityCommandResult;
pub use plugin_authority::PluginAuthorityDisposition;
pub use plugin_authority::PluginAuthoritySnapshot;
pub use plugin_authority::PluginAuthoritySubscription;
pub use plugin_authority::PluginInstallResult;
pub use plugin_authority::PluginInvocationFence;
pub use plugin_authority::PluginInvocationLease;
pub use plugin_discovery::project_local_plugin_discovery;
pub use plugin_package::InstalledPluginPackage;
pub use plugin_package::PluginPackageStore;
pub use provider::PluginPackageCapability;
pub use provider::PluginPackagePayload;
pub use provider::PluginProvider;
pub use provider::PluginProviders;
pub use registry::AcquireCapabilityRequest;
pub use registry::AcquiredCapability;
pub use registry::ActivationSpec;
pub use registry::ArtifactHandle;
pub use registry::AvailableCapability;
pub use registry::CapabilityDescriptor;
pub use registry::CapabilityKind;
pub use registry::CapabilityLease;
pub use registry::CapabilityRef;
pub use registry::ConnectorActivationSpec;
pub use registry::DownloadPackageRequest;
pub use registry::ExecutableActivationSpec;
pub use registry::ExecutableRuntime;
pub use registry::GetPackageRequest;
pub use registry::InstallPackageRequest;
pub use registry::InstallationState;
pub use registry::InstalledPackage;
pub use registry::LanguageActivationSpec;
pub use registry::ListInstalledRequest;
pub use registry::LocalizationActivationSpec;
pub use registry::MarketplaceClientError;
pub use registry::MarketplaceClientErrorKind;
pub use registry::MarketplaceErrorCode;
pub use registry::MarketplaceRemoteClient;
pub use registry::McpActivationSpec;
pub use registry::McpTransportSpec;
pub use registry::OpenResourceRequest;
pub use registry::PackageDetails;
pub use registry::PackageRef;
pub use registry::PackageSource;
pub use registry::PackageSummary;
pub use registry::PluginPackageService;
pub use registry::ReleaseCapabilityOutcome;
pub use registry::ReleaseCapabilityRequest;
pub use registry::RemoteMarketplaceConfig;
pub use registry::ResourceContent;
pub use registry::ResourceRef;
pub use registry::SearchPackagesRequest;
pub use registry::SearchPackagesResult;
pub use registry::SkillActivationSpec;
pub use registry::ThemeActivationSpec;
pub use registry::UninstallMode;
pub use registry::UninstallPackageRequest;
pub use registry::UpdatePackageRequest;
pub use registry::UpstreamReference;
pub use registry::UpstreamRegistry;

#[cfg(test)]
#[path = "manager_tests.rs"]
mod manager_tests;
