packages:
  - build
  - scripts
  - zeta-ts
  - docs-site
patchedDependencies:
  native-keymap@3.3.9: patches/native-keymap@3.3.9.patch
allowBuilds:
  electron: true
  esbuild: true
  native-keymap: true
  sharp: true
  unrs-resolver: true
  workerd: true
