import { registerColor } from "../colorRegistry.js";
import { foreground, mutedForeground, widgetBorder, widgetShadow } from "./baseColors.js";

const owner = "platform.theme.components";
const color = (id: string, dark: string, light: string, description: string): string => registerColor(id, { dark, light }, { description, owner });
const alias = (id: string, value: string, description: string): string => registerColor(id, { dark: value, light: value }, { description, owner });

export const inputForeground = alias("input.foreground", foreground, "Input text foreground.");
export const inputBackground = color("input.background", "#313131", "#ffffff", "Input background.");
export const inputBorder = color("input.border", "#3c3c3c", "#cecece", "Input border.");
export const inputPlaceholderForeground = alias("input.placeholderForeground", mutedForeground, "Input placeholder foreground.");
export const selectionForeground = color("selection.foreground", "#ffffff", "#000000", "Selected text foreground.");
export const selectionBackground = color("selection.background", "#264f78", "#add6ff", "Selected text background.");
export const hoverForeground = alias("hover.foreground", foreground, "Foreground for managed Hovers.");
export const hoverBackground = color("hover.background", "#252526", "#f8f8f8", "Background for managed Hovers.");
export const hoverBorder = alias("hover.border", widgetBorder, "Border around managed Hovers.");
export const hoverShadow = alias("hover.shadow", widgetShadow, "Shadow around managed Hovers.");
export const listHoverBackground = color("list.hoverBackground", "#2a2d2e", "#e8e8e8", "Hovered list row background.");
export const listActiveSelectionForeground = color("list.activeSelectionForeground", "#ffffff", "#ffffff", "Active list selection foreground.");
export const listActiveSelectionBackground = color("list.activeSelectionBackground", "#04395e", "#0060c0", "Active list selection background.");
export const treeIndentGuidesStroke = color("tree.indentGuidesStroke", "#585858", "#a9a9a9", "Tree indentation guide stroke.");
export const menuSelectionForeground = alias("menu.selectionForeground", listActiveSelectionForeground, "Selected menu item foreground.");
export const menuSelectionBackground = alias("menu.selectionBackground", listActiveSelectionBackground, "Selected menu item background.");
export const buttonForeground = alias("button.foreground", foreground, "Default button foreground.");
export const buttonBackground = color("button.background", "#0e639c", "#0078d4", "Default button background.");
export const buttonHoverBackground = alias("button.hoverBackground", listHoverBackground, "Hovered button background.");
export const buttonActiveBackground = color("button.activeBackground", "#37373d", "#dcdcdc", "Pressed button background.");
export const buttonSecondaryBackground = color("button.secondaryBackground", "#3a3d41", "#e5e5e5", "Secondary button background.");
export const primaryButtonForeground = color("button.primaryForeground", "#ffffff", "#ffffff", "Primary button foreground.");
export const primaryButtonBackground = alias("button.primaryBackground", buttonBackground, "Primary button background.");
export const primaryButtonHoverBackground = color("button.primaryHoverBackground", "#1177bb", "#006cbe", "Hovered primary button background.");
export const toolbarHoverBackground = color("toolbar.hoverBackground", "#5a5d5e50", "#5a5d5e29", "Hovered toolbar item background.");
export const keybindingLabelForeground = color("keybindingLabel.foreground", "#cccccc", "#555555", "Keybinding label foreground.");
export const keybindingLabelBackground = color("keybindingLabel.background", "#8080802b", "#dddddd66", "Keybinding label background.");
export const keybindingLabelBorder = color("keybindingLabel.border", "#80808033", "#cccccc66", "Keybinding label border.");
export const keybindingLabelBottomBorder = color("keybindingLabel.bottomBorder", "#6b6b6b", "#b0b0b0", "Keybinding label bottom border.");
export const scrollbarSliderBackground = color("scrollbar.sliderBackground", "#79797966", "#64646433", "Scrollbar slider background.");
export const scrollbarSliderHoverBackground = color("scrollbar.sliderHoverBackground", "#646464b3", "#64646459", "Hovered scrollbar slider background.");
export const scrollbarSliderActiveBackground = color("scrollbar.sliderActiveBackground", "#bfbfbf66", "#00000033", "Active scrollbar slider background.");
export const dialogBackground = color("dialog.background", "#252526", "#ffffff", "Dialog background.");
export const dialogBorder = alias("dialog.border", widgetBorder, "Dialog border.");
export const dialogBackdropBackground = color("dialog.backdropBackground", "#00000073", "#00000059", "Backdrop behind modal dialogs.");
export const dialogShadow = color("dialog.shadow", "#00000073", "#0000003d", "Shadow around modal dialogs.");
export const quickInputBackground = color("quickInput.background", "#252526", "#f8f8f8", "Quick input background.");
export const quickInputBackdropBackground = color("quickInput.backdropBackground", "#00000026", "#0000001f", "Backdrop behind quick input.");
export const textCodeBlockBackground = color("text.codeBlockBackground", "#0f0f0f", "#f2f2f2", "Inline and block code background.");
export const searchMatchBackground = color("search.matchBackground", "#f9c74f8c", "#f9c74f8c", "Highlighted search match background.");
