[package]
name = "zeta-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
name = "zeta_config"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
zeta-model-provider = { workspace = true }

[lints]
workspace = true
