[package]
name = "zeta-file-watcher"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_file_watcher"
path = "src/lib.rs"

[dependencies]
log = { workspace = true }
notify = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lints]
workspace = true
