use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Clone, Copy, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize, TS)]
pub enum AppServerErrorName {
    ParseError,
    InvalidRequest,
    MethodNotFound,
    InvalidParams,
    InternalError,
    ServerOverloaded,
    NotInitialized,
    AlreadyInitialized,
    CommandConflict,
    CoreOperationFailed,
    AgentInteractionNotOwner,
    AgentInteractionExpired,
    ResourceNotFound,
    ResourceNotOwner,
    ResourceTooLarge,
    InvalidResourceChunkSize,
    InvalidResourceOffset,
    FileSystemUnavailable,
    FileSystemOperationFailed,
    FileSystemNotFound,
    FileSystemRevisionConflict,
    GitUnavailable,
    GitNotRepository,
    GitOperationFailed,
    DiffOperationFailed,
    SyntaxAnalysisFailed,
    CodeIndexUnavailable,
    CodeIndexNotReady,
    CodeIndexOperationFailed,
    SymbolIndexUnavailable,
    SymbolIndexNotReady,
    SymbolIndexOperationFailed,
    CodeRetrievalOperationFailed,
    CloudCodeIndexUnavailable,
    CloudCodeIndexInvalidGrant,
    CloudCodeIndexConsentConflict,
    CloudCodeIndexEgressLimitExceeded,
    CloudCodeIndexProviderUnavailable,
    CloudCodeIndexOperationFailed,
    LanguageServiceUnavailable,
    LanguageRequestFailed,
    MarketplaceUnavailable,
    MarketplaceNotFound,
    MarketplaceUntrusted,
    MarketplaceIncompatible,
    MarketplaceInstallationInUse,
    MarketplaceOperationFailed,
    SearchUnavailable,
    SearchNotFound,
    SearchNotOwner,
    SearchBusy,
    TerminalUnavailable,
    TerminalNotFound,
    TerminalNotOwner,
    TerminalBusy,
    TerminalOperationFailed,
    DebugAdapterUnavailable,
    DebugAdapterNotFound,
    DebugAdapterNotOwner,
    DebugAdapterBusy,
    DebugAdapterOperationFailed,
    ConfigUnavailable,
    ConfigRevisionConflict,
    McpRuntimeUnavailable,
    McpServerNotFound,
    McpOAuthUnavailable,
    McpOAuthInvalidCallback,
    McpOAuthExpired,
    McpOAuthOperationFailed,
    AccountUnavailable,
    AccountLoginNotFound,
    AccountLoginConflict,
    AccountOperationFailed,
    ConnectorsUnavailable,
    ConnectorGenerationConflict,
    ConnectorOperationFailed,
    ConnectorOAuthUnavailable,
    ConnectorOAuthInvalidCallback,
    ConnectorOAuthExpired,
    PluginsUnavailable,
    PluginRevisionConflict,
    PluginOperationFailed,
    ToolSearchUnavailable,
    SkillsUnavailable,
    SkillOperationFailed,
    SkillNotFound,
    WorkspaceSwitchUnavailable,
    WorkspaceSwitchBusy,
    WorkspaceSwitchFailed,
    WorkspaceTrustRequired,
    ExtensionsUnavailable,
    ExtensionGenerationConflict,
    ExtensionNotFound,
    ExtensionResourceNotFound,
    ExtensionResourceInvalidPath,
    ExtensionOperationFailed,
    ExtensionHostUnavailable,
    ExtensionHostStale,
    ExtensionHostInvocationNotFound,
    ExtensionHostQuotaExceeded,
}

#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize, TS)]
pub struct AppServerError {
    #[ts(type = "number")]
    pub code: i64,
    pub message: AppServerErrorName,
    pub data: (),
}
