[package]
name = "zeta-lsp-manager"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_lsp_manager"
path = "src/lib.rs"

[dependencies]
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time"] }
url = { workspace = true }
zeta-async-utils = { workspace = true }
zeta-lsp-server-provider = { workspace = true }
zeta-lsp = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
