[package]
name = "zeta-linux-sandbox"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_linux_sandbox"
path = "src/lib.rs"

[dependencies]
zeta-bwrap = { workspace = true }
zeta-install-context = { workspace = true }
zeta-sandboxing = { workspace = true }
zeta-workspace = { workspace = true }

[lints]
workspace = true
