// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountLoginCancelStatusDto } from './AccountLoginCancelStatusDto.js';

export type AccountLoginCancelResult = { status: AccountLoginCancelStatusDto, };
