// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountStatusDto } from './AccountStatusDto.js';

export type AccountDto = { provider: string, accountId: string, email: string | null, displayName: string | null, organization: string | null, plan: string | null, status: AccountStatusDto, credentialRevision: number, };
