// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountLogoutStatusDto } from './AccountLogoutStatusDto.js';

export type AccountLogoutResult = { status: AccountLogoutStatusDto, };
