// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type AccountLoginStartResult = { "type": "connected", loginId: string, } | { "type": "browser", loginId: string, authorizationUrl: string, } | { "type": "deviceCode", loginId: string, verificationUrl: string, userCode: string, };
