// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountDto } from './AccountDto.js';

export type AccountReadResult = { revision: number, accounts: Array<AccountDto>, };
