// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentTreeNodeProjection } from './AgentTreeNodeProjection.js';

export type AgentTreeProjection = { roots: Array<AgentTreeNodeProjection>, };
