// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentMessageContent } from './AgentMessageContent.js';
import type { AgentMessageId } from './AgentMessageId.js';
import type { AgentMessageProvenance } from './AgentMessageProvenance.js';
import type { DelegationId } from './DelegationId.js';
import type { ThreadId } from './ThreadId.js';

export type AgentMessage = { messageId: AgentMessageId, delegationId?: DelegationId | null, senderThreadId: ThreadId, receiverThreadId: ThreadId, senderSequence: number, content: AgentMessageContent, provenance: AgentMessageProvenance, };
