// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContextCheckpointId } from './ContextCheckpointId.js';
import type { ItemId } from './ItemId.js';
import type { ThreadId } from './ThreadId.js';

export type AgentContextSource = { "type": "item", sourceThreadId: ThreadId, sourceSequence: number, itemId: ItemId, } | { "type": "checkpoint", sourceThreadId: ThreadId, sourceSequence: number, checkpointId: ContextCheckpointId, };
