// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ImageAttachmentRef } from './ImageAttachmentRef.js';
import type { ToolName } from './ToolName.js';

export type AgentContextContent = { "type": "userText", text: string, } | { "type": "userImage", url: string, } | { "type": "userImageAttachment", attachment: ImageAttachmentRef, } | { "type": "assistantText", text: string, } | { "type": "reasoning", text: string, } | { "type": "plan", text: string, } | { "type": "toolCall", name: ToolName, argumentsJson: string, } | { "type": "toolResult", text: string, isError: boolean, } | { "type": "checkpoint", summary: string, };
