// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { FrozenAgentDefinitionRef } from './FrozenAgentDefinitionRef.js';
import type { ModelRef } from './ModelRef.js';

export type AgentRoleSnapshot = { name: string, instructions: string, model?: ModelRef | null, definition?: FrozenAgentDefinitionRef | null, };
