// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentJoinId } from './AgentJoinId.js';
import type { AgentJoinPolicy } from './AgentJoinPolicy.js';
import type { AgentJoinStatus } from './AgentJoinStatus.js';
import type { DelegationId } from './DelegationId.js';
import type { ThreadId } from './ThreadId.js';

export type AgentJoin = { joinId: AgentJoinId, parentThreadId: ThreadId, policy: AgentJoinPolicy, delegations: Array<DelegationId>, status: AgentJoinStatus, satisfiedBy: Array<DelegationId>, };
