// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { ThreadOrigin } from './ThreadOrigin.js';

export type AgentThread = { sessionId: SessionId, threadId: ThreadId, origin: ThreadOrigin, };
