// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DelegationId } from './DelegationId.js';

export type AgentJoinPolicy = { "type": "all" } | { "type": "any" } | { "type": "quorum", count: number, } | { "type": "explicit", delegations: Array<DelegationId>, };
