// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentRoleSource } from './AgentRoleSource.js';

export type AgentRoleSelection = { "type": "default" } | { "type": "exact", source: AgentRoleSource, name: string, };
