// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ActionApprovalRequest } from './ActionApprovalRequest.js';
import type { DynamicToolCall } from './DynamicToolCall.js';
import type { RequestUserInput } from './RequestUserInput.js';

export type AgentRequest = { "type": "approval", request: ActionApprovalRequest, } | { "type": "userInput", request: RequestUserInput, } | { "type": "dynamicTool", call: DynamicToolCall, };
