// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ActionApprovalResponse } from './ActionApprovalResponse.js';
import type { DynamicToolResponse } from './DynamicToolResponse.js';
import type { RequestUserInputResponse } from './RequestUserInputResponse.js';

export type AgentResponse = { "type": "approval", response: ActionApprovalResponse, } | { "type": "userInput", response: RequestUserInputResponse, } | { "type": "dynamicTool", response: DynamicToolResponse, };
