// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentCapabilityScope } from './AgentCapabilityScope.js';
import type { AgentContextMode } from './AgentContextMode.js';
import type { AgentMaterializedContext } from './AgentMaterializedContext.js';
import type { AgentRoleSnapshot } from './AgentRoleSnapshot.js';
import type { ContextSeedDigest } from './ContextSeedDigest.js';
import type { DelegatedPolicyCeiling } from './DelegatedPolicyCeiling.js';
import type { DelegatedTask } from './DelegatedTask.js';
import type { DelegationId } from './DelegationId.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';
import type { TurnInstructions } from './TurnInstructions.js';

export type AgentContextSeed = { delegationId: DelegationId, parentThreadId: ThreadId, parentTurnId: TurnId, parentSequence: number, task: DelegatedTask, inheritance: AgentContextMode, materializedContext?: Array<AgentMaterializedContext>, policyCeiling: DelegatedPolicyCeiling, digest: ContextSeedDigest,
/**
 * None selects normal Agent behavior without a specialized role prompt.
 */
role: AgentRoleSnapshot | null, capabilityScope: AgentCapabilityScope,
/**
 * Common and model instructions. Historical seeds did not record this field.
 */
baseInstructions?: TurnInstructions | null, };
