// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentCapabilityScope } from './AgentCapabilityScope.js';
import type { AgentRoleSnapshot } from './AgentRoleSnapshot.js';
import type { TurnInstructions } from './TurnInstructions.js';

export type AgentConfiguration = {
/**
 * None selects normal Agent behavior without a specialized role prompt.
 */
role: AgentRoleSnapshot | null, capabilityScope: AgentCapabilityScope,
/**
 * Common and model instructions. Historical seeds did not record this field.
 */
baseInstructions?: TurnInstructions | null, };
