// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentContextContent } from './AgentContextContent.js';
import type { AgentContextSource } from './AgentContextSource.js';
import type { ContentDigest } from './ContentDigest.js';

export type AgentMaterializedContext = { source: AgentContextSource, content: AgentContextContent, contentDigest: ContentDigest, };
