// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentJoin } from './AgentJoin.js';
import type { AgentTreeExecutionStatus } from './AgentTreeExecutionStatus.js';
import type { AgentTreeWaitingReason } from './AgentTreeWaitingReason.js';
import type { DelegationResult } from './DelegationResult.js';
import type { FrozenAgentDefinitionRef } from './FrozenAgentDefinitionRef.js';
import type { ModelUsageSummary } from './ModelUsageSummary.js';
import type { ThreadGoal } from './ThreadGoal.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';

export type AgentTreeNodeProjection = { threadId: ThreadId, threadSequence: number, title: string, parentThreadId?: ThreadId | null, forkedFromId?: ThreadId | null, executionStatus: AgentTreeExecutionStatus, currentTurnId?: TurnId | null, waitingReason?: AgentTreeWaitingReason | null, usage: ModelUsageSummary, goal?: ThreadGoal | null, role?: FrozenAgentDefinitionRef | null, result?: DelegationResult | null, joins?: Array<AgentJoin>, children?: Array<AgentTreeNodeProjection>, };
