// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelRef } from './ModelRef.js';

export type ApprovalReviewModelSelection = { "type": "automatic" } | { "type": "explicit", model: ModelRef, };
