// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ImageDetail } from './ImageDetail.js';

export type AttachmentImportRemoteParams = { url: string, detail: ImageDetail, };
