// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AutomationDefinition } from './AutomationDefinition.js';
import type { AutomationRunStatus } from './AutomationRunStatus.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';
import type { UnixMillis } from './UnixMillis.js';

export type AutomationRun = { id: string, automationId: string, revision: number, definition: AutomationDefinition, scheduledAt: UnixMillis, createdAt: UnixMillis, startedAt: UnixMillis | null, finishedAt: UnixMillis | null, status: AutomationRunStatus, sessionId: SessionId | null, threadId: ThreadId | null, turnId: TurnId | null, message: string | null, };
