// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AutomationDefinition } from './AutomationDefinition.js';
import type { AutomationStatus } from './AutomationStatus.js';

export type AutomationWriteParams = { commandId: string, id: string, expectedRevision: number, definition: AutomationDefinition, status: AutomationStatus, };
