// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { BrowserElementTargetDto } from './BrowserElementTargetDto.js';
import type { BrowserTextInputTargetDto } from './BrowserTextInputTargetDto.js';

export type BrowserPerformActionDto = { "type": "navigate", targetId: string, url: string, } | { "type": "click", targetId: string, target: BrowserElementTargetDto, } | { "type": "typeText", targetId: string, target: BrowserTextInputTargetDto, text: string, } | { "type": "scroll", targetId: string, deltaX: number, deltaY: number, } | { "type": "goBack", targetId: string, } | { "type": "reload", targetId: string, };
