// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type BrowserObserveParams = { targetId: string, includeAccessibilityTree: boolean, includeDomSnapshot: boolean, includeScreenshot: boolean, };
