// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type CloudCodebasePreviewResult = { localGeneration: number, fileCount: number, chunkCount: number, uploadUnitCount: number, egressBytes: number, withinLimit: boolean, };
