// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseChunkSpanDto } from './CodebaseChunkSpanDto.js';

export type CodebaseRetrievalHitDto = { path: string, language: string, sourceRevision: string, contentHash: string, span: CodebaseChunkSpanDto, content: string, rrfScore: number, };
