// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseStateDto } from './CodebaseStateDto.js';

export type CodebaseStatusResult = { state: CodebaseStateDto, rootId: string, generation: number, indexedFileCount: number, indexedChunkCount: number, indexedSourceBytes: number, skippedFileCount: number, truncatedFileCount: number, fileLimitHit: boolean, sourceBytesLimitHit: boolean, };
