// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseAutomaticContextDto } from './CodebaseAutomaticContextDto.js';
import type { CodebaseModelsDto } from './CodebaseModelsDto.js';
import type { CommandId } from './CommandId.js';

export type CodebaseConfigureParams = { commandId: CommandId, expectedRevision: number, models?: CodebaseModelsDto | null, automaticContext: CodebaseAutomaticContextDto, };
