// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseRetrievalDegradationDto } from './CodebaseRetrievalDegradationDto.js';
import type { CodebaseRetrievalHitDto } from './CodebaseRetrievalHitDto.js';
import type { CodebaseStatusResult } from './CodebaseStatusResult.js';

export type CodebaseRetrievalResult = { status: CodebaseStatusResult, hits: Array<CodebaseRetrievalHitDto>, degradations: Array<CodebaseRetrievalDegradationDto>, };
