// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ConnectorCommandResultDto } from './ConnectorCommandResultDto.js';

export type ConnectorDeviceOAuthPollResult = { "status": "pending", retryAfterSeconds: number, } | { "status": "connected", command: ConnectorCommandResultDto, };
