// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ConnectorCommandDispositionDto } from './ConnectorCommandDispositionDto.js';

export type ConnectorCommandResultDto = { generation: number, disposition: ConnectorCommandDispositionDto, };
