// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ConnectorDeviceOAuthStartParams = { commandId: string, expectedGeneration: number, connectorId: string, connectionGeneration: number, };
