// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ImageAttachmentRef } from './ImageAttachmentRef.js';
import type { ImageDetail } from './ImageDetail.js';

export type ContentPart = { "type": "text", text: string, } | { "type": "imageAttachment", attachment: ImageAttachmentRef, detail: ImageDetail, } | { "type": "imageUrl", url: string, detail: ImageDetail, };
