// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type ContentSearchCancelParams = { dirId?: string, sessionDirectory?: SessionDirSelector, searchId: string, };
