// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContentSearchMatchRange } from './ContentSearchMatchRange.js';

export type ContentSearchMatch = { path: string, lineNumber: number, preview: string, ranges: Array<ContentSearchMatchRange>, };
