// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type ContentSearchReadParams = { dirId?: string, sessionDirectory?: SessionDirSelector, searchId: string, afterMatch: number, maxMatches: number, };
