// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DiffRangeDto } from './DiffRangeDto.js';
import type { DiffRowKindDto } from './DiffRowKindDto.js';

export type DiffComputeRowDto = { kind: DiffRowKindDto, originalLineIndex: number | null, modifiedLineIndex: number | null, originalChanges: Array<DiffRangeDto>, modifiedChanges: Array<DiffRangeDto>, };
