// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type DirContributionsDto = { skills: Array<string>, mcpServers: Array<string>, hooks: Array<string>, plugins: Array<string>, diagnostics: Array<string>, };
