// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { DirId } from './DirId.js';

export type DirPermissionsForgetParams = { commandId: CommandId, expectedRevision: number, dir: DirId, };
