// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DirId } from './DirId.js';
import type { PermissionDto } from './PermissionDto.js';

export type DirPermissionsEntryDto = { dir: DirId, path?: string | null, permissions: Array<PermissionDto>, };
