// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DocumentCollaborationSnapshot } from './DocumentCollaborationSnapshot.js';
import type { DocumentCollaborationUpdate } from './DocumentCollaborationUpdate.js';

export type DocumentCollaborationSubmitResult = { "status": "accepted", update: DocumentCollaborationUpdate, } | { "status": "conflict", updates: Array<DocumentCollaborationUpdate>, } | { "status": "resync", snapshot: DocumentCollaborationSnapshot, };
