// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type DocumentCollaborationSubmitParams = { roomId: string, clientId: string, sequence: number, baseVersion: number, transaction: string,
/**
 * Serialized, schema-validated document after applying `transaction` optimistically.
 */
document: string, };
