// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type DocumentCollaborationUpdate = { roomId: string, clientId: string, sequence: number, baseVersion: number, version: number,
/**
 * Serialized Document Engine transaction. The renderer validates it against its schema before use.
 */
transaction: string, };
