// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DocumentCollaborationSnapshot } from './DocumentCollaborationSnapshot.js';

export type DocumentCollaborationOpenResult = { clientId: string, schemaId: string, snapshot: DocumentCollaborationSnapshot, };
