// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ExecPolicyEffectDto = { "type": "continue" } | { "type": "allowUnsandboxed" } | { "type": "requireApproval" } | { "type": "requireSandbox" } | { "type": "deny", "reason": string };
