// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ExecPolicyActionKindDto = "localProcess" | "fileSystemMutation" | "networkRequest" | "browserInteraction" | "externalServiceMutation" | "credentialUse" | "systemOperation";
