// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostFailureDto } from './ExtensionHostFailureDto.js';
import type { ExtensionHostLifecycleDto } from './ExtensionHostLifecycleDto.js';
import type { ExtensionHostOutputEventDto } from './ExtensionHostOutputEventDto.js';
import type { ExtensionHostRegistrationDescriptorDto } from './ExtensionHostRegistrationDescriptorDto.js';

export type ExtensionHostExtensionDto = { id: string, version: string, packageDigest: string, runtimeApiVersion: number, activationGeneration: number, incarnation: number | null, lifecycle: ExtensionHostLifecycleDto, failure: ExtensionHostFailureDto | null, stderr: string, outputEvents: Array<ExtensionHostOutputEventDto>, registrations: Array<ExtensionHostRegistrationDescriptorDto>, };
