// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionItemContent } from './ExtensionItemContent.js';
import type { ExtensionItemStatus } from './ExtensionItemStatus.js';

export type ExtensionItem = { extension: string, id: string, title: string, body: string, status: ExtensionItemStatus, content: ExtensionItemContent, };
