// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostReconcileModeDto } from './ExtensionHostReconcileModeDto.js';

export type ExtensionHostReconcileParams = { mode: ExtensionHostReconcileModeDto, };
