// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionItem } from './ExtensionItem.js';

export type ExtensionItemsResult = { items: Array<ExtensionItem>, };
