// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostOutputChannelKindDto } from './ExtensionHostOutputChannelKindDto.js';
import type { ExtensionHostOutputSeverityDto } from './ExtensionHostOutputSeverityDto.js';

export type ExtensionHostOutputEventDto = { sequence: number, incarnation: number, activationGeneration: number, } & ({ "operation": "create", channelId: string, label: string, kind: ExtensionHostOutputChannelKindDto, } | { "operation": "append", channelId: string, text: string, severity: ExtensionHostOutputSeverityDto, category: string | null, } | { "operation": "replace", channelId: string, text: string, severity: ExtensionHostOutputSeverityDto, category: string | null, } | { "operation": "clear", channelId: string, } | { "operation": "show", channelId: string, preserveFocus: boolean, } | { "operation": "dispose", channelId: string, });
