// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostFailureCodeDto } from './ExtensionHostFailureCodeDto.js';

export type ExtensionHostFailureDto = { code: ExtensionHostFailureCodeDto, message: string, incarnation: number | null, };
