// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ExtensionHostLanguageProviderOperationDto = "completion" | "parameterHints" | "definition" | "hover" | "references" | "rename" | "formatting" | "codeAction" | "codeLens" | "documentSymbols" | "foldingRanges" | "documentLinks" | "documentColors" | "semanticTokens" | "inlayHints" | "linkedEditing";
