// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostLanguageProviderOperationDto } from './ExtensionHostLanguageProviderOperationDto.js';

export type ExtensionHostRegistrationDescriptorDto = { registrationId: string, } & ({ "kind": "command", command: string, title: string, } | { "kind": "languageProvider", languageIds: Array<string>, operations: Array<ExtensionHostLanguageProviderOperationDto>, } | { "kind": "debugAdapter", debuggerType: string, } | { "kind": "taskProvider", taskType: string, } | { "kind": "testProfileProvider", providerId: string, label: string, });
