// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ResourceMetadataResult } from './ResourceMetadataResult.js';

export type ExtensionResourceOpenResult = { resource: ResourceMetadataResult, };
