// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostExtensionDto } from './ExtensionHostExtensionDto.js';

export type ExtensionHostSnapshotDto = { generation: number, extensions: Array<ExtensionHostExtensionDto>, };
