// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { Feature } from './Feature.js';
import type { FeatureSource } from './FeatureSource.js';
import type { FeatureStage } from './FeatureStage.js';

export type FeatureState = { feature: Feature, stage: FeatureStage, enabled: boolean, source: FeatureSource, };
