// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ForkedAgentContext = { "type": "full" } | { "type": "lastTurns", count: number, } | { "type": "checkpointAndTail" };
