// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';
import type { SkillActivationReason } from './SkillActivationReason.js';
import type { SkillId } from './SkillId.js';

export type FrozenSkillActivation = { id: SkillId, contentDigest: ContentDigest, catalogGeneration: number, reason: SkillActivationReason, };
