// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentDefinitionSelectionReason } from './AgentDefinitionSelectionReason.js';
import type { AgentRoleSource } from './AgentRoleSource.js';
import type { ContentDigest } from './ContentDigest.js';

export type FrozenAgentDefinitionRef = { name: string, source: AgentRoleSource, version: number | null, catalogGeneration: number, contentDigest: ContentDigest, selectionReason: AgentDefinitionSelectionReason, };
