// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type FsChanged = { "type": "pathsChanged", dirId?: string, paths: Array<string>, } | { "type": "rescanRequired", dirId?: string, };
