// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { FsDeleteMode } from './FsDeleteMode.js';
import type { FsMissingTargetBehavior } from './FsMissingTargetBehavior.js';
import type { SessionDirSelector } from './SessionDirSelector.js';

export type FsDeleteParams = { dirId?: string, sessionDirectory?: SessionDirSelector, path: string, missing: FsMissingTargetBehavior, mode: FsDeleteMode, };
