// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { FsReadDirectoryEntry } from './FsReadDirectoryEntry.js';

export type FsReadDirectoryResult = { entries: Array<FsReadDirectoryEntry>, };
