// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { FsGetMetadataResult } from './FsGetMetadataResult.js';

export type FsWriteFileResult = { metadata: FsGetMetadataResult,
/**
 * Opaque exact-content revision of the successfully written file.
 */
revision: string, };
