// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitCommitSummaryDto = { objectId: string, parentObjectIds: Array<string>, timestampSeconds: number, subject: string, };
