// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitCommitFileContentDto } from './GitCommitFileContentDto.js';

export type GitCommitFileResult = { original: GitCommitFileContentDto, modified: GitCommitFileContentDto, };
