// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitChangeFileComparisonDto } from './GitChangeFileComparisonDto.js';

export type GitChangeFileParams = { repositoryId?: string, path: string, comparison: GitChangeFileComparisonDto, };
