// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitChangeStatusDto = "unmodified" | "modified" | "added" | "deleted" | "renamed" | "copied" | "typeChanged" | "unmerged" | "untracked" | "ignored";
