// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitRemoteProviderDto } from './GitRemoteProviderDto.js';

export type GitRepositoryIdentityDto = { provider: GitRemoteProviderDto, host: string, owner: string, repository: string, };
