// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitRepositoryIdentityDto } from './GitRepositoryIdentityDto.js';

export type GitRemoteDto = { name: string, identity: GitRepositoryIdentityDto | null, };
