// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type GitSubmoduleStateDto = { isSubmodule: boolean, commitChanged: boolean, trackedChanges: boolean, untrackedChanges: boolean, };
