// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { GitDiffStatisticsDto } from './GitDiffStatisticsDto.js';
import type { GitStatusResult } from './GitStatusResult.js';
import type { GitTextDiffDto } from './GitTextDiffDto.js';

export type GitTextDiffResult = { status: GitStatusResult, diffs: Array<GitTextDiffDto>, statistics: GitDiffStatisticsDto, };
