// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';
import type { ThreadId } from './ThreadId.js';

export type HistoryPrefixRef = { digest: ContentDigest, sourceThreadId: ThreadId, sourceSequence: number, };
