// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { HookEnablementDto } from './HookEnablementDto.js';

export type HookSetEnablementParams = { commandId: CommandId, expectedRevision: number, hookId: string, enablement: HookEnablementDto, };
