// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';
import type { ImageMediaType } from './ImageMediaType.js';

export type ImageAttachmentRef = { contentDigest: ContentDigest, mediaType: ImageMediaType, encodedBytes: number, width: number, height: number, };
