// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ProtocolVersion } from './ProtocolVersion.js';
import type { SchemaHash } from './SchemaHash.js';
import type { ServerCapabilities } from './ServerCapabilities.js';
import type { ServerInfo } from './ServerInfo.js';
import type { SlashCommandDefinition } from './SlashCommandDefinition.js';

export type InitializeResult = { serverInfo: ServerInfo, protocolVersion: ProtocolVersion, schemaHash: SchemaHash, capabilities: ServerCapabilities, slashCommands: Array<SlashCommandDefinition>, };
