// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ImageAttachmentRef } from './ImageAttachmentRef.js';
import type { SkillRef } from './SkillRef.js';

export type InputItem = { "type": "issue", number: number, } | { "type": "text", text: string, } | { "type": "context", name: string, content: string, } | { "type": "imageAttachment", attachment: ImageAttachmentRef, } | { "type": "image", url: string, } | { "type": "skill", skill: SkillRef, };
