// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { IssueListMode } from './IssueListMode.js';
import type { IssueState } from './IssueState.js';

export type IssueListParams = { state: IssueState, page: number, query: string, mode: IssueListMode, };
