// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { IssueConfigDto } from './IssueConfigDto.js';

export type IssueConfigureParams = { commandId: CommandId, expectedRevision: number, config: IssueConfigDto, };
