// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ItemDelta = { "type": "agentMessage", text: string, } | { "type": "reasoning", text: string, } | { "type": "plan", text: string, };
