// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type LanguageDirectorySymbolsParams = { dirId?: string, sessionDirectory?: SessionDirSelector, languageId: string, query: string, };
