// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRenamePreparationDto } from './LanguageRenamePreparationDto.js';

export type LanguagePrepareRenameResult = { preparation: LanguageRenamePreparationDto | null, };
