// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageLocationDto } from './LanguageLocationDto.js';

export type LanguageLocationsResult = { revision: number, locations: Array<LanguageLocationDto>, };
