// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCodeLensDto } from './LanguageCodeLensDto.js';

export type LanguageCodeLensesResult = { revision: number, lenses: Array<LanguageCodeLensDto>, };
