// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageInlayHintKindDto } from './LanguageInlayHintKindDto.js';
import type { LanguagePositionDto } from './LanguagePositionDto.js';

export type LanguageInlayHintDto = { position: LanguagePositionDto, label: string, kind: LanguageInlayHintKindDto, tooltip: string | null, paddingLeft: boolean, paddingRight: boolean, };
