// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCodeActionDto } from './LanguageCodeActionDto.js';

export type LanguageCodeActionsResult = { actions: Array<LanguageCodeActionDto>, };
