// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageInlayHintsParams = { document: LanguageDocumentDto, range: LanguageRangeDto, };
