// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageRenamePreparationDto = { range: LanguageRangeDto, placeholder: string, };
