// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageDocumentSymbolDto = { name: string, detail: string | null, symbolKind: number, range: LanguageRangeDto, selectionRange: LanguageRangeDto, children: Array<LanguageDocumentSymbolDto>, };
