// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDirectoryEditEntryDto } from './LanguageDirectoryEditEntryDto.js';

export type LanguageDirectoryEditDto = { entries: Array<LanguageDirectoryEditEntryDto>, };
