// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCancelStatusDto } from './LanguageCancelStatusDto.js';

export type LanguageCancelResult = { status: LanguageCancelStatusDto, };
