// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguagePositionDto } from './LanguagePositionDto.js';
import type { LanguageSignatureHelpTriggerKindDto } from './LanguageSignatureHelpTriggerKindDto.js';

export type LanguageSignatureHelpParams = { document: LanguageDocumentDto, position: LanguagePositionDto, triggerKind: LanguageSignatureHelpTriggerKindDto, triggerCharacter: string | null, };
