// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCodeActionDiagnosticDto } from './LanguageCodeActionDiagnosticDto.js';
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageCodeActionsParams = { document: LanguageDocumentDto, range: LanguageRangeDto, diagnostics: Array<LanguageCodeActionDiagnosticDto>, only: Array<string>, };
