// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageColorPresentationDto } from './LanguageColorPresentationDto.js';

export type LanguageColorPresentationsResult = { revision: number, presentations: Array<LanguageColorPresentationDto>, };
