// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageColorDto } from './LanguageColorDto.js';
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageColorPresentationsParams = { document: LanguageDocumentDto, range: LanguageRangeDto, color: LanguageColorDto, };
