// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageServerMessageSeverityDto } from './LanguageServerMessageSeverityDto.js';
import type { LanguageServerMessageSourceDto } from './LanguageServerMessageSourceDto.js';

export type LanguageServerMessageNotification = { dirId?: string, server: string, severity: LanguageServerMessageSeverityDto, source: LanguageServerMessageSourceDto, show: boolean, message: string, };
