// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageFoldingRangeDto } from './LanguageFoldingRangeDto.js';

export type LanguageFoldingRangesResult = { revision: number, ranges: Array<LanguageFoldingRangeDto>, };
