// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguagePositionDto } from './LanguagePositionDto.js';

export type LanguagePrepareRenameParams = { document: LanguageDocumentDto, position: LanguagePositionDto, };
