// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguageFormattingOptionsDto } from './LanguageFormattingOptionsDto.js';

export type LanguageDocumentFormattingParams = { document: LanguageDocumentDto, options: LanguageFormattingOptionsDto, };
