// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCompletionTriggerKindDto } from './LanguageCompletionTriggerKindDto.js';
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguagePositionDto } from './LanguagePositionDto.js';

export type LanguageCompletionsParams = { document: LanguageDocumentDto, position: LanguagePositionDto, triggerKind: LanguageCompletionTriggerKindDto, triggerCharacter: string | null, };
