// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguagePositionDto } from './LanguagePositionDto.js';

export type LanguageRangeDto = { start: LanguagePositionDto, end: LanguagePositionDto, };
