// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguageDocumentLinkDto } from './LanguageDocumentLinkDto.js';

export type LanguageResolveDocumentLinkParams = { document: LanguageDocumentDto, link: LanguageDocumentLinkDto, };
