// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageTextEditDto } from './LanguageTextEditDto.js';

export type LanguageFormattingResult = { revision: number, edits: Array<LanguageTextEditDto>, };
