// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageDocumentLinkDto = { range: LanguageRangeDto, target: string | null, tooltip: string | null, providerData: unknown, };
