// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type LanguageHierarchyKindDto = "prepareCall" | "incomingCalls" | "outgoingCalls" | "prepareType" | "supertypes" | "subtypes";
