// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageHierarchyItemDto = { name: string, symbolKind: number, detail: string | null, path: string, range: LanguageRangeDto, selectionRange: LanguageRangeDto, data: unknown, };
