// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type LanguageCompletionItemKindDto = "text" | "method" | "function" | "constructor" | "field" | "variable" | "class" | "interface" | "module" | "property" | "unit" | "value" | "enum" | "keyword" | "snippet" | "file" | "folder" | "reference" | "typeParameter";
