// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type LanguageFormattingOptionsDto = { tabSize: number, insertSpaces: boolean, trimTrailingWhitespace: boolean | null, };
