// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDirectoryDiagnosticSnapshotDto } from './LanguageDirectoryDiagnosticSnapshotDto.js';

export type LanguageDirectoryDiagnosticsResult = { supported: boolean, snapshots: Array<LanguageDirectoryDiagnosticSnapshotDto>, };
