// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCodeLensDto } from './LanguageCodeLensDto.js';
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';

export type LanguageResolveCodeLensParams = { document: LanguageDocumentDto, lens: LanguageCodeLensDto, };
