// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceInstalledPackageDto } from './MarketplaceInstalledPackageDto.js';

export type MarketplaceListInstalledResult = { instanceId: string, generation: number, packages: Array<MarketplaceInstalledPackageDto>, };
