// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceAvailableCapabilityDto } from './MarketplaceAvailableCapabilityDto.js';
import type { MarketplacePackageRefDto } from './MarketplacePackageRefDto.js';
import type { MarketplacePackageSourceDto } from './MarketplacePackageSourceDto.js';
import type { MarketplaceUpstreamReferenceDto } from './MarketplaceUpstreamReferenceDto.js';

export type MarketplacePackageDetailsDto = { package: MarketplacePackageRefDto, packageType: string, displayName: string, description: string, license: string, source: MarketplacePackageSourceDto, upstream: MarketplaceUpstreamReferenceDto | null, capabilities: Array<MarketplaceAvailableCapabilityDto>, };
