// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type MarketplacePackageSummaryDto = {
/**
 * Source-qualified plugin identity returned unchanged to lifecycle requests.
 */
id: string, version: string, packageType: string, displayName: string, description: string, };
