// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceUninstallModeDto } from './MarketplaceUninstallModeDto.js';

export type MarketplaceUninstallParams = { installationId: string, mode: MarketplaceUninstallModeDto, };
