// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceCapabilityRefDto } from './MarketplaceCapabilityRefDto.js';

export type MarketplaceConnectorActivationSpecDto = { contractVersion: string, authenticationProvider: string | null, mcp: MarketplaceCapabilityRefDto | null, };
