// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceCapabilityKindDto } from './MarketplaceCapabilityKindDto.js';
import type { MarketplaceCapabilityRefDto } from './MarketplaceCapabilityRefDto.js';

export type MarketplaceCapabilityDescriptorDto = { reference: MarketplaceCapabilityRefDto, kind: MarketplaceCapabilityKindDto, id: string, contractVersion: string, permissions: Array<string>, authenticationProvider: string | null, };
