// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceUpstreamRegistryDto } from './MarketplaceUpstreamRegistryDto.js';

export type MarketplaceUpstreamReferenceDto = { registry: MarketplaceUpstreamRegistryDto, name: string, version: string, recordUrl: string, repositoryUrl: string | null, };
