// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceResourceRefDto } from './MarketplaceResourceRefDto.js';

export type MarketplaceOpenResourceParams = { leaseId: string, resource: MarketplaceResourceRefDto, };
