// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceCapabilityKindDto } from './MarketplaceCapabilityKindDto.js';

export type MarketplaceAvailableCapabilityDto = { kind: MarketplaceCapabilityKindDto, id: string, contractVersion: string, permissions: Array<string>, authenticationProvider: string | null, };
