// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { McpSecretDto } from './McpSecretDto.js';

export type McpOAuthCompleteParams = { flowId: string, state: McpSecretDto, authorizationCode: McpSecretDto, };
