// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { McpServerConfigDto } from './McpServerConfigDto.js';

export type McpServerUpsertParams = { commandId: CommandId, expectedRevision: number, server: McpServerConfigDto, };
