// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { McpServerRuntimeStateDto } from './McpServerRuntimeStateDto.js';

export type McpServerStatusDto = { id: string, displayName: string, state: McpServerRuntimeStateDto, catalogGeneration: number, connectionGeneration: number | null, toolCount: number, };
