// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type McpTransportDto = { "type": "stdio", command: string, args: Array<string>, } | { "type": "streamableHttp", url: string, };
