// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryFinding } from './MemoryFinding.js';
import type { MemoryMetricKind } from './MemoryMetricKind.js';

export type MemoryTrend = { kind: MemoryMetricKind, finding: MemoryFinding, samples: number, spanSecs: number, growthPerSecond: number | null, };
