// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryPolicy } from './MemoryPolicy.js';

export type MemoryScopeDescriptor = { label: string, policy: MemoryPolicy, };
