// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type MemoryMetricKind = "residentBytes" | "javaScriptHeapBytes" | "domNodes" | "eventListeners" | "uiObjects" | "windows" | "cacheBytes" | "gpuEstimatedBytes" | "gpuResources" | "renderCacheEntries" | "tasks";
