// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryScopeDescriptor } from './MemoryScopeDescriptor.js';

export type MemoryScopesResult = { scopes: Array<MemoryScopeDescriptor>, };
