// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';

export type MemorySource = "user" | { "model": { sessionId: SessionId, threadId: ThreadId, turnId: TurnId, } };
