// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryCitation } from './MemoryCitation.js';
import type { MemoryId } from './MemoryId.js';
import type { MemoryScope } from './MemoryScope.js';
import type { MemorySource } from './MemorySource.js';

export type MemorySearchMatch = { source: MemorySource, citation: MemoryCitation, memoryId: MemoryId, scope: MemoryScope, revision: number, title: string, excerpt: string, updatedAtUnixMs: number, };
