// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryMutationDisposition } from './MemoryMutationDisposition.js';
import type { MemoryPolicy } from './MemoryPolicy.js';

export type MemoryPolicyMutationResult = { disposition: MemoryMutationDisposition, catalogRevision: number, policy: MemoryPolicy, };
