// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryReadMode } from './MemoryReadMode.js';
import type { MemoryScope } from './MemoryScope.js';
import type { MemoryWriteMode } from './MemoryWriteMode.js';

export type MemoryPolicy = { scope: MemoryScope, revision: number, automaticRead: MemoryReadMode, modelWrite: MemoryWriteMode, };
