// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type MemoryRole = "backend" | "tool" | "tui" | "rustGui" | "electronMain" | "renderer" | "gpu" | "utility" | "extension";
