// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { MemoryReadMode } from './MemoryReadMode.js';
import type { MemoryScope } from './MemoryScope.js';
import type { MemoryWriteMode } from './MemoryWriteMode.js';

export type MemoryPolicyUpdateParams = { commandId: CommandId, scope: MemoryScope, expectedRevision: number, automaticRead: MemoryReadMode, modelWrite: MemoryWriteMode, };
