// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryCitation } from './MemoryCitation.js';
import type { MemorySource } from './MemorySource.js';

export type MemoryCitationResult = { citation: MemoryCitation, title: string, source: MemorySource, body: string, };
