// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryProduct } from './MemoryProduct.js';
import type { MemoryStatus } from './MemoryStatus.js';
import type { MemoryTargetReport } from './MemoryTargetReport.js';

export type MemoryReport = { version: number, sessionId: string, product: MemoryProduct, status: MemoryStatus, startedAtMs: number, elapsedMs: number, sampleIntervalMs: number, targets: Array<MemoryTargetReport>, evidenceGaps: number, };
