// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemorySummary } from './MemorySummary.js';

export type MemoryListPage = { catalogRevision: number, memories: Array<MemorySummary>, nextCursor: string | null, };
