// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryScope } from './MemoryScope.js';

export type MemoryListParams = { scope: MemoryScope, cursor?: string | null, limit?: number | null, };
