// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryMetricKind } from './MemoryMetricKind.js';
import type { MemoryUnavailable } from './MemoryUnavailable.js';

export type MemoryMetric = { kind: MemoryMetricKind, value: number | null, unavailable: MemoryUnavailable | null, };
