// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { MemoryId } from './MemoryId.js';
import type { MemoryScope } from './MemoryScope.js';

export type MemoryAddParams = { commandId: CommandId, memoryId: MemoryId, scope: MemoryScope, title: string, body: string, };
