// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelContextUsageSource } from './ModelContextUsageSource.js';

export type ModelContextUsage = { usedTokens: number, source: ModelContextUsageSource, };
