// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelUsageTotal } from './ModelUsageTotal.js';

export type ModelUsageSummary = { modelInvocations: number, inputTokens: ModelUsageTotal, outputTokens: ModelUsageTotal, cachedInputTokens: ModelUsageTotal, cacheWriteInputTokens: ModelUsageTotal, reasoningTokens: ModelUsageTotal, };
