// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelMoneyAmount } from './ModelMoneyAmount.js';

export type ModelReferenceCostSummary = { knownAmounts: Array<ModelMoneyAmount>, complete: boolean, };
