// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelBillingRecord } from './ModelBillingRecord.js';
import type { ModelId } from './ModelId.js';
import type { ModelInputEstimate } from './ModelInputEstimate.js';
import type { ModelInvocationId } from './ModelInvocationId.js';
import type { ModelInvocationOutcome } from './ModelInvocationOutcome.js';
import type { ModelRef } from './ModelRef.js';
import type { ModelReferenceCostRecord } from './ModelReferenceCostRecord.js';
import type { ModelUsage } from './ModelUsage.js';
import type { ThreadId } from './ThreadId.js';
import type { TimeContext } from './TimeContext.js';
import type { TurnId } from './TurnId.js';

export type ModelInvocationRecord = {
/**
 * Exact immutable time facts included in this request; absent when disabled.
 */
timeContext?: TimeContext | null, invocationId: ModelInvocationId, threadId: ThreadId, turnId: TurnId, requestedModel?: ModelRef | null, resolvedModel?: ModelId | null, billing?: ModelBillingRecord | null, startedAtUnixMs: number, completedAtUnixMs: number, outcome: ModelInvocationOutcome, usage?: ModelUsage | null, inputEstimate?: ModelInputEstimate | null, referenceCost: ModelReferenceCostRecord, };
