// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelCatalogEntry } from './ModelCatalogEntry.js';

export type ModelListResult = { models: Array<ModelCatalogEntry>, };
