// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelReferenceCostReason } from './ModelReferenceCostReason.js';
import type { RatedModelCost } from './RatedModelCost.js';

export type ModelReferenceCostRecord = { "type": "complete", cost: RatedModelCost, } | { "type": "partial", known_minimum: RatedModelCost, reason: ModelReferenceCostReason, } | { "type": "unpriced", reason: ModelReferenceCostReason, };
