// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';
import type { InstructionText } from './InstructionText.js';
import type { ModelRef } from './ModelRef.js';

export type ModelInstructionSelection = { "type": "generic", model: ModelRef | null, } | { "type": "specialized", model: ModelRef, instructions: InstructionText, digest: ContentDigest, };
