// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { PlanStepStatus } from './PlanStepStatus.js';

export type PlanStep = { step: string, status: PlanStepStatus, };
