// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { PlanStep } from './PlanStep.js';

export type PlanUpdate = { explanation?: string | null, steps: Array<PlanStep>, };
