// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { PluginRequestEnablementDto } from './PluginRequestEnablementDto.js';

export type PluginRequestSetEnablementParams = { commandId: CommandId, expectedRevision: number, pluginId: string, enablement: PluginRequestEnablementDto, };
