// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type PluginPackageCommandParams = { commandId: string, expectedRevision: number, id: string, version: string, digest: string, };
