// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type PluginPackageDto = { id: string, version: string, digest: string, enabled: boolean, granted: boolean, effective: boolean, revoked: boolean, };
