// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { PluginCommandDispositionDto } from './PluginCommandDispositionDto.js';

export type PluginCommandResultDto = { revision: number, activationGeneration: number, disposition: PluginCommandDispositionDto, };
