// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ProjectId } from './ProjectId.js';
import type { ProjectRootDto } from './ProjectRootDto.js';
import type { ProjectStatusDto } from './ProjectStatusDto.js';
import type { SessionId } from './SessionId.js';

export type ProjectDto = { projectId: ProjectId, revision: number, status: ProjectStatusDto, name: string, description: string, roots: Array<ProjectRootDto>, sessionIds: Array<SessionId>, };
