// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ProjectCommandDispositionDto } from './ProjectCommandDispositionDto.js';
import type { ProjectDto } from './ProjectDto.js';

export type ProjectMutationResult = { disposition: ProjectCommandDispositionDto, project: ProjectDto, };
