// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ProjectSummaryDto } from './ProjectSummaryDto.js';

export type ProjectListResult = { projects: Array<ProjectSummaryDto>, };
