// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ProviderModelsListFailureCodeDto = "authentication" | "permission" | "unsupported" | "rateLimited" | "unreachable" | "providerUnavailable" | "invalidRequest" | "invalidResponse" | "invalidConfiguration" | "cancelled" | "unknown";
