// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ProviderApiKeyDto } from './ProviderApiKeyDto.js';
import type { ProviderConfigDto } from './ProviderConfigDto.js';

export type ProviderProbeParams = { config: ProviderConfigDto, apiKey: ProviderApiKeyDto | null, model: string | null, };
