// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ProviderApiKeyPolicyDto } from './ProviderApiKeyPolicyDto.js';

export type ProviderCatalogEntryDto = { provider: string, displayName: string, apiKeyPolicy: ProviderApiKeyPolicyDto, apiKeyConfigured: boolean, };
