// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CustomProviderConfigDto } from './CustomProviderConfigDto.js';
import type { ModelContextConfigDto } from './ModelContextConfigDto.js';

export type ProviderConfigDto = { provider: string, custom?: CustomProviderConfigDto | null, baseUrl?: string | null, maxOutputTokens?: number | null, modelContext?: { [key in string]: ModelContextConfigDto }, };
