// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelCatalogEntry } from './ModelCatalogEntry.js';
import type { ProviderModelsListFailureDto } from './ProviderModelsListFailureDto.js';

export type ProviderModelsListResult = { "type": "models", models: Array<ModelCatalogEntry>, } | { "type": "empty" } | { "type": "failed", failure: ProviderModelsListFailureDto, };
