// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { ProviderConfigDto } from './ProviderConfigDto.js';

export type ProviderConfigureParams = { commandId: CommandId, expectedRevision: number, config: ProviderConfigDto, };
