// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type ProviderProbeResult = { "type": "passed" } | { "type": "models", models: Array<string>, } | { "type": "failed", message: string, };
