// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';

export type ProviderRemoveParams = { commandId: CommandId, expectedRevision: number, provider: string, };
