// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { QueueInput } from './QueueInput.js';
import type { QueueStatus } from './QueueStatus.js';
import type { TurnId } from './TurnId.js';

export type QueuedMessage = { request: QueueInput, status: QueueStatus, turnId: TurnId | null, error: string | null, revision: number, };
