// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ApprovalMode } from './ApprovalMode.js';
import type { CommandId } from './CommandId.js';
import type { InputItem } from './InputItem.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { ToolMode } from './ToolMode.js';

export type QueueEnqueueParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, input: Array<InputItem>, toolMode: ToolMode, approvalMode: ApprovalMode, };
