// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelCostLineItem } from './ModelCostLineItem.js';
import type { ModelMoneyAmount } from './ModelMoneyAmount.js';

export type RatedModelCost = { amount: ModelMoneyAmount, revision: string, lineItems: Array<ModelCostLineItem>, };
