// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { UserInputAnswer } from './UserInputAnswer.js';

export type RequestUserInputResponse = { answers: { [key in string]: UserInputAnswer }, };
