// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { UserInputQuestion } from './UserInputQuestion.js';

export type RequestUserInput = { questions: Array<UserInputQuestion>, };
