// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { Thread } from './Thread.js';
import type { ThreadHistoryBoundary } from './ThreadHistoryBoundary.js';
import type { ThreadTranscriptSnapshot } from './ThreadTranscriptSnapshot.js';
import type { ThreadUpdateEnvelope } from './ThreadUpdateEnvelope.js';

export type SessionThreadSubscribeResult = { thread: Thread, transcript: ThreadTranscriptSnapshot, updates: Array<ThreadUpdateEnvelope>, history?: ThreadHistoryBoundary, };
