// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { Session } from './Session.js';
import type { ThreadId } from './ThreadId.js';

export type SessionThreadResult = { session: Session, threadId: ThreadId, };
