// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentTreeProjection } from './AgentTreeProjection.js';
import type { Session } from './Session.js';

export type SessionResult = { session: Session, agentTree: AgentTreeProjection, };
