// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirDto } from './SessionDirDto.js';
import type { SessionDirMutationDto } from './SessionDirMutationDto.js';

export type SessionDirAddResult = {
/**
 * Canonical path resolved by the server, including for an existing directory.
 */
path: string, mutation: SessionDirMutationDto, revision: number, dirs: Array<SessionDirDto>, };
