// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { SessionResult } from './SessionResult.js';
import type { SessionRewriteResult } from './SessionRewriteResult.js';
import type { SessionThreadResult } from './SessionThreadResult.js';
import type { TurnInteractionResolveResult } from './TurnInteractionResolveResult.js';
import type { TurnInterruptResult } from './TurnInterruptResult.js';
import type { TurnStartResult } from './TurnStartResult.js';
import type { TurnSteerResult } from './TurnSteerResult.js';

export type SessionRequestResult = { "type": "session", "value": SessionResult } | { "type": "deleted", "value": SessionId } | { "type": "thread", "value": SessionThreadResult } | { "type": "rewrite", "value": SessionRewriteResult } | { "type": "turn", "value": TurnStartResult } | { "type": "turnSteer", "value": TurnSteerResult } | { "type": "turnInterrupt", "value": TurnInterruptResult } | { "type": "interaction", "value": TurnInteractionResolveResult };
