// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { PermissionDto } from './PermissionDto.js';
import type { SessionId } from './SessionId.js';

export type SessionDirAddParams = { sessionId: SessionId, path: string, permissions: Array<PermissionDto>, };
