// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { Thread } from './Thread.js';
import type { ThreadHistoryBoundary } from './ThreadHistoryBoundary.js';
import type { ThreadTranscriptSnapshot } from './ThreadTranscriptSnapshot.js';

export type SessionThreadReadResult = { thread: Thread, transcript: ThreadTranscriptSnapshot,
/**
 * Present whenever the request selected bounded history.
 */
history?: ThreadHistoryBoundary, };
