// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { SessionId } from './SessionId.js';
import type { SessionRequest } from './SessionRequest.js';

export type SessionRequestParams = { commandId: CommandId, sessionId: SessionId, request: SessionRequest, };
