// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ModelUsageSummary } from './ModelUsageSummary.js';
import type { Thread } from './Thread.js';
import type { ThreadId } from './ThreadId.js';
import type { ThreadStatus } from './ThreadStatus.js';
import type { Turn } from './Turn.js';

export type SessionThread = { threadId: ThreadId, title: string, createdAtUnixMs: number,
/**
 * Sum of durations for terminal Turns that started in this Thread.
 */
completedTurnDurationMs: number,
/**
 * Start time of the current non-terminal Turn, when it has begun running.
 */
activeTurnStartedAtUnixMs?: number,
/**
 * Provider-reported token usage accumulated by this execution branch.
 */
usage: ModelUsageSummary, parentThreadId?: ThreadId | null, forkedFromId?: ThreadId | null, status: ThreadStatus, };
