// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type SessionManagerActivity = { "type": "operation", text: string, } | { "type": "question", text: string, } | { "type": "failure", text: string, };
