// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { ThreadSnapshotHistory } from './ThreadSnapshotHistory.js';

export type SessionThreadSubscribeParams = { sessionId: SessionId, threadId: ThreadId, afterSequence: number, history?: ThreadSnapshotHistory, };
