// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { SkillSourceConfigDto } from './SkillSourceConfigDto.js';

export type SkillSourceAddParams = { commandId: CommandId, expectedRevision: number, source: SkillSourceConfigDto, };
