// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SkillSourceEnablementDto } from './SkillSourceEnablementDto.js';

export type SkillSourceConfigDto = { id: string, rootReference: string, enablement: SkillSourceEnablementDto, };
