// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { StableTurnErrorCode } from './StableTurnErrorCode.js';

export type StableTurnError = { code: StableTurnErrorCode, message: string, retryable: boolean, httpStatus?: number | null, };
