// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type SymbolKindDto = "constant" | "enum" | "field" | "function" | "macro" | "method" | "module" | "static" | "struct" | "trait" | "type" | "variable";
