// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type SyntaxTokenKindDto = "attribute" | "comment" | "constant" | "constructor" | "embedded" | "function" | "keyword" | "label" | "module" | "number" | "operator" | "property" | "punctuation" | "string" | "type" | "variable";
