// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SyntaxSelectionRangeDto } from './SyntaxSelectionRangeDto.js';

export type SyntaxSelectionRangesResult = { revision: number, ranges: Array<SyntaxSelectionRangeDto>, };
