// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SyntaxLanguageDto } from './SyntaxLanguageDto.js';
import type { SyntaxRangeDto } from './SyntaxRangeDto.js';

export type SyntaxSelectionRangesParams = { language: SyntaxLanguageDto, revision: number, text: string, ranges: Array<SyntaxRangeDto>, };
