// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SyntaxRangeDto } from './SyntaxRangeDto.js';
import type { SyntaxTokenKindDto } from './SyntaxTokenKindDto.js';

export type SyntaxTokenDto = { range: SyntaxRangeDto, kind: SyntaxTokenKindDto, };
