// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { TerminalLifecycle } from './TerminalLifecycle.js';
import type { TerminalProfileSelection } from './TerminalProfileSelection.js';

export type TerminalCreateInSessionDirectoryParams = { sessionId: SessionId, path: string, rows: number, cols: number, profile: TerminalProfileSelection, lifecycle: TerminalLifecycle, };
