// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TerminalReadParams = { dirId?: string, terminalId: string, afterSequence: number, afterCommandSequence: number, maxChunks: number, };
