// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ItemDelta } from './ItemDelta.js';
import type { ItemId } from './ItemId.js';
import type { ThreadEvent } from './ThreadEvent.js';
import type { ThreadItem } from './ThreadItem.js';
import type { ToolCallId } from './ToolCallId.js';
import type { ToolOutputStream } from './ToolOutputStream.js';
import type { TurnId } from './TurnId.js';

export type ThreadUpdate = { "type": "committed", event: ThreadEvent, } | { "type": "itemStarted", turnId: TurnId, item: ThreadItem, } | { "type": "itemDelta", turnId: TurnId, itemId: ItemId, delta: ItemDelta, } | { "type": "toolOutputDelta", turnId: TurnId, toolCallId: ToolCallId, stream: ToolOutputStream, text: string, };
