// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { StreamCursor } from './StreamCursor.js';
import type { ThreadId } from './ThreadId.js';
import type { ThreadTranscriptChange } from './ThreadTranscriptChange.js';

export type ThreadTranscriptUpdateEnvelope = { sessionId: SessionId, threadId: ThreadId, durableSequence: number, revision: number, streamCursor?: StreamCursor | null, changes: Array<ThreadTranscriptChange>, };
