// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { DelegationId } from './DelegationId.js';
import type { ItemId } from './ItemId.js';
import type { MessageBoundary } from './MessageBoundary.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';
import type { WorkspaceCheckpoint } from './WorkspaceCheckpoint.js';

export type ThreadOrigin = { "type": "root" } | { "type": "replacement", sourceThreadId: ThreadId, sourceSequence: number, } | { "type": "fork", parentThreadId: ThreadId, parentSequence: number, } | { "type": "rewind", parentThreadId: ThreadId, beforeTurnId: TurnId, } | { "type": "message", parentThreadId: ThreadId, parentSequence: number, itemId: ItemId, boundary: MessageBoundary, workspace: WorkspaceCheckpoint, } | { "type": "agentSpawn", parentThreadId: ThreadId, parentSequence: number, delegationId: DelegationId, };
