// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TimeContextMode } from './TimeContextMode.js';
import type { TimeZoneOrigin } from './TimeZoneOrigin.js';
import type { UnixMillis } from './UnixMillis.js';

export type TimeContext = { sampledAtUnixMs: UnixMillis,
/**
 * Offset resolved when sampled; historical rendering does not use a newer tzdb's rules.
 */
utcOffsetSeconds: number, timeZone: string, origin: TimeZoneOrigin, mode: TimeContextMode, };
