// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ToolCallId } from './ToolCallId.js';

export type ToolCallCaller = { "type": "direct" } | { "type": "codeMode", parentToolCallId: ToolCallId, cellId: string, runtimeCallId: string, };
