// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { RequestId } from './RequestId.js';

export type ToolExecutionAuthority = { "type": "sandboxed" } | { "type": "unsandboxedGrant", grantId: string, } | { "type": "execPolicyGranted", layerId: string, ruleId: string, execPolicyRevision: string, } | { "type": "autoReviewed", assessmentId: string, } | { "type": "permissionBypassed" } | { "type": "approvedOnce", requestId: RequestId, };
