// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';

export type TurnChangesDiscardThreadParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, expectedRevision: number, confirmed: boolean, };
