// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ChangeSetId } from './ChangeSetId.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnChangeCaptureStateDto } from './TurnChangeCaptureStateDto.js';
import type { TurnChangeCommitStateDto } from './TurnChangeCommitStateDto.js';
import type { TurnChangeFileStatisticsDto } from './TurnChangeFileStatisticsDto.js';
import type { TurnChangeMessageStateDto } from './TurnChangeMessageStateDto.js';
import type { TurnChangeTerminalStateDto } from './TurnChangeTerminalStateDto.js';
import type { TurnId } from './TurnId.js';

export type TurnChangeSetSummary = { changeSetId: ChangeSetId, sessionId: SessionId, threadId: ThreadId, turnId: TurnId, repositoryId: string, targetBranch?: string, statistics: TurnChangeFileStatisticsDto, captureState: TurnChangeCaptureStateDto, messageState: TurnChangeMessageStateDto, commitState: TurnChangeCommitStateDto, terminalState?: TurnChangeTerminalStateDto, dependencies: Array<ChangeSetId>, externalDependencyPaths: Array<string>, warnings: Array<string>, conflictPaths: Array<string>, failureMessage?: string, commitId?: string, revision: number, };
