// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { ChangeSetId } from './ChangeSetId.js';
import type { CommandId } from './CommandId.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';

export type TurnChangesCommitParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, changeSetIds: Array<ChangeSetId>, expectedRevision: number, };
