// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TurnChangesReadFileResult = { path: string, binary: boolean, truncated: boolean, before?: string, after?: string, };
