// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnChangeSetSummary } from './TurnChangeSetSummary.js';

export type TurnChangesChanged = { sessionId: SessionId, threadId: ThreadId, changeSets: Array<TurnChangeSetSummary>, };
