// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TurnChangeFileKindDto } from './TurnChangeFileKindDto.js';

export type TurnChangeFileDto = { path: string, previousPath?: string, kind: TurnChangeFileKindDto, beforeMode?: string, afterMode?: string, binary: boolean, additions: number, deletions: number, };
