// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { InstructionText } from './InstructionText.js';
import type { ModelInstructionSelection } from './ModelInstructionSelection.js';

export type TurnInstructions = { owner: string, id: string, revision: string, body: string, shared?: Array<InstructionText>, modelGuidance?: ModelInstructionSelection | null, };
