// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export type TurnStatus = "created" | "running" | "waitingForApproval" | "waitingForUserInput" | "waitingForCapability" | "cancelling" | "completed" | "failed" | "interrupted";
