// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AgentRequest } from './AgentRequest.js';
import type { InteractionDeadline } from './InteractionDeadline.js';
import type { ItemId } from './ItemId.js';
import type { RequestId } from './RequestId.js';

export type TurnInteraction = { requestId: RequestId, itemId?: ItemId | null, request: AgentRequest, deadline?: InteractionDeadline | null, };
