// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { TypstDiagnosticSeverityDto } from './TypstDiagnosticSeverityDto.js';
import type { TypstSourceRangeDto } from './TypstSourceRangeDto.js';

export type TypstDiagnosticDto = { severity: TypstDiagnosticSeverityDto, message: string, hints: Array<string>, range: TypstSourceRangeDto | null, };
