[package]
name = "zeta-terminal-workspace"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_terminal_workspace"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
unicode-width = { workspace = true }
zeta-app-server-client = { workspace = true }
zeta-app-server-protocol = { workspace = true }
zeta-protocol = { workspace = true }
zeta-remote-connections = { workspace = true }
zeta-terminal = { workspace = true }
zeta-ui-components = { workspace = true }
zeta-ui-theme = { workspace = true }
zeta-utils-pty = { workspace = true }
zui = { workspace = true, features = ["native"] }

[lints]
workspace = true
