[package]
name = "ash-shell-command"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_shell_command"
path = "src/lib.rs"

[dependencies]
network-proxy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ash-async-utils = { workspace = true }
ash-tool-executor = { workspace = true }
ash-sandboxing = { workspace = true }
ash-file-access = { workspace = true }
ash-tools = { workspace = true }

[dev-dependencies]
mxc-sandbox = { workspace = true }
ash-install-context = { workspace = true }
ash-protocol = { workspace = true }

[lints]
workspace = true
