// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { BrowserCloseParams } from './types/BrowserCloseParams.js';
import type { BrowserCreateParams } from './types/BrowserCreateParams.js';
import type { BrowserCreateResult } from './types/BrowserCreateResult.js';
import type { BrowserObserveParams } from './types/BrowserObserveParams.js';
import type { BrowserObserveResult } from './types/BrowserObserveResult.js';
import type { BrowserPerformParams } from './types/BrowserPerformParams.js';
import type { BrowserPerformResult } from './types/BrowserPerformResult.js';
import type { JsonRpcError, JsonRpcRequest, JsonRpcResponse } from './protocol.js';

export interface AppServerServerRequestMap {
  "browser/create": { params: BrowserCreateParams; response: BrowserCreateResult };
  "browser/observe": { params: BrowserObserveParams; response: BrowserObserveResult };
  "browser/perform": { params: BrowserPerformParams; response: BrowserPerformResult };
  "browser/close": { params: BrowserCloseParams; response: null };
}
export type AppServerServerRequestMethod = keyof AppServerServerRequestMap;
export type ServerRequestParams<M extends AppServerServerRequestMethod> = AppServerServerRequestMap[M]["params"];
export type ServerRequestResult<M extends AppServerServerRequestMethod> = AppServerServerRequestMap[M]["response"];
export type AppServerServerRequest<M extends AppServerServerRequestMethod> = JsonRpcRequest<ServerRequestParams<M>> & { method: M };
export type AppServerServerResponse<M extends AppServerServerRequestMethod> = JsonRpcResponse<ServerRequestResult<M>, JsonRpcError>;
export type AppServerServerRequestDefinition<M extends AppServerServerRequestMethod> = {
readonly method: M;
readonly __params?: ServerRequestParams<M>;
readonly __result?: ServerRequestResult<M>;
};
export const APP_SERVER_SERVER_REQUESTS: { [M in AppServerServerRequestMethod]: AppServerServerRequestDefinition<M> } = {
  "browser/create": { method: "browser/create" },
  "browser/observe": { method: "browser/observe" },
  "browser/perform": { method: "browser/perform" },
  "browser/close": { method: "browser/close" },
};
