// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
import type { AccountLoginCompleted } from './types/AccountLoginCompleted.js';
import type { AccountUpdated } from './types/AccountUpdated.js';
import type { AgentRequestEnvelope } from './types/AgentRequestEnvelope.js';
import type { ConfigChanged } from './types/ConfigChanged.js';
import type { ConnectorsChanged } from './types/ConnectorsChanged.js';
import type { DocumentCollaborationPresenceSnapshot } from './types/DocumentCollaborationPresenceSnapshot.js';
import type { DocumentCollaborationUpdate } from './types/DocumentCollaborationUpdate.js';
import type { ExtensionHostChanged } from './types/ExtensionHostChanged.js';
import type { FsChanged } from './types/FsChanged.js';
import type { GitStatusChanged } from './types/GitStatusChanged.js';
import type { LanguageDiagnosticsNotification } from './types/LanguageDiagnosticsNotification.js';
import type { LanguageServerMessageNotification } from './types/LanguageServerMessageNotification.js';
import type { LanguageServerProgressNotification } from './types/LanguageServerProgressNotification.js';
import type { LanguageServerStateNotification } from './types/LanguageServerStateNotification.js';
import type { MarketplaceChanged } from './types/MarketplaceChanged.js';
import type { MemoryChanged } from './types/MemoryChanged.js';
import type { PluginsChanged } from './types/PluginsChanged.js';
import type { ProjectChanged } from './types/ProjectChanged.js';
import type { SessionChanged } from './types/SessionChanged.js';
import type { SessionDeleted } from './types/SessionDeleted.js';
import type { SkillsChanged } from './types/SkillsChanged.js';
import type { ThreadGoalClearedNotification } from './types/ThreadGoalClearedNotification.js';
import type { ThreadGoalUpdatedNotification } from './types/ThreadGoalUpdatedNotification.js';
import type { ThreadTranscriptUpdateEnvelope } from './types/ThreadTranscriptUpdateEnvelope.js';
import type { ThreadUpdateEnvelope } from './types/ThreadUpdateEnvelope.js';
import type { TurnChangesChanged } from './types/TurnChangesChanged.js';
import type { JsonRpcVersion } from './protocol.js';

export interface AppServerNotificationMap {
  "account/login/completed": AccountLoginCompleted;
  "account/updated": AccountUpdated;
  "agent/request": AgentRequestEnvelope;
  "session/changed": SessionChanged;
  "session/deleted": SessionDeleted;
  "document/collaboration/update": DocumentCollaborationUpdate;
  "document/collaboration/presence": DocumentCollaborationPresenceSnapshot;
  "session/thread/update": ThreadUpdateEnvelope;
  "session/thread/transcript/update": ThreadTranscriptUpdateEnvelope;
  "thread/goal/updated": ThreadGoalUpdatedNotification;
  "thread/goal/cleared": ThreadGoalClearedNotification;
  "config/changed": ConfigChanged;
  "connector/changed": ConnectorsChanged;
  "plugin/changed": PluginsChanged;
  "marketplace/changed": MarketplaceChanged;
  "skills/changed": SkillsChanged;
  "extensionHost/changed": ExtensionHostChanged;
  "git/statusChanged": GitStatusChanged;
  "turnChanges/changed": TurnChangesChanged;
  "project/changed": ProjectChanged;
  "memory/changed": MemoryChanged;
  "queue/changed": Record<string, never>;
  "automation/changed": Record<string, never>;
  "fs/changed": FsChanged;
  "language/diagnostics": LanguageDiagnosticsNotification;
  "language/serverMessage": LanguageServerMessageNotification;
  "language/serverProgress": LanguageServerProgressNotification;
  "language/serverState": LanguageServerStateNotification;
}
export type AppServerNotificationMethod = keyof AppServerNotificationMap;
export type NotificationParams<M extends AppServerNotificationMethod> = AppServerNotificationMap[M];
export type ServerNotification = {
[M in AppServerNotificationMethod]: { method: M; params: NotificationParams<M> }
}[AppServerNotificationMethod];
export type AppServerWireNotification = {
[M in AppServerNotificationMethod]: { jsonrpc: JsonRpcVersion; method: M; params: NotificationParams<M> }
}[AppServerNotificationMethod];
export type AppServerNotificationDefinition<M extends AppServerNotificationMethod> = {
readonly method: M;
readonly __params?: NotificationParams<M>;
};
export const APP_SERVER_NOTIFICATIONS: {
[M in AppServerNotificationMethod]: AppServerNotificationDefinition<M>
} = {
  "account/login/completed": { method: "account/login/completed" },
  "account/updated": { method: "account/updated" },
  "agent/request": { method: "agent/request" },
  "session/changed": { method: "session/changed" },
  "session/deleted": { method: "session/deleted" },
  "document/collaboration/update": { method: "document/collaboration/update" },
  "document/collaboration/presence": { method: "document/collaboration/presence" },
  "session/thread/update": { method: "session/thread/update" },
  "session/thread/transcript/update": { method: "session/thread/transcript/update" },
  "thread/goal/updated": { method: "thread/goal/updated" },
  "thread/goal/cleared": { method: "thread/goal/cleared" },
  "config/changed": { method: "config/changed" },
  "connector/changed": { method: "connector/changed" },
  "plugin/changed": { method: "plugin/changed" },
  "marketplace/changed": { method: "marketplace/changed" },
  "skills/changed": { method: "skills/changed" },
  "extensionHost/changed": { method: "extensionHost/changed" },
  "git/statusChanged": { method: "git/statusChanged" },
  "turnChanges/changed": { method: "turnChanges/changed" },
  "project/changed": { method: "project/changed" },
  "memory/changed": { method: "memory/changed" },
  "queue/changed": { method: "queue/changed" },
  "automation/changed": { method: "automation/changed" },
  "fs/changed": { method: "fs/changed" },
  "language/diagnostics": { method: "language/diagnostics" },
  "language/serverMessage": { method: "language/serverMessage" },
  "language/serverProgress": { method: "language/serverProgress" },
  "language/serverState": { method: "language/serverState" },
};
