// Generated by `ash-app-server-protocol generate_protocol`. Do not edit.
export const APP_SERVER_PROTOCOL_MAJOR = 4 as const;
export const APP_SERVER_PROTOCOL_REVISION = 1 as const;
export const APP_SERVER_CAPABILITY_VERSION = 4 as const;
export const APP_SERVER_SCHEMA_HASH = "sha256:d4d5ab5d02c8c0a99d5240f934f0d65e4ce662f82436a3f874bee8dbc666eb3c" as const;
export type JsonRpcVersion = "2.0";
export type JsonRpcId = number | string | null;
export type JsonRpcRequest<P> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P };
export type JsonRpcNotification<P> = { jsonrpc: JsonRpcVersion; method: string; params: P };
export type JsonRpcSuccess<R> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R };
export type JsonRpcFailure<E> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E };
export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;
export type JsonRpcError = { code: number; message: string; data: unknown };
