[package]
name = "zeta-ui-theme"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_ui_theme"
path = "src/lib.rs"

[dependencies]
zeta-icons = { workspace = true }
zeta-theme = { workspace = true }
zeta-ui-components = { workspace = true }
zui = { workspace = true, default-features = false }

[lints]
workspace = true
