[package]
name = "zeta-text-search"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_text_search"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
zeta-async-utils = { workspace = true }
zeta-sandboxing = { workspace = true }
zeta-tools = { workspace = true }

[dev-dependencies]
zeta-protocol = { workspace = true }

[lints]
workspace = true
