//! Rust source generation for embedded terminal sprites.

use crate::OwnedTerminalSprite;
use crate::Rgb;
use std::fmt::Write;

/// Emits a static `TerminalSprite` value for inclusion by the consuming product.
pub fn terminal_sprite_rust_source(name: &str, sprite: &OwnedTerminalSprite) -> String {
    let sprite = sprite.as_sprite();
    let mut output = String::from(
        "// @generated by zeta-sprite. Regenerate from the design source; do not hand-edit.\n\n",
    );
    output.push_str("use zeta_sprite::Rgb;\n");
    output.push_str("use zeta_sprite::SpriteCell;\n");
    output.push_str("use zeta_sprite::TerminalSprite;\n\n");
    writeln!(
        output,
        "pub(super) static {name}: TerminalSprite<'static> = TerminalSprite::new("
    )
    .expect("write to String");
    writeln!(output, "    {},", sprite.width()).expect("write to String");
    writeln!(output, "    {},", sprite.height()).expect("write to String");
    output.push_str("    &[\n");
    for cell in sprite.cells().iter().copied() {
        if cell.background().is_some() {
            output.push_str("        SpriteCell::new(\n");
            writeln!(output, "            {:?},", cell.symbol()).expect("write to String");
            writeln!(output, "            {},", rust_color(cell.foreground()))
                .expect("write to String");
            writeln!(output, "            {},", rust_color(cell.background()))
                .expect("write to String");
            output.push_str("        ),\n");
        } else {
            writeln!(
                output,
                "        SpriteCell::new({:?}, {}, {}),",
                cell.symbol(),
                rust_color(cell.foreground()),
                rust_color(cell.background())
            )
            .expect("write to String");
        }
    }
    output.push_str("    ],\n);\n");
    output
}

fn rust_color(color: Option<Rgb>) -> String {
    let Some(color) = color else {
        return "None".into();
    };
    let [red, green, blue] = color.components();
    format!("Some(Rgb::new(0x{red:02x}, 0x{green:02x}, 0x{blue:02x}))")
}

#[cfg(test)]
#[path = "rust_source_tests.rs"]
mod tests;
