//! Rust source generation for embedded terminal sprites.

#[cfg(feature = "sheet")]
use crate::CompiledSpriteSheet;
use crate::OwnedTerminalSprite;
use crate::Rgb;
use std::fmt::Write;

/// Emits a static `TerminalSprite` value for inclusion by the consuming product.
pub fn terminal_sprite_rust_source(name: &str, sprite: &OwnedTerminalSprite) -> String {
    let mut output = String::from(
        "// @generated by zeta-sprite. Regenerate from the design source; do not hand-edit.\n\n",
    );
    output.push_str("use zeta_sprite::Rgb;\n");
    output.push_str("use zeta_sprite::SpriteCell;\n");
    output.push_str("use zeta_sprite::TerminalSprite;\n\n");
    writeln!(
        output,
        "pub(super) static {name}: TerminalSprite<'static> ="
    )
    .expect("write to String");
    write_sprite(&mut output, sprite, "    ");
    output.push_str(";\n");
    output
}

/// Emits a static named sprite sheet for inclusion by the consuming product.
#[cfg(feature = "sheet")]
pub fn terminal_sprite_sheet_rust_source(name: &str, sheet: &CompiledSpriteSheet) -> String {
    let mut output = String::from(
        "// @generated by zeta-sprite. Regenerate from the design source; do not hand-edit.\n\n",
    );
    output.push_str("use zeta_sprite::Rgb;\n");
    output.push_str("use zeta_sprite::SpriteCell;\n");
    output.push_str("use zeta_sprite::TerminalSprite;\n");
    output.push_str("use zeta_sprite::TerminalSpriteAction;\n");
    output.push_str("use zeta_sprite::TerminalSpriteActionStep;\n");
    output.push_str("use zeta_sprite::TerminalSpriteFrame;\n");
    output.push_str("use zeta_sprite::TerminalSpriteSheet;\n\n");

    for frame in sheet.frames() {
        let frame_name = rust_identifier(name, frame.name());
        writeln!(output, "static {frame_name}_CELLS: &[SpriteCell] = &[").expect("write to String");
        write_cells(&mut output, frame.sprite().as_sprite(), "    ");
        output.push_str("];\n\n");
    }

    writeln!(
        output,
        "static {name}_FRAMES: &[TerminalSpriteFrame<'static>] = &["
    )
    .expect("write to String");
    for frame in sheet.frames() {
        let frame_name = rust_identifier(name, frame.name());
        let sprite = frame.sprite().as_sprite();
        writeln!(
            output,
            "    TerminalSpriteFrame::new({:?}, TerminalSprite::new({}, {}, {frame_name}_CELLS)),",
            frame.name(),
            sprite.width(),
            sprite.height()
        )
        .expect("write to String");
    }
    output.push_str("];\n\n");

    for action in sheet.actions() {
        let action_name = rust_identifier(name, action.name());
        writeln!(
            output,
            "static {action_name}_STEPS: &[TerminalSpriteActionStep] = &["
        )
        .expect("write to String");
        for step in action.steps() {
            writeln!(
                output,
                "    TerminalSpriteActionStep::new({}, {}),",
                step.frame_index(),
                step.duration_ms()
            )
            .expect("write to String");
        }
        output.push_str("];\n\n");
    }

    writeln!(
        output,
        "static {name}_ACTIONS: &[TerminalSpriteAction<'static>] = &["
    )
    .expect("write to String");
    for action in sheet.actions() {
        let action_name = rust_identifier(name, action.name());
        writeln!(
            output,
            "    TerminalSpriteAction::new({:?}, {action_name}_STEPS),",
            action.name()
        )
        .expect("write to String");
    }
    output.push_str("];\n\n");
    writeln!(
        output,
        "pub(super) static {name}: TerminalSpriteSheet<'static> = TerminalSpriteSheet::new("
    )
    .expect("write to String");
    writeln!(output, "    {name}_FRAMES,").expect("write to String");
    writeln!(output, "    {name}_ACTIONS,").expect("write to String");
    writeln!(output, "    {},", sheet.idle_frame_index()).expect("write to String");
    output.push_str(");\n");
    output
}

fn write_sprite(output: &mut String, sprite: &OwnedTerminalSprite, indent: &str) {
    let sprite = sprite.as_sprite();
    writeln!(output, "{indent}TerminalSprite::new(").expect("write to String");
    writeln!(output, "{indent}    {},", sprite.width()).expect("write to String");
    writeln!(output, "{indent}    {},", sprite.height()).expect("write to String");
    writeln!(output, "{indent}    &[").expect("write to String");
    write_cells(output, sprite, &format!("{indent}        "));
    writeln!(output, "{indent}    ],").expect("write to String");
    write!(output, "{indent})").expect("write to String");
}

fn write_cells(output: &mut String, sprite: crate::TerminalSprite<'_>, indent: &str) {
    for cell in sprite.cells().iter().copied() {
        if cell.background().is_some() {
            writeln!(output, "{indent}SpriteCell::new(").expect("write to String");
            writeln!(output, "{indent}    {:?},", cell.symbol()).expect("write to String");
            writeln!(output, "{indent}    {},", rust_color(cell.foreground()))
                .expect("write to String");
            writeln!(output, "{indent}    {},", rust_color(cell.background()))
                .expect("write to String");
            writeln!(output, "{indent}),").expect("write to String");
        } else {
            writeln!(
                output,
                "{indent}SpriteCell::new({:?}, {}, {}),",
                cell.symbol(),
                rust_color(cell.foreground()),
                rust_color(cell.background())
            )
            .expect("write to String");
        }
    }
}

#[cfg(feature = "sheet")]
fn rust_identifier(prefix: &str, name: &str) -> String {
    format!("{prefix}_{}", name.replace('-', "_").to_ascii_uppercase())
}

fn rust_color(color: Option<Rgb>) -> String {
    let Some(color) = color else {
        return "None".into();
    };
    let [red, green, blue] = color.components();
    format!("Some(Rgb::new(0x{red:02x}, 0x{green:02x}, 0x{blue:02x}))")
}

#[cfg(test)]
#[path = "rust_source_tests.rs"]
mod tests;
