[package]
name = "zeta-server-host"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[[bin]]
name = "zeta-server"
path = "src/main.rs"

[lib]
doctest = false
name = "zeta_server_host"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
zeta-app-server = { workspace = true }
zeta-app-server-client = { workspace = true }
zeta-app-server-protocol = { workspace = true }
zeta-remote = { workspace = true }
zeta-remote-connections = { workspace = true }
zeta-remote-server = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
