[package]
name = "zeta-editor"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_editor"
path = "src/lib.rs"

[dependencies]
unicode-segmentation = { workspace = true }
unicode-width = { workspace = true }
zeta-diff = { workspace = true }
zeta-syntax = { workspace = true }
zeta-ui = { workspace = true }

[lints]
workspace = true
