[package]
name = "zeta-goal"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
action-policy = { package = "zeta-action-policy", path = "../../action-policy" }
async-utils = { package = "zeta-async-utils", path = "../../async-utils" }
zeta-core = { workspace = true }
extension-api = { package = "zeta-extension-api", path = "../extension-api" }
prompts = { package = "zeta-prompts", path = "../../prompts" }
protocol = { package = "zeta-protocol", path = "../../protocol" }
utils-template = { package = "zeta-utils-template", path = "../../utils/template" }

[lints]
workspace = true
