load("//zeterm:defs.bzl", "zeterm_rust_binary")

zeterm_rust_binary(
    name = "zui_demo",
    crate_name = "zui_demo",
    crate_root = "src/main.rs",
    package_name = "zeterm/zui-demo",
)

filegroup(
    name = "zui_demo_sources",
    srcs = glob([
        "src/**/*.rs",
        "Cargo.toml",
    ]),
    visibility = ["//visibility:public"],
)
