load("//:defs.bzl", "ash_rust_crate")

ash_rust_crate(
    name = "keybinding",
    crate_name = "ash_keybinding",
    data = ["//resources/keybindings:conformance.json"],
)

filegroup(
    name = "keybinding_sources",
    srcs = glob([
        "src/**/*.rs",
        "Cargo.toml",
    ]),
    visibility = ["//visibility:public"],
)
