[package]
name = "zeterm-keybinding-ui"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeterm_keybinding_ui"

[dependencies]
zeta-keybinding = { workspace = true }
zeta-ui = { workspace = true }
zui = { workspace = true }

[lints]
workspace = true
