[package]
name = "zeta-tui"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_tui"
path = "src/lib.rs"

[dependencies]
base64 = { workspace = true }
crossterm = { workspace = true }
dirs = { workspace = true }
ratatui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
unicode-width = { workspace = true }
zeta-ansi-escape = { workspace = true }
zeta-app-server-client = { workspace = true }
zeta-app-server-protocol = { workspace = true }
zeta-file-search = { workspace = true }
zeta-keybinding = { workspace = true }
zeta-diff = { workspace = true }
zeta-protocol = { workspace = true }
zeta-slash-commands = { workspace = true }
zeta-terminal-detection = { workspace = true }
zeta-theme = { workspace = true }
zeta-utils-path = { workspace = true }
zeta-utils-image = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs", "process", "stdio"] }
signal-hook = { workspace = true }

[target.'cfg(not(target_os = "android"))'.dependencies]
arboard = { workspace = true }
image = { workspace = true, features = ["gif", "jpeg", "png", "webp"] }

[dev-dependencies]
tempfile = { workspace = true }
zeta-client = { workspace = true }

[lints]
workspace = true
