[package]
name = "ash-extension-api"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_extension_api"
path = "src/lib.rs"

[dependencies]
ash-action-policy = { workspace = true }
async-utils = { package = "ash-async-utils", path = "../../async-utils" }
extension-items = { workspace = true }
ash-protocol = { workspace = true }
ash-tools = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
