[package]
name = "ash-hooks"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_hooks"
path = "src/lib.rs"

[dependencies]
ash-install-context = { workspace = true }
mxc-sandbox = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ash-action-policy = { workspace = true }
ash-async-utils = { workspace = true }
ash-config = { workspace = true }
ash-core = { workspace = true }
ash-protocol = { workspace = true }
ash-sandboxing = { workspace = true }
ash-tool-executor = { workspace = true }
ash-file-access = { workspace = true }

[lints]
workspace = true
