[package]
name = "zeta-input-classifier"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_input_classifier"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
candle-core = { workspace = true }
candle-nn = { workspace = true }
candle-onnx = { workspace = true }
difflib = { workspace = true }
prost = { workspace = true }
rust-stemmers = { workspace = true }
tokenizers = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
