load("//:defs.bzl", "ash_rust_binary", "ash_rust_crate")

ash_rust_crate(
    name = "windows-sandbox",
    crate_name = "windows_sandbox",
)

ash_rust_binary(
    name = "ash-windows-sandbox",
    crate_name = "ash_windows_sandbox",
    crate_root = "src/main.rs",
    deps = [":windows-sandbox"],
)
