// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AccountLoginFailureDto } from './AccountLoginFailureDto.js';

export type AccountLoginCompletionStatusDto = { "type": "succeeded" } | { "type": "failed", failure: AccountLoginFailureDto, };
