// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type AccountLoginMethodDto = { "type": "openAiChatGptBrowser" } | { "type": "openAiChatGptDeviceCode" } | { "type": "kimiDeviceCode" };
