// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AccountLoginMethodDto } from './AccountLoginMethodDto.js';

export type AccountLoginStartParams = { method: AccountLoginMethodDto, };
