// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AccountLoginCompletionStatusDto } from './AccountLoginCompletionStatusDto.js';
import type { AccountReadResult } from './AccountReadResult.js';

export type AccountLoginCompleted = { loginId: string, status: AccountLoginCompletionStatusDto, account: AccountReadResult, };
