// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ActionApprovalCapability } from './ActionApprovalCapability.js';
import type { SandboxDenialOutput } from './SandboxDenialOutput.js';

export type ActionApprovalRequest = { actionDigest: string, policyRevision: string, capabilities: Array<ActionApprovalCapability>, reason: string, sandboxDenial?: SandboxDenialOutput | null, };
