// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type ActionApprovalCapabilityKind = "fileRead" | "fileWrite" | "processSpawn" | "network" | "credentialUse" | "externalMutation" | "systemConfiguration" | "userInterface";
