// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentInteractionKind } from './AgentInteractionKind.js';
import type { ToolName } from './ToolName.js';

export type AgentInteractionCapability = { version: number, kinds: Array<AgentInteractionKind>,
/**
 * Exact client-hosted dynamic tool names this connection can execute.
 *
 * This is ephemeral routing authority, not an executable registration. App Server still
 * accepts and validates definitions through its composition root.
 */
dynamicTools?: Array<ToolName>, };
