// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { AgentThread } from './AgentThread.js';

export type AgentReadResult = { agentId: AgentId, createdAtUnixMs: number, threads: Array<AgentThread>, };
