// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentContextSource } from './AgentContextSource.js';
import type { ForkedAgentContext } from './ForkedAgentContext.js';

export type AgentContextMode = { "type": "fresh" } | { "type": "selected", sources: Array<AgentContextSource>, } | { "type": "forkedPrefix", selection: ForkedAgentContext, };
