// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';
import type { TurnInteraction } from './TurnInteraction.js';

export type AgentRequestEnvelope = { sessionId: SessionId, threadId: ThreadId, turnId: TurnId, interaction: TurnInteraction, };
