// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { DelegationResult } from './DelegationResult.js';

export type AgentMessageContent = { "type": "instruction", text: string, } | { "type": "result", result: DelegationResult, };
