// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AppServerErrorData } from './AppServerErrorData.js';

export type AppServerError = { code: number, message: string, data: AppServerErrorData, };
