// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ImageAttachmentRef } from './ImageAttachmentRef.js';

export type AttachmentMaterializeResult = { attachment: ImageAttachmentRef, };
