// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ImageDetail } from './ImageDetail.js';
import type { ImageMediaType } from './ImageMediaType.js';

export type AttachmentUploadStartParams = { mediaType: ImageMediaType, encodedBytes: number, detail: ImageDetail, };
