// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type AutomationRunStatus = "pending" | "running" | "needsInput" | "stopping" | "completed" | "failed" | "stopped" | "skipped";
