// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AutomationRun } from './AutomationRun.js';

export type AutomationRunsResult = { runs: Array<AutomationRun>, };
