// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AutomationDefinition } from './AutomationDefinition.js';
import type { AutomationStatus } from './AutomationStatus.js';
import type { UnixMillis } from './UnixMillis.js';

export type Automation = { id: string, revision: number, definition: AutomationDefinition, status: AutomationStatus, createdAt: UnixMillis, updatedAt: UnixMillis, nextRunAt: UnixMillis | null, };
