// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { UnixMillis } from './UnixMillis.js';

export type AutomationSchedule = { "type": "once", at: UnixMillis, } | { "type": "interval", anchor: UnixMillis, minutes: number, } | { "type": "weekly", timezone: string,
/**
 * ISO weekdays: Monday is 1, Sunday is 7. All seven days means daily.
 */
weekdays: Array<number>, hour: number, minute: number, };
