// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { BrowserBinaryPayload } from './BrowserBinaryPayload.js';

export type BrowserObserveResult = { targetId: string, url: string, title: string, loading: boolean, accessibilityTree?: string, domSnapshot?: string, screenshot?: BrowserBinaryPayload, };
