// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { BrowserElementTargetDto } from './BrowserElementTargetDto.js';

export type BrowserTextInputTargetDto = { "type": "element", target: BrowserElementTargetDto, } | { "type": "focusedElement" };
