// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentInteractionCapability } from './AgentInteractionCapability.js';
import type { BrowserCapability } from './BrowserCapability.js';
import type { DirPermissionsHostCapability } from './DirPermissionsHostCapability.js';

export type ClientCapabilities = { notifications?: boolean, agentInteractions?: AgentInteractionCapability | null, browser?: BrowserCapability | null, dirPermissionsHost?: DirPermissionsHostCapability | null, };
