// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CloudCodebaseGrantDto } from './CloudCodebaseGrantDto.js';
import type { CloudCodebaseStateDto } from './CloudCodebaseStateDto.js';
import type { CodebaseDeploymentModeDto } from './CodebaseDeploymentModeDto.js';

export type CloudCodebaseStatusResult = { deploymentMode: CodebaseDeploymentModeDto, state: CloudCodebaseStateDto, rootId: string, grant: CloudCodebaseGrantDto | null, localGeneration: number, syncedLocalGeneration: number | null, remoteGeneration: string | null, };
