// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CloudCodebaseSelectionDto } from './CloudCodebaseSelectionDto.js';

export type CloudCodebasePreviewParams = { selection: CloudCodebaseSelectionDto, maxEgressBytes: number, };
