// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CloudCodebaseGrantDto } from './CloudCodebaseGrantDto.js';

export type CloudCodebaseAuthorizeParams = { grant: CloudCodebaseGrantDto, };
