// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CloudCodebaseDestinationDto } from './CloudCodebaseDestinationDto.js';
import type { CloudCodebaseSelectionDto } from './CloudCodebaseSelectionDto.js';

export type CloudCodebaseGrantDto = { grantId: string, codebaseId: string, destination: CloudCodebaseDestinationDto, selection: CloudCodebaseSelectionDto, maxEgressBytes: number, };
