// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ModelRef } from './ModelRef.js';

export type CodebaseModelsDto = { embeddingModel: ModelRef, rerankModel?: ModelRef | null, };
