// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseAutomaticContextDto } from './CodebaseAutomaticContextDto.js';
import type { CodebaseModelsDto } from './CodebaseModelsDto.js';

export type CodebaseConfigDto = { models?: CodebaseModelsDto | null, automaticContext: CodebaseAutomaticContextDto, };
