// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseChunkSpanDto } from './CodebaseChunkSpanDto.js';

export type CodebaseSearchHitDto = { path: string, language: string, sourceRevision: string, chunkKey: string, contentHash: string, span: CodebaseChunkSpanDto, content: string, score: number, };
