// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseSearchHitDto } from './CodebaseSearchHitDto.js';
import type { CodebaseStatusResult } from './CodebaseStatusResult.js';

export type CodebaseSearchResult = { status: CodebaseStatusResult, hits: Array<CodebaseSearchHitDto>, };
