// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';
import type { SymbolKindDto } from './SymbolKindDto.js';

export type CodebaseSymbolsSearchHitDto = { name: string, kind: SymbolKindDto, containerName: string | null, path: string, language: string, sourceRevision: string, declarationRange: LanguageRangeDto, selectionRange: LanguageRangeDto, score: number,
/**
 * Zero-based UTF-16 offsets into `name` suitable for Renderer highlighting.
 */
matchedIndices: Array<number>, };
