// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseSymbolsStateDto } from './CodebaseSymbolsStateDto.js';

export type CodebaseSymbolsStatusResult = { state: CodebaseSymbolsStateDto, rootId: string, generation: number, sourceGeneration: number, indexedSourceCount: number, indexedSymbolCount: number, symbolLimitHit: boolean, };
