// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type CodebaseRetrievalDegradationDto = { "type": "codebaseIncomplete" } | { "type": "cloudCodebaseUnavailable" } | { "type": "candidateVerificationFailed", discarded: number, } | { "type": "contentBudgetExceeded", discarded: number, };
