// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CodebaseSymbolsSearchHitDto } from './CodebaseSymbolsSearchHitDto.js';
import type { CodebaseSymbolsStatusResult } from './CodebaseSymbolsStatusResult.js';

export type CodebaseSymbolsSearchResult = { status: CodebaseSymbolsStatusResult, hits: Array<CodebaseSymbolsSearchHitDto>,
/**
 * Matches discarded because their exact source revision could no longer be materialized.
 */
discardedStaleHitCount: number, };
