// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ConfigCommandDispositionDto } from './ConfigCommandDispositionDto.js';

export type ConfigCommandResult = { revision: number, generation: number, disposition: ConfigCommandDispositionDto, };
