// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentGrepBackendDto } from './AgentGrepBackendDto.js';
import type { ApprovalReviewModelSelection } from './ApprovalReviewModelSelection.js';
import type { CodebaseConfigDto } from './CodebaseConfigDto.js';
import type { ExecPolicyRuleDto } from './ExecPolicyRuleDto.js';
import type { FeatureState } from './FeatureState.js';
import type { FrontendConfigDto } from './FrontendConfigDto.js';
import type { HookConfigDto } from './HookConfigDto.js';
import type { IssueConfigDto } from './IssueConfigDto.js';
import type { LanguageServerConfigDto } from './LanguageServerConfigDto.js';
import type { McpServerConfigDto } from './McpServerConfigDto.js';
import type { ModelRef } from './ModelRef.js';
import type { PluginRequestDto } from './PluginRequestDto.js';
import type { ProviderConfigDto } from './ProviderConfigDto.js';
import type { ReasoningEffort } from './ReasoningEffort.js';
import type { SkillSourceConfigDto } from './SkillSourceConfigDto.js';
import type { ToolMode } from './ToolMode.js';
import type { ToolSearchConfigDto } from './ToolSearchConfigDto.js';

export type ConfigReadResult = { features: Array<FeatureState>, issues: IssueConfigDto, revision: number, generation: number, preferredModel: ModelRef | null, preferredReasoningEffort?: ReasoningEffort | null, approvalReviewModel: ApprovalReviewModelSelection, commitMessageModel?: ModelRef | null, commitMessageActiveDirAuthorized: boolean, toolMode: ToolMode, agentGrepBackend: AgentGrepBackendDto, gui: FrontendConfigDto, providers: { [key in string]: ProviderConfigDto }, mcpServers: { [key in string]: McpServerConfigDto }, skillSources: { [key in string]: SkillSourceConfigDto }, pluginRequests: { [key in string]: PluginRequestDto }, hooks: { [key in string]: HookConfigDto }, languageServers: { [key in string]: LanguageServerConfigDto }, toolSearch: ToolSearchConfigDto, codebase: CodebaseConfigDto, execPolicyRules: Array<ExecPolicyRuleDto>, tui: FrontendConfigDto, };
