// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ConnectorSecretDto } from './ConnectorSecretDto.js';

export type ConnectorApiTokenConnectParams = { commandId: string, expectedGeneration: number, connectorId: string, connectionGeneration: number, accountId: string, accountDisplayName: string, apiToken: ConnectorSecretDto, };
