// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type ConnectorAvailableActionDto = "connectApiToken" | "connectOAuth" | "disconnect" | "reauthorizeApiToken" | "reauthorizeOAuth" | "refreshOAuth" | "revokeOAuth";
