// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ConnectorSecretDto } from './ConnectorSecretDto.js';

export type ConnectorOAuthCompleteParams = { flowId: string, state: ConnectorSecretDto, authorizationCode: ConnectorSecretDto, };
