// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ConnectorDto } from './ConnectorDto.js';

export type ConnectorListResult = { generation: number, connectors: Array<ConnectorDto>, };
