// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type ConnectorDeviceOAuthStartResult = { flowId: string, userCode: string, verificationUri: string, expiresInSeconds: number, pollIntervalSeconds: number, };
