// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type ConnectorOAuthStartParams = { commandId: string, expectedGeneration: number, connectorId: string, connectionGeneration: number, redirectUri: string, };
