// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ContentSearchMatch } from './ContentSearchMatch.js';

export type ContentSearchReadResult = { searchId: string, matches: Array<ContentSearchMatch>, nextMatch: number, completed: boolean, limitHit: boolean, error: string | null, };
