// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ContentSearchCaseSensitivity } from './ContentSearchCaseSensitivity.js';
import type { ContentSearchPatternKind } from './ContentSearchPatternKind.js';
import type { SessionDirSelector } from './SessionDirSelector.js';

export type ContentSearchStartParams = { dirId?: string, sessionDirectory?: SessionDirSelector, query: string, patternKind: ContentSearchPatternKind, caseSensitivity: ContentSearchCaseSensitivity, includePatterns: Array<string>, excludePatterns: Array<string>, maxResults: number, };
