// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ContextCheckpointId } from './ContextCheckpointId.js';
import type { ContextCheckpointVerification } from './ContextCheckpointVerification.js';
import type { ContextSourceDigest } from './ContextSourceDigest.js';
import type { ContextSourceRange } from './ContextSourceRange.js';
import type { ItemId } from './ItemId.js';
import type { ModelRef } from './ModelRef.js';
import type { ThreadId } from './ThreadId.js';

export type ContextCheckpoint = { checkpointId: ContextCheckpointId, sourceThreadId: ThreadId, covered: ContextSourceRange, referencedItems: Array<ItemId>, sourceDigest: ContextSourceDigest, summary: string, schemaRevision: string, promptRevision: string, contextPolicyRevision: string, generatorModel?: ModelRef | null, createdAtUnixMs: number, verification: ContextCheckpointVerification, };
