// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CustomProviderProtocolDto } from './CustomProviderProtocolDto.js';

export type CustomProviderConfigDto = { contextWindow: number, order: bigint, model?: string | null, name: string, protocol: CustomProviderProtocolDto, };
