// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { DebugAdapterMessageDto } from './DebugAdapterMessageDto.js';

export type DebugAdapterReadResult = { messages: Array<DebugAdapterMessageDto>, nextSequence: number, outputGap: boolean, stderr: string, exited: boolean, exitCode: number | null, protocolError: string | null, };
