// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type DelegationResultStatus = "completed" | "failed" | "cancelled" | "policyDenied" | "capacityRejected" | "contextSeedInvalid" | "deliveryFailed" | "unknownOutcome";
