// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';

export type DelegationArtifactRef = { uri: string, contentDigest?: ContentDigest | null, };
