// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { DelegationArtifactRef } from './DelegationArtifactRef.js';
import type { DelegationId } from './DelegationId.js';
import type { DelegationResultDigest } from './DelegationResultDigest.js';
import type { DelegationResultStatus } from './DelegationResultStatus.js';
import type { ThreadId } from './ThreadId.js';
import type { ThreadSequenceRange } from './ThreadSequenceRange.js';

export type DelegationResult = { delegationId: DelegationId, childThreadId: ThreadId, status: DelegationResultStatus, summary: string, artifacts: Array<DelegationArtifactRef>, sourceRange: ThreadSequenceRange, digest: DelegationResultDigest, };
