// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { Activity } from './Activity.js';
import type { ActivitySummary } from './ActivitySummary.js';
import type { BuildInfo } from './BuildInfo.js';
import type { Observation } from './Observation.js';
import type { UsageSnapshot } from './UsageSnapshot.js';

export type DiagnosticSnapshot = { build: BuildInfo, activities: { [key in Activity]?: ActivitySummary }, recent: Array<Observation>, usage: UsageSnapshot, };
