// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { DiffComputeRowDto } from './DiffComputeRowDto.js';
import type { DiffHunkDto } from './DiffHunkDto.js';

export type DiffComputeResult = { rows: Array<DiffComputeRowDto>, hunks: Array<DiffHunkDto>, originalLineCount: number, modifiedLineCount: number, };
