// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type DiffHunkDto = { rowStart: number, rowEnd: number, originalStartLineIndex: number, originalLineCount: number, modifiedStartLineIndex: number, modifiedLineCount: number, };
