// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { PermissionDto } from './PermissionDto.js';

export type DirGrantDto = { "type": "config" } | { "type": "host", permissions: Array<PermissionDto>, } | { "type": "user", commandId: CommandId, expectedRevision: number, permissions: Array<PermissionDto>, };
