// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { DirId } from './DirId.js';
import type { PermissionDto } from './PermissionDto.js';

export type DirPermissionsReadResult = { dir: DirId, permissions?: Array<PermissionDto> | null, };
