// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { PermissionDto } from './PermissionDto.js';

export type DirPermissionsSetParams = { commandId: CommandId, expectedRevision: number, path: string, permissions: Array<PermissionDto>, };
