// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { DirPermissionsEntryDto } from './DirPermissionsEntryDto.js';

export type DirPermissionsListResult = { revision: number, entries: Array<DirPermissionsEntryDto>, };
