// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type DocumentCollaborationOpenParams = { roomId?: string | null, clientId: string, schemaId: string,
/**
 * Serialized, schema-validated document supplied only when creating a room.
 */
document: string, };
