// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { DocumentCollaborationPresence } from './DocumentCollaborationPresence.js';

export type DocumentCollaborationPresenceSnapshot = { roomId: string, generation: number, presences: Array<DocumentCollaborationPresence>, };
