// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { DynamicToolOutput } from './DynamicToolOutput.js';
import type { ToolCallId } from './ToolCallId.js';

export type DynamicToolResponse = { callId: ToolCallId, content: Array<DynamicToolOutput>, success: boolean, };
