// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { EnvDirSetEntry } from './EnvDirSetEntry.js';

export type EnvDirsSetParams = { dirs: Array<EnvDirSetEntry>, };
