// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { PermissionDto } from './PermissionDto.js';

export type EnvDirDto = { id: string, path: string, permissions: Array<PermissionDto>, };
