// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ExecPolicyActionKindDto } from './ExecPolicyActionKindDto.js';
import type { ExecPolicyHostMatcherDto } from './ExecPolicyHostMatcherDto.js';
import type { ExecPolicyScopeMatcherDto } from './ExecPolicyScopeMatcherDto.js';
import type { ExecPolicyTokenDto } from './ExecPolicyTokenDto.js';

export type ExecPolicySelectorDto = { "type": "any" } | { "type": "actionDigest", digest: string, } | { "type": "actionKind", actionKind: ExecPolicyActionKindDto, } | { "type": "source", source?: string | null, sourceId?: string | null, } | { "type": "commandPrefix", pattern: Array<ExecPolicyTokenDto>, } | { "type": "network", protocol?: string | null, host: ExecPolicyHostMatcherDto, port?: number | null, } | { "type": "capability", capabilityKind: string, scope: ExecPolicyScopeMatcherDto, } | { "type": "all", selectors: Array<ExecPolicySelectorDto>, };
