// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ExecPolicyEffectDto } from './ExecPolicyEffectDto.js';
import type { ExecPolicySelectorDto } from './ExecPolicySelectorDto.js';

export type ExecPolicyRuleDto = { id: string, selector: ExecPolicySelectorDto, effect: ExecPolicyEffectDto, justification?: string | null, };
