// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { ExecPolicyRuleDto } from './ExecPolicyRuleDto.js';

export type ExecPolicyRuleUpsertParams = { commandId: CommandId, expectedRevision: number, rule: ExecPolicyRuleDto, };
