// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionItemStatus } from './ExtensionItemStatus.js';

export type ExtensionItem = { extension: string, id: string, title: string, body: string, status: ExtensionItemStatus, };
