// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionCatalogReloadDto } from './ExtensionCatalogReloadDto.js';

export type ExtensionListParams = { reload: ExtensionCatalogReloadDto, };
