// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionDiagnosticCodeDto } from './ExtensionDiagnosticCodeDto.js';

export type ExtensionDiagnosticDto = { source: string, subject: string | null, code: ExtensionDiagnosticCodeDto, message: string, };
