// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostInvokeCancelDispositionDto } from './ExtensionHostInvokeCancelDispositionDto.js';

export type ExtensionHostInvokeCancelResult = { disposition: ExtensionHostInvokeCancelDispositionDto, };
