// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionDiagnosticDto } from './ExtensionDiagnosticDto.js';
import type { ExtensionDto } from './ExtensionDto.js';

export type ExtensionListResult = { generation: number, extensions: Array<ExtensionDto>, diagnostics: Array<ExtensionDiagnosticDto>, };
