// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ExtensionHostCancellationReasonDto } from './ExtensionHostCancellationReasonDto.js';
import type { ExtensionHostFailureCodeDto } from './ExtensionHostFailureCodeDto.js';

export type ExtensionHostInvokeReadResult = { "state": "pending" } | { "state": "succeeded", payload: unknown, } | { "state": "failed", code: ExtensionHostFailureCodeDto, message: string, } | { "state": "cancelled", reason: ExtensionHostCancellationReasonDto, };
