// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type ExtensionDiagnosticCodeDto = "sourceUnavailable" | "invalidManifest" | "duplicateExtension" | "pathEscapesRoot" | "resourceNotFound" | "resourceTooLarge";
