// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SearchSource } from './SearchSource.js';

export type ExtensionItemContent = { "type": "text" } | { "type": "webSearch", queries: Array<string>, sources: Array<SearchSource>, } | { "type": "image", mimeType: string, savedPath: string, } | { "type": "sleep", durationMs: number, };
