// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type ExtensionHostInvokeStartParams = { extensionId: string, registrationId: string, activationGeneration: number, incarnation: number, operation: string, payload: unknown, deadlineUnixMillis: number, };
