// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type FastRegexIndexStatusResult = { enabled: boolean, active: boolean, generation: number | null, indexedFileCount: number, indexedSourceBytes: number, };
