// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { FsExistingTargetBehavior } from './FsExistingTargetBehavior.js';
import type { SessionDirSelector } from './SessionDirSelector.js';

export type FsCreateFileParams = { dirId?: string, sessionDirectory?: SessionDirSelector, path: string, existing: FsExistingTargetBehavior, };
