// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { FsFileType } from './FsFileType.js';

export type FsGetMetadataResult = { fileType: FsFileType, sizeBytes: number, readonly: boolean, modifiedAtMillis: number | null, };
