// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type FsReadFileResult = { content: string,
/**
 * Opaque exact-content revision required to protect a later conditional write.
 */
revision: string, };
