// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type FsReadFileParams = { dirId?: string, sessionDirectory?: SessionDirSelector, path: string, };
