// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { FsFileType } from './FsFileType.js';

export type FsReadDirectoryEntry = { name: string, fileType: FsFileType, };
