// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type FsWriteFileParams = { dirId?: string, sessionDirectory?: SessionDirSelector, path: string, content: string,
/**
 * When supplied, rejects the write if the file no longer has this exact revision.
 */
expectedRevision?: string | null, };
