// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { GitBranchDto } from './GitBranchDto.js';

export type GitBranchListResult = { branches: Array<GitBranchDto>, };
