// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { GitStatusResult } from './GitStatusResult.js';

export type GitCommitResult = { objectId: string, status: GitStatusResult, };
