// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { GitChangeStatusDto } from './GitChangeStatusDto.js';

export type GitCommitChangeDto = { path: string, originalPath: string | null, status: GitChangeStatusDto, };
