// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { GitCommitSummaryDto } from './GitCommitSummaryDto.js';

export type GitHistoryResult = { commits: Array<GitCommitSummaryDto>, };
