// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { GitChangeStatusDto } from './GitChangeStatusDto.js';
import type { GitSubmoduleStateDto } from './GitSubmoduleStateDto.js';

export type GitRepositoryChangeDto = { path: string, originalPath: string | null, indexStatus: GitChangeStatusDto, worktreeStatus: GitChangeStatusDto, conflicted: boolean, submodule: GitSubmoduleStateDto, };
