// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { GitReferenceKindDto } from './GitReferenceKindDto.js';

export type GitReferenceDto = { name: string, objectId: string, kind: GitReferenceKindDto, remoteName: string | null, current: boolean, };
