// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { GitHeadDto } from './GitHeadDto.js';
import type { GitRepositoryChangeDto } from './GitRepositoryChangeDto.js';
import type { StreamInstanceId } from './StreamInstanceId.js';

export type GitStatusResult = { repositoryId: string, streamInstanceId: StreamInstanceId, revision: number, path: string, head: GitHeadDto, changes: Array<GitRepositoryChangeDto>, };
