// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { HookActionDto } from './HookActionDto.js';
import type { HookEnablementDto } from './HookEnablementDto.js';
import type { HookEventDto } from './HookEventDto.js';
import type { HookMatcherDto } from './HookMatcherDto.js';

export type HookConfigDto = { id: string, event: HookEventDto, matcher: HookMatcherDto, action: HookActionDto, enablement: HookEnablementDto, };
