// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ClientCapabilities } from './ClientCapabilities.js';
import type { ClientInfo } from './ClientInfo.js';

export type InitializeParams = { clientInfo: ClientInfo, capabilities: ClientCapabilities, };
