// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';

export type IssueReadParams = { repository: IssueRepository, number: number, };
