// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { IssueComment } from './IssueComment.js';
import type { IssueSummary } from './IssueSummary.js';

export type IssueReadResult = { issue: IssueSummary, body: string, comments: Array<IssueComment>, };
