// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type IssueSummary = { labels: Array<string>, assignees: Array<string>, number: number, title: string, url: string, updatedAt: string, state: string, };
