// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { IssueRepository } from './IssueRepository.js';
import type { IssueSummary } from './IssueSummary.js';

export type IssueListResult = { repository: IssueRepository, issues: Array<IssueSummary>, nextPage: number | null, cached: boolean, fetchedAt: number, refreshAfterSeconds: number | null, notice: string, };
