// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type LanguageDocumentDto = {
/**
 * directory folder that owns this document in a multi-root directory.
 */
dirId?: string, sessionDirectory?: SessionDirSelector, path: string, languageId: string, revision: number, text: string, };
