// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCommandDto } from './LanguageCommandDto.js';
import type { LanguageCompletionInsertTextFormatDto } from './LanguageCompletionInsertTextFormatDto.js';
import type { LanguageCompletionItemKindDto } from './LanguageCompletionItemKindDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';
import type { LanguageTextEditDto } from './LanguageTextEditDto.js';

export type LanguageCompletionItemDto = { label: string, kind: LanguageCompletionItemKindDto, detail: string | null, documentation: string | null, filterText: string | null, sortText: string | null, preselect: boolean | null, commitCharacters: Array<string>, insertTextFormat: LanguageCompletionInsertTextFormatDto, range: LanguageRangeDto, insertText: string, additionalTextEdits: Array<LanguageTextEditDto>, command: LanguageCommandDto | null, providerData: unknown, };
