// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';

export type LanguageDocumentFeaturesParams = { document: LanguageDocumentDto, };
