// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageSemanticTokenDto = { range: LanguageRangeDto, tokenType: string, modifiers: Array<string>, };
