// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageSemanticTokenDto } from './LanguageSemanticTokenDto.js';

export type LanguageSemanticTokensResult = { revision: number, resultId: string | null, tokens: Array<LanguageSemanticTokenDto>, };
