// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageHierarchyEntryDto } from './LanguageHierarchyEntryDto.js';

export type LanguageHierarchyResultDto = { revision: number, entries: Array<LanguageHierarchyEntryDto>, };
