// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageServerModeDto } from './LanguageServerModeDto.js';

export type LanguageServerConfigDto = { mode: LanguageServerModeDto, executable?: string | null, };
