// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { LanguageServerConfigDto } from './LanguageServerConfigDto.js';

export type LanguageServerConfigureParams = { commandId: CommandId, expectedRevision: number, serverId: string, config: LanguageServerConfigDto, };
