// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type LanguageServerProgressNotification = { dirId?: string, server: string, token: string, title: string | null, message: string | null, percentage: number | null, done: boolean, };
