// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguageHierarchyItemDto } from './LanguageHierarchyItemDto.js';
import type { LanguageHierarchyKindDto } from './LanguageHierarchyKindDto.js';
import type { LanguagePositionDto } from './LanguagePositionDto.js';

export type LanguageHierarchyParams = { document: LanguageDocumentDto, kind: LanguageHierarchyKindDto, position: LanguagePositionDto | null, item: LanguageHierarchyItemDto | null, };
