// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';

export type LanguageServerRemoveParams = { commandId: CommandId, expectedRevision: number, serverId: string, };
