// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageTextEditDto = { range: LanguageRangeDto, newText: string, };
