// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguageFormattingOptionsDto } from './LanguageFormattingOptionsDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageRangeFormattingParams = { document: LanguageDocumentDto, range: LanguageRangeDto, options: LanguageFormattingOptionsDto, };
