// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageInlayHintDto } from './LanguageInlayHintDto.js';

export type LanguageInlayHintsResult = { revision: number, hints: Array<LanguageInlayHintDto>, };
