// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageTextEditDto } from './LanguageTextEditDto.js';

export type LanguageColorPresentationDto = { label: string, textEdit: LanguageTextEditDto | null, additionalTextEdits: Array<LanguageTextEditDto>, };
