// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentLinkDto } from './LanguageDocumentLinkDto.js';

export type LanguageDocumentLinksResult = { revision: number, links: Array<LanguageDocumentLinkDto>, };
