// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCommandDto } from './LanguageCommandDto.js';
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';

export type LanguageExecuteCommandParams = { document: LanguageDocumentDto, command: LanguageCommandDto, };
