// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDirectoryEditDto } from './LanguageDirectoryEditDto.js';

export type LanguageCodeActionDto = { title: string, kind: string | null, isPreferred: boolean, disabledReason: string | null, edit: LanguageDirectoryEditDto | null, providerData: unknown, };
