// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCodeActionDiagnosticDto } from './LanguageCodeActionDiagnosticDto.js';

export type LanguageDiagnosticsNotification = { dirId?: string, path: string, revision: number, diagnostics: Array<LanguageCodeActionDiagnosticDto>, };
