// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageHoverResult = { revision: number, contents: string | null, range: LanguageRangeDto | null, };
