// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentDto } from './LanguageDocumentDto.js';
import type { LanguageLocationKindDto } from './LanguageLocationKindDto.js';
import type { LanguagePositionDto } from './LanguagePositionDto.js';

export type LanguageLocationsParams = { document: LanguageDocumentDto, position: LanguagePositionDto, kind: LanguageLocationKindDto, includeDeclaration: boolean, };
