// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageParameterInformationDto } from './LanguageParameterInformationDto.js';

export type LanguageSignatureInformationDto = { label: string, documentation: string | null, parameters: Array<LanguageParameterInformationDto>, activeParameter: number | null, };
