// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDocumentColorDto } from './LanguageDocumentColorDto.js';

export type LanguageDocumentColorsResult = { revision: number, colors: Array<LanguageDocumentColorDto>, };
