// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCodeActionDiagnosticDto } from './LanguageCodeActionDiagnosticDto.js';

export type LanguageDirectoryDiagnosticSnapshotDto = { path: string, diagnostics: Array<LanguageCodeActionDiagnosticDto>, };
