// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDiagnosticSeverityDto } from './LanguageDiagnosticSeverityDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageCodeActionDiagnosticDto = { range: LanguageRangeDto, severity: LanguageDiagnosticSeverityDto, message: string, code: unknown, source: string | null, };
