// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCommandDto } from './LanguageCommandDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageCodeLensDto = { range: LanguageRangeDto, command: LanguageCommandDto | null, providerData: unknown, };
