// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageTextEditDto } from './LanguageTextEditDto.js';

export type LanguageTextDocumentEditDto = { path: string, expectedText: string, edits: Array<LanguageTextEditDto>, };
