// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageDirectorySymbolDto } from './LanguageDirectorySymbolDto.js';

export type LanguageDirectorySymbolsResult = { symbols: Array<LanguageDirectorySymbolDto>, };
