// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type LanguageServerStateDto = { "type": "starting" } | { "type": "ready" } | { "type": "backingOff", attempt: number, retryAfterMillis: number, } | { "type": "crashLoop", restartAttempts: number, message: string, } | { "type": "failed", message: string, } | { "type": "stopped" };
