// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageHierarchyItemDto } from './LanguageHierarchyItemDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageHierarchyEntryDto = { item: LanguageHierarchyItemDto, fromPath: string | null, fromRanges: Array<LanguageRangeDto>, };
