// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirSelector } from './SessionDirSelector.js';

export type LanguageDirectoryDiagnosticsParams = { dirId?: string, sessionDirectory?: SessionDirSelector, languageId: string, };
