// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageColorDto } from './LanguageColorDto.js';
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageDocumentColorDto = { range: LanguageRangeDto, color: LanguageColorDto, };
