// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageServerStateDto } from './LanguageServerStateDto.js';

export type LanguageServerStateNotification = { dirId?: string, server: string, state: LanguageServerStateDto, };
