// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageDirectorySymbolDto = { name: string, symbolKind: number, containerName: string | null, path: string, range: LanguageRangeDto, };
