// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageRangeDto } from './LanguageRangeDto.js';

export type LanguageLinkedEditingRangesResult = { revision: number, ranges: Array<LanguageRangeDto>, wordPattern: string | null, };
