// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { LanguageCodeActionDiagnosticDto } from './LanguageCodeActionDiagnosticDto.js';
import type { LanguageDiagnosticReportKindDto } from './LanguageDiagnosticReportKindDto.js';

export type LanguageDocumentDiagnosticsResult = { revision: number, kind: LanguageDiagnosticReportKindDto, diagnostics: Array<LanguageCodeActionDiagnosticDto>, };
