// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceCapabilityRefDto } from './MarketplaceCapabilityRefDto.js';

export type MarketplaceCapabilityLeaseDto = { id: string, capability: MarketplaceCapabilityRefDto, installationId: string, };
