// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceExecutableRuntimeDto } from './MarketplaceExecutableRuntimeDto.js';
import type { MarketplaceResourceRefDto } from './MarketplaceResourceRefDto.js';

export type MarketplaceExecutableActivationSpecDto = { contractVersion: string, runtime: MarketplaceExecutableRuntimeDto, entrypoint: MarketplaceResourceRefDto, };
