// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type MarketplaceInstallParams = {
/**
 * Exact `<name>@<marketplace>` returned by search; unqualified names are rejected.
 */
packageId: string, version: string | null, };
