// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceMcpTransportDto } from './MarketplaceMcpTransportDto.js';

export type MarketplaceMcpActivationSpecDto = { contractVersion: string, transport: MarketplaceMcpTransportDto, networkHosts: Array<string>, };
