// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceResourceRefDto } from './MarketplaceResourceRefDto.js';

export type MarketplaceThemeActivationSpecDto = { contractVersion: string, manifest: MarketplaceResourceRefDto, };
