// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceActivationSpecDto } from './MarketplaceActivationSpecDto.js';
import type { MarketplaceCapabilityLeaseDto } from './MarketplaceCapabilityLeaseDto.js';

export type MarketplaceAcquiredCapabilityDto = { lease: MarketplaceCapabilityLeaseDto, spec: MarketplaceActivationSpecDto, };
