// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type MarketplacePackageRefDto = {
/**
 * Source-qualified plugin identity: `<name>@<marketplace>`.
 */
id: string, version: string, digest: string, };
