// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceResourceRefDto } from './MarketplaceResourceRefDto.js';

export type MarketplaceLocalizationActivationSpecDto = { contractVersion: string, catalog: MarketplaceResourceRefDto, };
