// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type MarketplaceCapabilityKindDto = "skill" | "mcp" | "connector" | "theme" | "language" | "localization" | "executable" | "asset";
