// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceResourceRefDto } from './MarketplaceResourceRefDto.js';

export type MarketplaceMcpTransportDto = { "type": "stdio", executable: MarketplaceResourceRefDto, args: Array<string>, } | { "type": "streamableHttp", url: string, };
