// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceCapabilityDescriptorDto } from './MarketplaceCapabilityDescriptorDto.js';
import type { MarketplaceInstallationStateDto } from './MarketplaceInstallationStateDto.js';
import type { MarketplacePackageRefDto } from './MarketplacePackageRefDto.js';

export type MarketplaceInstalledPackageDto = { installationId: string, package: MarketplacePackageRefDto, state: MarketplaceInstallationStateDto, capabilities: Array<MarketplaceCapabilityDescriptorDto>, };
