// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceConnectorActivationSpecDto } from './MarketplaceConnectorActivationSpecDto.js';
import type { MarketplaceExecutableActivationSpecDto } from './MarketplaceExecutableActivationSpecDto.js';
import type { MarketplaceLanguageActivationSpecDto } from './MarketplaceLanguageActivationSpecDto.js';
import type { MarketplaceLocalizationActivationSpecDto } from './MarketplaceLocalizationActivationSpecDto.js';
import type { MarketplaceMcpActivationSpecDto } from './MarketplaceMcpActivationSpecDto.js';
import type { MarketplaceSkillActivationSpecDto } from './MarketplaceSkillActivationSpecDto.js';
import type { MarketplaceThemeActivationSpecDto } from './MarketplaceThemeActivationSpecDto.js';

export type MarketplaceActivationSpecDto = { "kind": "skill" } & MarketplaceSkillActivationSpecDto | { "kind": "mcp" } & MarketplaceMcpActivationSpecDto | { "kind": "connector" } & MarketplaceConnectorActivationSpecDto | { "kind": "theme" } & MarketplaceThemeActivationSpecDto | { "kind": "language" } & MarketplaceLanguageActivationSpecDto | { "kind": "localization" } & MarketplaceLocalizationActivationSpecDto | { "kind": "executable" } & MarketplaceExecutableActivationSpecDto;
