// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplacePackageSummaryDto } from './MarketplacePackageSummaryDto.js';

export type MarketplaceSearchResult = { packages: Array<MarketplacePackageSummaryDto>, };
