// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplaceCapabilityRefDto } from './MarketplaceCapabilityRefDto.js';

export type MarketplaceAcquireCapabilityParams = { capability: MarketplaceCapabilityRefDto, };
