// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MarketplacePackageRefDto } from './MarketplacePackageRefDto.js';

export type MarketplaceArtifactHandleDto = { id: string, package: MarketplacePackageRefDto, };
