// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { McpServerStatusDto } from './McpServerStatusDto.js';

export type McpServerStatusResult = { catalogGeneration: number, servers: Array<McpServerStatusDto>, };
