// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { McpServerRuntimeIntentDto } from './McpServerRuntimeIntentDto.js';

export type McpServerRuntimeIntentResult = { serverId: string, intent: McpServerRuntimeIntentDto, };
