// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { McpServerEnablementDto } from './McpServerEnablementDto.js';

export type McpServerSetEnablementParams = { commandId: CommandId, expectedRevision: number, serverId: string, enablement: McpServerEnablementDto, };
