// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type McpServerRuntimeStateDto = { "status": "disabled" } | { "status": "disconnected" } | { "status": "connected" } | { "status": "stale" } | { "status": "unavailable", reason: string, };
