// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryProduct } from './MemoryProduct.js';

export type MemoryStart = { requestId: string, product: MemoryProduct, durationSecs: number, };
