// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type MemoryFinding = "insufficientEvidence" | "noSustainedGrowthObserved" | "sustainedGrowth" | "idleBaselineGrowth";
