// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryOrigin } from './MemoryOrigin.js';
import type { MemoryRole } from './MemoryRole.js';
import type { MemorySample } from './MemorySample.js';
import type { MemoryTrend } from './MemoryTrend.js';

export type MemoryTargetReport = { origin: MemoryOrigin, instanceId: string, processId: number | null, role: MemoryRole, samples: number, discardedSamples: number, latest: MemorySample, trends: Array<MemoryTrend>, };
