// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryReadMode } from './MemoryReadMode.js';
import type { MemoryScope } from './MemoryScope.js';

export type MemoryPolicy = { scope: MemoryScope, revision: number, automaticRead: MemoryReadMode, };
