// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryCitation } from './MemoryCitation.js';

export type MemoryCitationReadParams = { citation: MemoryCitation, };
