// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryId } from './MemoryId.js';
import type { MemoryMutationDisposition } from './MemoryMutationDisposition.js';
import type { MemoryScope } from './MemoryScope.js';

export type MemoryDeleteResult = { disposition: MemoryMutationDisposition, catalogRevision: number, memoryId: MemoryId, scope: MemoryScope, deletedRevision: number, };
