// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemorySearchMatch } from './MemorySearchMatch.js';

export type MemorySearchPage = { catalogRevision: number, matches: Array<MemorySearchMatch>, nextCursor: string | null, };
