// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryId } from './MemoryId.js';
import type { MemoryScope } from './MemoryScope.js';
import type { MemorySource } from './MemorySource.js';

export type Memory = { memoryId: MemoryId, scope: MemoryScope, revision: number, title: string, body: string, source: MemorySource, createdAtUnixMs: number, updatedAtUnixMs: number, };
