// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryObservation } from './MemoryObservation.js';

export type MemoryEvidence = { sessionId: string, sequence: number, observations: Array<MemoryObservation>, };
