// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryScope } from './MemoryScope.js';

export type MemorySearchParams = { scope: MemoryScope, query: string, cursor?: string | null, limit?: number | null, };
