// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryMetric } from './MemoryMetric.js';
import type { MemoryPhase } from './MemoryPhase.js';

export type MemorySample = { elapsedMs: number, phase: MemoryPhase, metrics: Array<MemoryMetric>, };
