// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryId } from './MemoryId.js';
import type { MemoryScope } from './MemoryScope.js';

export type MemoryReadParams = { memoryId: MemoryId, scope: MemoryScope, };
