// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MemoryId } from './MemoryId.js';
import type { MemoryScope } from './MemoryScope.js';

export type MemoryCitation = { memoryId: MemoryId, scope: MemoryScope, revision: number, startByte: number, endByte: number, };
