// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { MessageCheckpoint } from './MessageCheckpoint.js';

export type MessageCheckpointsResult = { checkpoints: Array<MessageCheckpoint>, };
