// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CapabilitySupport } from './CapabilitySupport.js';

export type ModelCapabilities = { tools: CapabilitySupport, reasoning: CapabilitySupport, parallelToolCalls: CapabilitySupport, personality: CapabilitySupport, imageDetailOriginal: CapabilitySupport, };
