// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ModelMoneyAmount } from './ModelMoneyAmount.js';

export type ModelCostLineItem = { dimension: string, quantity: number, ratePicoUnitsPerToken: string, amount: ModelMoneyAmount, };
