// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ModelAccess } from './ModelAccess.js';
import type { ModelCapabilities } from './ModelCapabilities.js';
import type { ModelOutputTransport } from './ModelOutputTransport.js';
import type { ModelRef } from './ModelRef.js';
import type { Personality } from './Personality.js';
import type { ReasoningEffort } from './ReasoningEffort.js';

export type ModelCatalogEntry = { model: ModelRef, displayName: string, access: ModelAccess, outputTransport: ModelOutputTransport, contextWindow: number | null, autoCompactTokenLimit: number | null, availableContextWindow?: number | null, capabilities: ModelCapabilities, supportedReasoningEfforts: Array<ReasoningEffort>, defaultReasoningEffort: ReasoningEffort | null, defaultPersonality: Personality | null, };
