// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ModelBillingEvidence } from './ModelBillingEvidence.js';

export type ModelBillingRecord = { billingPlatform: string, operation: string, requestedServiceTier?: string | null, appliedServiceTier: string, serviceTierEvidence: ModelBillingEvidence, region: string, pricingVariant: string, rateCardRevision: string, };
