// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type ModelUsage = {
/**
 * Total provider-accounted input tokens, including cache reads and cache writes.
 */
inputTokens: number | null, outputTokens: number | null,
/**
 * Input tokens read from a provider prompt cache.
 */
cachedInputTokens: number | null,
/**
 * Input tokens written to a provider prompt cache.
 */
cacheWriteInputTokens: number | null, reasoningTokens: number | null, };
