// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { Activity } from './Activity.js';
import type { Outcome } from './Outcome.js';

export type Observation = { activity: Activity, outcome: Outcome, elapsedMs: number, };
