// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { PluginPackageDto } from './PluginPackageDto.js';

export type PluginListResult = { revision: number, activationGeneration: number, packages: Array<PluginPackageDto>, };
