// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { PluginRequestDto } from './PluginRequestDto.js';

export type PluginRequestUpsertParams = { commandId: CommandId, expectedRevision: number, request: PluginRequestDto, };
