// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { PluginRequestEnablementDto } from './PluginRequestEnablementDto.js';

export type PluginRequestDto = { pluginId: string, version: string, enablement: PluginRequestEnablementDto, };
