// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type PreparedFeedback = { digest: string, endpoint: string,
/**
 * Exact JSON bytes the user reviews and authorizes for this destination.
 */
content: string, };
