// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ProcessExitStatus } from './ProcessExitStatus.js';

export type ProcessExecutionOutput = { exitStatus: ProcessExitStatus, stdout: string, stderr: string, aggregatedOutput: string, };
