// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { ProjectId } from './ProjectId.js';

export type ProjectDetailsUpdateParams = { commandId: CommandId, projectId: ProjectId, expectedRevision: number, name: string, description: string, };
