// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { DirId } from './DirId.js';
import type { ProjectId } from './ProjectId.js';

export type ProjectRootUpdateParams = { commandId: CommandId, projectId: ProjectId, expectedRevision: number, dirId: DirId, name: string, purpose: string, };
