// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { DirId } from './DirId.js';
import type { ProjectId } from './ProjectId.js';
import type { SessionId } from './SessionId.js';

export type ProjectRootAddParams = { commandId: CommandId, projectId: ProjectId, expectedRevision: number, sessionId: SessionId, dirId: DirId, name: string, purpose: string, };
