// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ProviderModelsListFailureCodeDto } from './ProviderModelsListFailureCodeDto.js';

export type ProviderModelsListFailureDto = { code: ProviderModelsListFailureCodeDto, };
