// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ProviderCatalogEntryDto } from './ProviderCatalogEntryDto.js';

export type ProviderListResult = { providers: Array<ProviderCatalogEntryDto>, };
