// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ProviderApiKeyDto } from './ProviderApiKeyDto.js';

export type ProviderApiKeySetParams = { provider: string, apiKey: ProviderApiKeyDto, };
