// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { InputItem } from './InputItem.js';
import type { QueueMove } from './QueueMove.js';
import type { TurnId } from './TurnId.js';

export type QueueEditAction = { "type": "pause" } | { "type": "replace", input: Array<InputItem>, } | { "type": "move", direction: QueueMove, } | { "type": "send", turnId: TurnId | null, };
