// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { QueueEditAction } from './QueueEditAction.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';

export type QueueEditParams = { sessionId: SessionId, threadId: ThreadId, commandId: CommandId, expectedRevision: number, action: QueueEditAction, };
