// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { QueuedMessage } from './QueuedMessage.js';

export type QueueListResult = { messages: Array<QueuedMessage>, };
