// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CapabilityContract } from './CapabilityContract.js';

export type ServerCapabilities = { agentInteractions: boolean, documentCollaboration: boolean, sessions: boolean, threads: boolean, turns: boolean, projects: boolean, memories: boolean, resources: boolean, attachments: boolean, fileSystem: boolean, git: boolean, contentSearch: boolean, codebase: boolean, cloudCodebase: boolean, terminal: boolean, debugAdapter: boolean, typst: boolean, updateReplay: boolean, extensions: boolean, extensionHost: boolean, connectors: boolean, plugins: boolean, marketplace: boolean, mcp: boolean, mcpOAuth: boolean, contracts: { [key in string]: CapabilityContract }, };
