// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirDto } from './SessionDirDto.js';

export type SessionDirListResult = { revision: number, dirs: Array<SessionDirDto>, };
