// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionDirDto } from './SessionDirDto.js';
import type { SessionDirMutationDto } from './SessionDirMutationDto.js';

export type SessionDirMutationResult = { mutation: SessionDirMutationDto, revision: number, dirs: Array<SessionDirDto>, };
