// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { AgentRoleSelection } from './AgentRoleSelection.js';
import type { CommandId } from './CommandId.js';

export type SessionCreateParams = {
/**
 * Reuse an existing Agent identity in a new task; omission allocates a new identity.
 */
agentId?: AgentId | null, agent: AgentRoleSelection, commandId: CommandId, title: string, };
