// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { Session } from './Session.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnStartResult } from './TurnStartResult.js';

export type SessionRewriteResult = { session: Session, threadId: ThreadId, turn: TurnStartResult, };
