// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { Thread } from './Thread.js';
import type { ThreadTranscriptSnapshot } from './ThreadTranscriptSnapshot.js';
import type { ThreadUpdateEnvelope } from './ThreadUpdateEnvelope.js';

export type SessionThreadProjection = { thread: Thread, transcript: ThreadTranscriptSnapshot, updates: Array<ThreadUpdateEnvelope>, };
