// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type SessionManagerStatus = "idle" | "needsInput" | "working" | "readyForReview" | "completed" | "failed" | "stopped";
