// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentTreeProjection } from './AgentTreeProjection.js';
import type { Session } from './Session.js';
import type { SessionThreadProjection } from './SessionThreadProjection.js';

export type SessionSubscribeResult = { session: Session, threadProjections: Array<SessionThreadProjection>, agentTree: AgentTreeProjection, };
