// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { SessionManagerInfo } from './SessionManagerInfo.js';
import type { SessionStatus } from './SessionStatus.js';
import type { SessionThread } from './SessionThread.js';

export type Session = { sessionId: SessionId, title: string, status: SessionStatus, manager: SessionManagerInfo, threads: Array<SessionThread>, };
