// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { AgentResponse } from './AgentResponse.js';
import type { ApprovalMode } from './ApprovalMode.js';
import type { InputItem } from './InputItem.js';
import type { ItemId } from './ItemId.js';
import type { MessageBoundary } from './MessageBoundary.js';
import type { RequestId } from './RequestId.js';
import type { ReviewTarget } from './ReviewTarget.js';
import type { ThreadId } from './ThreadId.js';
import type { ToolMode } from './ToolMode.js';
import type { TurnId } from './TurnId.js';

export type SessionRequest = { "type": "archive" } | { "type": "restore" } | { "type": "delete" } | { "type": "stop" } | { "type": "createThread", agentId?: AgentId | null, title: string, } | { "type": "replaceThread", sourceThreadId: ThreadId, title: string, } | { "type": "restoreMessage", threadId: ThreadId, itemId: ItemId, boundary: MessageBoundary, title: string, } | { "type": "forkThread", parentThreadId: ThreadId, title: string, } | { "type": "rewindThread", parentThreadId: ThreadId, beforeTurnId: TurnId, title: string, } | { "type": "rewriteThread", parentThreadId: ThreadId, beforeTurnId: TurnId, title: string, toolMode?: ToolMode | null, input: Array<InputItem>, } | { "type": "startTurn", threadId: ThreadId, expectedSequence: number, approvalMode: ApprovalMode, toolMode?: ToolMode | null, input: Array<InputItem>, } | { "type": "startReview", threadId: ThreadId, expectedSequence: number, target: ReviewTarget, } | { "type": "startShellTurn", threadId: ThreadId, expectedSequence: number, approvalMode: ApprovalMode, command: string, workingDirectory: string, } | { "type": "compactContext", threadId: ThreadId, expectedSequence: number, retentionPrompt?: string | null, } | { "type": "steerTurn", threadId: ThreadId, expectedSequence: number, turnId: TurnId, input: Array<InputItem>, } | { "type": "interruptTurn", threadId: ThreadId, expectedSequence: number, turnId: TurnId, } | { "type": "resolveInteraction", threadId: ThreadId, expectedSequence: number, turnId: TurnId, requestId: RequestId, response: AgentResponse, };
