// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionManagerActivity } from './SessionManagerActivity.js';
import type { SessionManagerStatus } from './SessionManagerStatus.js';

export type SessionManagerInfo = { status: SessionManagerStatus, statusChangedAtUnixMs: number, activity?: SessionManagerActivity | null, summary?: string | null, };
