// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { SkillCatalogReloadDto } from './SkillCatalogReloadDto.js';

export type SkillListParams = { reload: SkillCatalogReloadDto, sessionId?: SessionId, };
