// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';
import type { SkillCompatibilityDto } from './SkillCompatibilityDto.js';
import type { SkillEnablementDto } from './SkillEnablementDto.js';
import type { SkillId } from './SkillId.js';
import type { SkillSourceKindDto } from './SkillSourceKindDto.js';

export type SkillDto = { id: SkillId, description: string, sourceKind: SkillSourceKindDto, contentDigest: ContentDigest, enablement: SkillEnablementDto, compatibility: SkillCompatibilityDto, };
