// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';

export type SkillSourceRemoveParams = { commandId: CommandId, expectedRevision: number, sourceId: string, };
