// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SkillDiagnosticDto } from './SkillDiagnosticDto.js';
import type { SkillDto } from './SkillDto.js';

export type SkillListResult = { generation: number, skills: Array<SkillDto>, diagnostics: Array<SkillDiagnosticDto>, };
