// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SkillDiagnosticCodeDto } from './SkillDiagnosticCodeDto.js';

export type SkillDiagnosticDto = { source: string, subject: string | null, code: SkillDiagnosticCodeDto, message: string, };
