// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';

export type SkillVersionSelector = { "type": "followLatest" } | { "type": "pinnedDigest", digest: ContentDigest, };
