// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ResourceMetadataResult } from './ResourceMetadataResult.js';
import type { SkillResourceKindDto } from './SkillResourceKindDto.js';

export type SkillResourceOpenResult = { path: string, kind: SkillResourceKindDto, resource: ResourceMetadataResult, };
