// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ContentDigest } from './ContentDigest.js';
import type { SessionId } from './SessionId.js';
import type { SkillId } from './SkillId.js';

export type SkillResourceOpenParams = { sessionId?: SessionId, skillId: SkillId, skillContentDigest: ContentDigest, path: string, };
