// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { SkillSourceEnablementDto } from './SkillSourceEnablementDto.js';

export type SkillSourceSetEnablementParams = { commandId: CommandId, expectedRevision: number, sourceId: string, enablement: SkillSourceEnablementDto, };
