// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SkillName } from './SkillName.js';
import type { SkillSourceId } from './SkillSourceId.js';

export type SkillId = { source: SkillSourceId, name: SkillName, };
