// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SkillId } from './SkillId.js';
import type { SkillVersionSelector } from './SkillVersionSelector.js';

export type SkillRef = { id: SkillId, version: SkillVersionSelector, };
