// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SlashCommandArgumentModeDto } from './SlashCommandArgumentModeDto.js';

export type SlashCommandDefinition = { name: string, description: string, argumentMode: SlashCommandArgumentModeDto, };
