// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SyntaxLanguageDto } from './SyntaxLanguageDto.js';

export type SyntaxAnalyzeParams = { language: SyntaxLanguageDto, revision: number, text: string, };
