// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SyntaxDiagnosticKindDto } from './SyntaxDiagnosticKindDto.js';
import type { SyntaxRangeDto } from './SyntaxRangeDto.js';

export type SyntaxDiagnosticDto = { range: SyntaxRangeDto, kind: SyntaxDiagnosticKindDto, };
