// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type SyntaxLanguageDto = "javascript" | "javascriptreact" | "json" | "jsonc" | "rust" | "shell" | "typescript" | "typescriptreact";
