// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { TerminalProfile } from './TerminalProfile.js';

export type TerminalProfileListResult = { profiles: Array<TerminalProfile>, };
