// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { TerminalReconnectLease } from './TerminalReconnectLease.js';

export type TerminalAttachResult = { terminalId: string, reconnect: TerminalReconnectLease, };
