// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { TerminalCommandStatusEvent } from './TerminalCommandStatusEvent.js';
import type { TerminalOutputChunk } from './TerminalOutputChunk.js';

export type TerminalReadResult = { terminalId: string, chunks: Array<TerminalOutputChunk>, nextSequence: number, outputGap: boolean, commandEvents: Array<TerminalCommandStatusEvent>, nextCommandSequence: number, commandEventGap: boolean, exited: boolean, exitCode: number | null, };
