// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { TerminalProfile } from './TerminalProfile.js';
import type { TerminalReconnectLease } from './TerminalReconnectLease.js';

export type TerminalCreateResult = { terminalId: string, profile: TerminalProfile, reconnect: TerminalReconnectLease | null, };
