// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type TerminalAttachParams = { dirId?: string, terminalId: string, reconnectToken: string, rows: number, cols: number, };
