// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ThreadTranscriptEntry } from './ThreadTranscriptEntry.js';

export type ThreadTranscriptChange = { "type": "upsert", entry: ThreadTranscriptEntry, } | { "type": "remove", entryIds: Array<string>, } | { "type": "clearTransient" };
