// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ContentPart } from './ContentPart.js';
import type { ImageAttachmentRef } from './ImageAttachmentRef.js';
import type { ItemId } from './ItemId.js';
import type { ToolCallBinding } from './ToolCallBinding.js';
import type { ToolCallId } from './ToolCallId.js';
import type { ToolName } from './ToolName.js';
import type { TurnId } from './TurnId.js';

export type ThreadItem = { "type": "userMessage", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "userContext", itemId: ItemId, turnId: TurnId, name: string, content: string, } | { "type": "userImage", itemId: ItemId, turnId: TurnId, url: string, } | { "type": "userImageAttachment", itemId: ItemId, turnId: TurnId, attachment: ImageAttachmentRef, } | { "type": "agentMessage", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "reasoning", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "plan", itemId: ItemId, turnId: TurnId, text: string, } | { "type": "toolCall", itemId: ItemId, turnId: TurnId, toolCallId: ToolCallId, name: ToolName, argumentsJson: string, binding?: ToolCallBinding | null, } | { "type": "toolResult", itemId: ItemId, turnId: TurnId, toolCallId: ToolCallId, text: string, content?: Array<ContentPart> | null, isError: boolean, };
