// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';
import type { ThreadTranscriptEntry } from './ThreadTranscriptEntry.js';

export type ThreadTranscriptSnapshot = { sessionId: SessionId, threadId: ThreadId, durableSequence: number, revision: number, entries: Array<ThreadTranscriptEntry>, };
