// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ThreadGoalStatus } from './ThreadGoalStatus.js';
import type { ThreadId } from './ThreadId.js';

export type ThreadGoal = { threadId: ThreadId, goalId: string, objective: string, status: ThreadGoalStatus, tokenBudget?: number | null, tokensUsed: number, };
