// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { AgentId } from './AgentId.js';
import type { ModelReferenceCostSummary } from './ModelReferenceCostSummary.js';
import type { ModelUsageSummary } from './ModelUsageSummary.js';
import type { SessionId } from './SessionId.js';
import type { ThreadGoal } from './ThreadGoal.js';
import type { ThreadId } from './ThreadId.js';
import type { ThreadOrigin } from './ThreadOrigin.js';
import type { ThreadStatus } from './ThreadStatus.js';
import type { Turn } from './Turn.js';

export type Thread = { agentId: AgentId, origin: ThreadOrigin, sessionId: SessionId, threadId: ThreadId, parentThreadId?: ThreadId | null, forkedFromId?: ThreadId | null, title: string, status: ThreadStatus, sequence: number, usage: ModelUsageSummary, referenceCost: ModelReferenceCostSummary, goal?: ThreadGoal | null, turns: Array<Turn>, };
