// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export type ThreadWorktreeRepositoryBindingDto = { repositoryId: string, targetBranch?: string, baselineObjectId?: string, };
