// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ThreadWorktreeRepositoryBindingDto } from './ThreadWorktreeRepositoryBindingDto.js';

export type ThreadDirBinding = { managedWorktreeId: string, sourceDirId: string, repositories: Array<ThreadWorktreeRepositoryBindingDto>, baselineSummary: string, };
