// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ThreadGoalStatus } from './ThreadGoalStatus.js';
import type { ThreadId } from './ThreadId.js';

export type ThreadGoalSetParams = { threadId: ThreadId, objective?: string | null, status?: ThreadGoalStatus | null, tokenBudget?: number | null, };
