// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { TurnId } from './TurnId.js';

export type ThreadHistoryBoundary = { hasOlderTurns: boolean, oldestTurnId?: TurnId | null, };
