// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ThreadGoal } from './ThreadGoal.js';
import type { ThreadId } from './ThreadId.js';
import type { TurnId } from './TurnId.js';

export type ThreadGoalUpdatedNotification = { threadId: ThreadId, turnId?: TurnId | null, goal: ThreadGoal, };
