// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { SessionId } from './SessionId.js';
import type { StreamCursor } from './StreamCursor.js';
import type { ThreadId } from './ThreadId.js';
import type { ThreadUpdate } from './ThreadUpdate.js';

export type ThreadUpdateEnvelope = { sessionId: SessionId, threadId: ThreadId, durableSequence: number, streamCursor?: StreamCursor | null, update: ThreadUpdate, };
