// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { TurnId } from './TurnId.js';

export type ThreadSnapshotHistory = { "type": "latest", turnLimit: number, } | { "type": "before", turnId: TurnId, turnLimit: number, };
