// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ModelRef } from './ModelRef.js';

export type ToolSearchEmbeddingStatusDto = { "type": "disabled" } | { "type": "ready", model: ModelRef, } | { "type": "unavailable", model?: ModelRef | null, reason: string, };
