// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ToolName } from './ToolName.js';

export type ToolProfileSnapshot = { id: string, revision: string, definitionDigest: string, toolNames: Array<ToolName>, parallelToolCalls: boolean, };
