// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ModelRef } from './ModelRef.js';
import type { ToolSearchEmbeddingStatusDto } from './ToolSearchEmbeddingStatusDto.js';
import type { ToolSearchModeDto } from './ToolSearchModeDto.js';

export type ToolSearchConfigDto = { mode: ToolSearchModeDto, embeddingModel?: ModelRef | null, embeddingStatus: ToolSearchEmbeddingStatusDto, };
