// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { CommandId } from './CommandId.js';
import type { ModelRef } from './ModelRef.js';
import type { ToolSearchModeDto } from './ToolSearchModeDto.js';

export type ToolSearchConfigureParams = { commandId: CommandId, expectedRevision: number, mode: ToolSearchModeDto, embeddingModel?: ModelRef | null, };
