// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ChangeSetId } from './ChangeSetId.js';
import type { CommandId } from './CommandId.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';

export type TurnChangesMutationParams = { commandId: CommandId, sessionId: SessionId, threadId: ThreadId, changeSetId: ChangeSetId, expectedRevision: number, };
