// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { TurnChangeSetSummary } from './TurnChangeSetSummary.js';

export type TurnChangesMutationResult = { changeSets: Array<TurnChangeSetSummary>, };
