// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { TurnChangeFileDto } from './TurnChangeFileDto.js';
import type { TurnChangeSetSummary } from './TurnChangeSetSummary.js';

export type TurnChangesReadResult = { summary: TurnChangeSetSummary, files: Array<TurnChangeFileDto>, generatedMessage?: string, draftMessage?: string, };
