// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ChangeSetId } from './ChangeSetId.js';
import type { SessionId } from './SessionId.js';
import type { ThreadId } from './ThreadId.js';

export type TurnChangesReadFileParams = { sessionId: SessionId, threadId: ThreadId, changeSetId: ChangeSetId, path: string, };
