// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ApprovalMode } from './ApprovalMode.js';
import type { ModelContextUsage } from './ModelContextUsage.js';
import type { ModelRef } from './ModelRef.js';
import type { ModelUsageSummary } from './ModelUsageSummary.js';
import type { PendingInteraction } from './PendingInteraction.js';
import type { PlanUpdate } from './PlanUpdate.js';
import type { StableTurnError } from './StableTurnError.js';
import type { ThreadItem } from './ThreadItem.js';
import type { ToolMode } from './ToolMode.js';
import type { ToolProfileSnapshot } from './ToolProfileSnapshot.js';
import type { TurnId } from './TurnId.js';
import type { TurnInstructions } from './TurnInstructions.js';
import type { TurnKind } from './TurnKind.js';
import type { TurnStatus } from './TurnStatus.js';

export type Turn = { turnId: TurnId, status: TurnStatus, kind: TurnKind,
/**
 * Exact instructions frozen when this Turn was accepted.
 *
 * Historical Turns written before instruction snapshots were introduced omit this field.
 */
instructions?: TurnInstructions | null, model?: ModelRef | null, toolProfile?: ToolProfileSnapshot | null, toolMode: ToolMode, approvalMode: ApprovalMode, usage: ModelUsageSummary, contextUsage?: ModelContextUsage | null, items: Array<ThreadItem>, plan?: PlanUpdate | null, pendingInteraction?: PendingInteraction | null, error?: StableTurnError | null, };
