// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ThreadDirBinding } from './ThreadDirBinding.js';
import type { TurnChangeSetSummary } from './TurnChangeSetSummary.js';

export type TurnChangesListResult = { dir?: ThreadDirBinding, changeSets: Array<TurnChangeSetSummary>, };
