// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { ResourceMetadataResult } from './ResourceMetadataResult.js';
import type { TypstDiagnosticDto } from './TypstDiagnosticDto.js';

export type TypstCompileResult = { "status": "success", resource: ResourceMetadataResult, warnings: Array<TypstDiagnosticDto>, } | { "status": "failed", diagnostics: Array<TypstDiagnosticDto>, };
