// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { UsageEvent } from './UsageEvent.js';

export type UsageSnapshot = { enabled: boolean, counts: { [key in UsageEvent]?: number }, };
