// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { UserInputOption } from './UserInputOption.js';

export type UserInputQuestion = { id: string, header: string, question: string, options?: Array<UserInputOption>, allowFreeForm: boolean, };
