// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
import type { RepositoryCheckpoint } from './RepositoryCheckpoint.js';

export type WorkspaceCheckpoint = { "type": "noFiles" } | { "type": "git", sourceDirId: string, repositories: Array<RepositoryCheckpoint>, } | { "type": "unavailable", reason: string, };
