[package]
name = "ash-connectors-extension"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_connectors_extension"
path = "src/lib.rs"

[dependencies]
file-system = { package = "ash-file-system", path = "../../file-system" }
base64 = { workspace = true }
getrandom = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }
zeroize = { workspace = true }
ash-http-client = { workspace = true }
ash-core-plugins = { workspace = true }
ash-plugin = { workspace = true }
ash-secrets = { workspace = true }
ash-state = { workspace = true }
ash-tools = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }


[lints]
workspace = true
