import type { LanguagePackCatalog } from "../../../../platform/languagePacks/common/languagePacksService.js";
import { ZETA_LOCALIZATION_CATALOG_VERSION } from "../../../../platform/languagePacks/common/languagePackContract.js";

const english: LanguagePackCatalog = {
	schemaVersion: 1,
	locale: "en",
	languageName: "English",
	localizedLanguageName: "English",
	catalogVersion: ZETA_LOCALIZATION_CATALOG_VERSION,
	bundles: {
		"zeta.menu": {
			file: "File",
			edit: "Edit",
			selection: "Selection",
			view: "View",
			go: "Go",
			run: "Run",
			terminal: "Terminal",
			help: "Help",
		},
		"zeta.actions": {
			showPrimarySidebar: "Show Primary Side Bar",
			hidePrimarySidebar: "Hide Primary Side Bar",
			showSecondarySidebar: "Show Secondary Side Bar",
			hideSecondarySidebar: "Hide Secondary Side Bar",
			showPanel: "Show Panel",
			hidePanel: "Hide Panel",
			maximizePanel: "Maximize Panel",
			restoreEditorArea: "Restore Editor Area",
			closePanel: "Close Panel",
		},
		"zeta.views": {
			explorer: "Explorer",
			search: "Search",
			git: "Git",
			changes: "Changes",
			agentReview: "Agent Review",
			graph: "Graph",
			chat: "Chat",
			agent: "Agent",
			agentSessions: "Agent Sessions",
			problems: "Problems",
			output: "Output",
			terminal: "Terminal",
			testing: "Testing",
			tasks: "Tasks",
			runAndDebug: "Run and Debug",
			debugConsole: "Debug Console",
			ports: "Ports",
			refactorPreview: "Refactor Preview",
		},
		"zeta.regions": {
			primarySidebar: "Primary sidebar",
			primarySidebarViews: "Primary side bar views",
			agentSidebar: "Agent sidebar",
			agentSidebarViews: "Agent sidebar views",
			auxiliarySidebar: "Auxiliary sidebar",
			auxiliarySidebarViews: "Auxiliary sidebar views",
			panel: "Panel",
			panelViews: "Panel views",
			additionalViews: "Additional views",
			applicationMenu: "Application menu",
			editor: "Editor",
			editorActions: "Editor actions",
			openEditors: "Open editors",
			editorShortcuts: "Editor shortcuts",
		},
		"zeta.marketplace": {
			searchMarketplace: "Search Marketplace",
			searchLanguageExtensions: "Search language extensions",
			searchPackages: "Search Plugins, Skills, MCPs…",
			browse: "Browse Marketplace",
			packageTypes: "Marketplace package types",
			filterAll: "All",
			filterPlugins: "Plugins",
			filterMcps: "MCPs",
			filterSkills: "Skills",
			filterLanguages: "Languages",
			filterLocalization: "Localization",
			filterThemes: "Themes",
			loading: "Loading Marketplace…",
			unavailable: "Marketplace unavailable.",
			noMatching: "No matching packages.",
			packageCount: "{count} package",
			packageCountPlural: "{count} packages",
			noTypeFound: "No {type} packages found",
			explore: "Explore Marketplace packages",
			tryDifferent: "Try a different search or clear the current filters.",
			installDescription: "Install Plugins, Skills, MCP servers, language support, and themes from the signed catalog.",
			clearFilters: "Clear filters",
			installed: "Installed · activation is separate",
			removalPending: "Removal pending",
			available: "Available",
			install: "Install",
			uninstall: "Uninstall",
			officialMcp: "Listed in the official MCP Registry · {name}@{version}",
			official: "Marketplace official package",
			thirdParty: "Third-party package",
			operationFailed: "Marketplace operation failed.",
		},
		"zeta.settings": {
			"chrome.search": "Search settings",
			"chrome.categories": "Settings categories",
			"chrome.noResults": "No settings found.",
			"chrome.modalTitle": "Zeta Settings",
			"displayLanguage.title": "Display Language",
			"displayLanguage.description": "Choose the language used by the Zeta interface.",
			"displayLanguage.restart": "Some interface areas update after reopening Settings.",
			"displayLanguage.builtin": "Built-in",
			"displayLanguage.marketplace": "Marketplace",
			"displayLanguage.installMore": "Install more languages from Marketplace",
			"displayLanguage.loading": "Loading available languages…",
			"displayLanguage.unavailable": "Marketplace language packs are unavailable.",
			"displayLanguage.install": "Install",
			"displayLanguage.installed": "Installed",
			"displayLanguage.select": "Interface language",
			"categories.general.label": "General",
			"categories.general.description": "Configure core application behavior and accessibility.",
			"categories.appearance.label": "Appearance",
			"categories.appearance.description": "Customize the visual appearance of Zeta.",
			"categories.editor.label": "Editor",
			"categories.editor.description": "Configure text editing, fonts, search, and diff behavior.",
		},
	},
};

const chinese: LanguagePackCatalog = {
	schemaVersion: 1,
	locale: "zh-CN",
	languageName: "Chinese (Simplified)",
	localizedLanguageName: "简体中文",
	catalogVersion: ZETA_LOCALIZATION_CATALOG_VERSION,
	bundles: {
		"zeta.menu": {
			file: "文件",
			edit: "编辑",
			selection: "选择",
			view: "查看",
			go: "转到",
			run: "运行",
			terminal: "终端",
			help: "帮助",
		},
		"zeta.actions": {
			showPrimarySidebar: "显示主侧栏",
			hidePrimarySidebar: "隐藏主侧栏",
			showSecondarySidebar: "显示辅助侧栏",
			hideSecondarySidebar: "隐藏辅助侧栏",
			showPanel: "显示面板",
			hidePanel: "隐藏面板",
			maximizePanel: "最大化面板",
			restoreEditorArea: "恢复编辑器区域",
			closePanel: "关闭面板",
		},
		"zeta.views": {
			explorer: "资源管理器",
			search: "搜索",
			git: "Git",
			changes: "更改",
			agentReview: "Agent 审查",
			graph: "图表",
			chat: "聊天",
			agent: "Agent",
			agentSessions: "Agent 会话",
			problems: "问题",
			output: "输出",
			terminal: "终端",
			testing: "测试",
			tasks: "任务",
			runAndDebug: "运行和调试",
			debugConsole: "调试控制台",
			ports: "端口",
			refactorPreview: "重构预览",
		},
		"zeta.regions": {
			primarySidebar: "主侧栏",
			primarySidebarViews: "主侧栏视图",
			agentSidebar: "Agent 侧栏",
			agentSidebarViews: "Agent 侧栏视图",
			auxiliarySidebar: "辅助侧栏",
			auxiliarySidebarViews: "辅助侧栏视图",
			panel: "面板",
			panelViews: "面板视图",
			additionalViews: "其他视图",
			applicationMenu: "应用程序菜单",
			editor: "编辑器",
			editorActions: "编辑器操作",
			openEditors: "打开的编辑器",
			editorShortcuts: "编辑器快捷方式",
		},
		"zeta.marketplace": {
			searchMarketplace: "搜索 Marketplace",
			searchLanguageExtensions: "搜索语言扩展",
			searchPackages: "搜索插件、技能、MCP…",
			browse: "浏览 Marketplace",
			packageTypes: "Marketplace 软件包类型",
			filterAll: "全部",
			filterPlugins: "插件",
			filterMcps: "MCP",
			filterSkills: "技能",
			filterLanguages: "语言",
			filterLocalization: "界面语言",
			filterThemes: "主题",
			loading: "正在加载 Marketplace…",
			unavailable: "Marketplace 暂不可用。",
			noMatching: "没有匹配的软件包。",
			packageCount: "{count} 个软件包",
			packageCountPlural: "{count} 个软件包",
			noTypeFound: "未找到 {type} 软件包",
			explore: "探索 Marketplace 软件包",
			tryDifferent: "请尝试其他搜索词，或清除当前筛选条件。",
			installDescription: "从已签名目录安装插件、技能、MCP 服务、语言支持和主题。",
			clearFilters: "清除筛选条件",
			installed: "已安装 · 需单独激活",
			removalPending: "等待移除",
			available: "可安装",
			install: "安装",
			uninstall: "卸载",
			officialMcp: "已列入官方 MCP Registry · {name}@{version}",
			official: "Marketplace 官方软件包",
			thirdParty: "第三方软件包",
			operationFailed: "Marketplace 操作失败。",
		},
		"zeta.settings": {
			"chrome.search": "搜索设置",
			"chrome.categories": "设置类别",
			"chrome.noResults": "未找到设置。",
			"chrome.modalTitle": "Zeta 设置",
			"displayLanguage.title": "显示语言",
			"displayLanguage.description": "选择 Zeta 界面使用的语言。",
			"displayLanguage.restart": "部分界面将在重新打开设置后更新。",
			"displayLanguage.builtin": "内置",
			"displayLanguage.marketplace": "Marketplace",
			"displayLanguage.installMore": "从 Marketplace 安装更多语言",
			"displayLanguage.loading": "正在加载可用语言…",
			"displayLanguage.unavailable": "Marketplace 语言包暂时不可用。",
			"displayLanguage.install": "安装",
			"displayLanguage.installed": "已安装",
			"displayLanguage.select": "界面语言",
			"categories.general.label": "常规",
			"categories.general.description": "配置应用核心行为和辅助功能。",
			"categories.appearance.label": "外观",
			"categories.appearance.description": "自定义 Zeta 的视觉外观。",
			"categories.editor.label": "编辑器",
			"categories.editor.description": "配置文本编辑、字体、搜索和差异显示。",
		},
	},
};

export const builtinLanguagePackCatalogs: readonly LanguagePackCatalog[] = [english, chinese];
