import type { LanguagePackCatalog } from "../../../../platform/languagePacks/common/languagePacksService.js";
import { ZETA_LOCALIZATION_CATALOG_VERSION } from "../../../../platform/languagePacks/common/languagePackContract.js";

const english: LanguagePackCatalog = {
	schemaVersion: 1,
	locale: "en",
	languageName: "English",
	localizedLanguageName: "English",
	catalogVersion: ZETA_LOCALIZATION_CATALOG_VERSION,
	bundles: {
		"zeta.menu": {
			file: "File",
			edit: "Edit",
			selection: "Selection",
			view: "View",
			go: "Go",
			run: "Run",
			terminal: "Terminal",
			help: "Help",
		},
		"zeta.actions": {
			showPrimarySidebar: "Show Primary Side Bar",
			hidePrimarySidebar: "Hide Primary Side Bar",
			showSecondarySidebar: "Show Secondary Side Bar",
			hideSecondarySidebar: "Hide Secondary Side Bar",
			showPanel: "Show Panel",
			hidePanel: "Hide Panel",
			maximizePanel: "Maximize Panel",
			restoreEditorArea: "Restore Editor Area",
			closePanel: "Close Panel",
		},
		"zeta.views": {
			explorer: "Explorer",
			search: "Search",
			git: "Git",
			changes: "Changes",
			agentReview: "Agent Review",
			graph: "Graph",
			chat: "Chat",
			agent: "Agent",
			agentSessions: "Agent Sessions",
			problems: "Problems",
			output: "Output",
			terminal: "Terminal",
			testing: "Testing",
			tasks: "Tasks",
			runAndDebug: "Run and Debug",
			debugConsole: "Debug Console",
			ports: "Ports",
			refactorPreview: "Refactor Preview",
		},
		"zeta.regions": {
			primarySidebar: "Primary sidebar",
			primarySidebarViews: "Primary side bar views",
			agentSidebar: "Agent sidebar",
			agentSidebarViews: "Agent sidebar views",
			auxiliarySidebar: "Auxiliary sidebar",
			auxiliarySidebarViews: "Auxiliary sidebar views",
			panel: "Panel",
			panelViews: "Panel views",
			additionalViews: "Additional views",
			applicationMenu: "Application menu",
			editor: "Editor",
			editorActions: "Editor actions",
			openEditors: "Open editors",
			editorShortcuts: "Editor shortcuts",
		},
		"zeta.marketplace": {
			searchMarketplace: "Search Marketplace",
			searchLanguageExtensions: "Search language extensions",
			searchPackages: "Search Plugins, Skills, MCPs…",
			browse: "Browse Marketplace",
			packageTypes: "Marketplace package types",
			filterAll: "All",
			filterPlugins: "Plugins",
			filterMcps: "MCPs",
			filterSkills: "Skills",
			filterLanguages: "Languages",
			filterLocalization: "Localization",
			filterThemes: "Themes",
			loading: "Loading Marketplace…",
			unavailable: "Marketplace unavailable.",
			noMatching: "No matching packages.",
			packageCount: "{count} package",
			packageCountPlural: "{count} packages",
			noTypeFound: "No {type} packages found",
			explore: "Explore Marketplace packages",
			tryDifferent: "Try a different search or clear the current filters.",
			installDescription: "Install Plugins, Skills, MCP servers, language support, and themes from the signed catalog.",
			clearFilters: "Clear filters",
			installed: "Installed · activation is separate",
			removalPending: "Removal pending",
			available: "Available",
			install: "Install",
			uninstall: "Uninstall",
			officialMcp: "Listed in the official MCP Registry · {name}@{version}",
			official: "Marketplace official package",
			thirdParty: "Third-party package",
			operationFailed: "Marketplace operation failed.",
		},
		"zeta.settings": {
			"chrome.search": "Search settings",
			"chrome.categories": "Settings categories",
			"chrome.noResults": "No settings found.",
			"chrome.modalTitle": "Zeta Settings",
			"displayLanguage.title": "Display Language",
			"displayLanguage.description": "Choose the language used by the Zeta interface.",
			"displayLanguage.restart": "Some interface areas update after reopening Settings.",
			"displayLanguage.builtin": "Built-in",
			"displayLanguage.marketplace": "Marketplace",
			"displayLanguage.installMore": "Install more languages from Marketplace",
			"displayLanguage.loading": "Loading available languages…",
			"displayLanguage.unavailable": "Marketplace language packs are unavailable.",
			"displayLanguage.install": "Install",
			"displayLanguage.installed": "Installed",
			"displayLanguage.select": "Interface language",
			"sections.general.label": "General",
			"sections.general.description": "Configure core application behavior and defaults.",
			"sections.chat.label": "Chat",
			"sections.chat.description": "Configure chat behavior, conversations, and presentation.",
			"sections.user.label": "User",
			"sections.user.description": "Manage your identity, account, and user-level preferences.",
			"sections.workspace-trust.label": "Workspace Trust",
			"sections.workspace-trust.description": "Review and revoke folders that are allowed to run workspace capabilities.",
			"sections.appearance.label": "Appearance",
			"sections.appearance.description": "Customize the visual appearance of Zeta.",
			"sections.editor.label": "Editor",
			"sections.editor.description": "Configure text editing, fonts, and editor behavior.",
			"sections.languages.label": "Languages",
			"sections.languages.description": "Discover and manage Marketplace language extensions.",
			"sections.localization.label": "Display Language",
			"sections.localization.description": "Choose the language used by the Zeta interface.",
			"groups.agents.label": "Agents",
			"groups.agents.description": "Create agents and teams, then configure their shared capabilities.",
			"sections.agents.label": "My Agents",
			"sections.agents.description": "Create, select, and configure reusable agents.",
			"sections.teams.label": "Teams",
			"sections.teams.description": "Compose reusable teams of agents and define how they collaborate.",
			"sections.agent-defaults.label": "Defaults",
			"sections.agent-defaults.description": "Choose the default agent and shared execution behavior.",
			"sections.models.label": "Models",
			"sections.models.description": "Choose models and configure model-specific behavior.",
			"sections.git.label": "Git",
			"sections.git.description": "Configure source control and Git workflows.",
			"sections.worktrees.label": "Worktrees",
			"sections.worktrees.description": "Manage worktree creation, placement, and lifecycle.",
			"sections.marketplace.label": "Marketplace",
			"sections.marketplace.description": "Discover and install packages without exposing Marketplace internals to Zeta.",
			"sections.plugins.label": "Plugins",
			"sections.plugins.description": "Manage installed plugins and plugin behavior.",
			"sections.connectors.label": "Connectors",
			"sections.connectors.description": "Connect external accounts whose capabilities are provided by plugins.",
			"sections.rules.label": "Rules",
			"sections.rules.description": "Configure the instructions and rules agents follow.",
			"sections.skills.label": "Skills",
			"sections.skills.description": "Manage reusable skills that agents can activate.",
			"sections.tools-and-mcps.label": "Tools & MCPs",
			"sections.tools-and-mcps.description": "Configure tools and Model Context Protocol connections.",
			"sections.hooks.label": "Hooks",
			"sections.hooks.description": "Configure automated actions around workflow events.",
			"sections.browser.label": "Browser",
			"sections.browser.description": "Configure browser behavior and web interactions.",
			"sections.tabs.label": "Tabs",
			"sections.tabs.description": "Customize tab behavior and organization.",
			"sections.indexing.label": "Indexing",
			"sections.indexing.description": "Control Agent tool discovery and workspace semantic search.",
			"sections.experimental.label": "Experimental",
			"sections.experimental.description": "Try features that are still under development.",
			"sections.documentation.label": "Documentation",
			"sections.documentation.description": "Configure documentation sources and related behavior.",
		},
	},
};

const chinese: LanguagePackCatalog = {
	schemaVersion: 1,
	locale: "zh-CN",
	languageName: "Chinese (Simplified)",
	localizedLanguageName: "简体中文",
	catalogVersion: ZETA_LOCALIZATION_CATALOG_VERSION,
	bundles: {
		"zeta.menu": {
			file: "文件",
			edit: "编辑",
			selection: "选择",
			view: "查看",
			go: "转到",
			run: "运行",
			terminal: "终端",
			help: "帮助",
		},
		"zeta.actions": {
			showPrimarySidebar: "显示主侧栏",
			hidePrimarySidebar: "隐藏主侧栏",
			showSecondarySidebar: "显示辅助侧栏",
			hideSecondarySidebar: "隐藏辅助侧栏",
			showPanel: "显示面板",
			hidePanel: "隐藏面板",
			maximizePanel: "最大化面板",
			restoreEditorArea: "恢复编辑器区域",
			closePanel: "关闭面板",
		},
		"zeta.views": {
			explorer: "资源管理器",
			search: "搜索",
			git: "Git",
			changes: "更改",
			agentReview: "Agent 审查",
			graph: "图表",
			chat: "聊天",
			agent: "Agent",
			agentSessions: "Agent 会话",
			problems: "问题",
			output: "输出",
			terminal: "终端",
			testing: "测试",
			tasks: "任务",
			runAndDebug: "运行和调试",
			debugConsole: "调试控制台",
			ports: "端口",
			refactorPreview: "重构预览",
		},
		"zeta.regions": {
			primarySidebar: "主侧栏",
			primarySidebarViews: "主侧栏视图",
			agentSidebar: "Agent 侧栏",
			agentSidebarViews: "Agent 侧栏视图",
			auxiliarySidebar: "辅助侧栏",
			auxiliarySidebarViews: "辅助侧栏视图",
			panel: "面板",
			panelViews: "面板视图",
			additionalViews: "其他视图",
			applicationMenu: "应用程序菜单",
			editor: "编辑器",
			editorActions: "编辑器操作",
			openEditors: "打开的编辑器",
			editorShortcuts: "编辑器快捷方式",
		},
		"zeta.marketplace": {
			searchMarketplace: "搜索 Marketplace",
			searchLanguageExtensions: "搜索语言扩展",
			searchPackages: "搜索插件、技能、MCP…",
			browse: "浏览 Marketplace",
			packageTypes: "Marketplace 软件包类型",
			filterAll: "全部",
			filterPlugins: "插件",
			filterMcps: "MCP",
			filterSkills: "技能",
			filterLanguages: "语言",
			filterLocalization: "界面语言",
			filterThemes: "主题",
			loading: "正在加载 Marketplace…",
			unavailable: "Marketplace 暂不可用。",
			noMatching: "没有匹配的软件包。",
			packageCount: "{count} 个软件包",
			packageCountPlural: "{count} 个软件包",
			noTypeFound: "未找到 {type} 软件包",
			explore: "探索 Marketplace 软件包",
			tryDifferent: "请尝试其他搜索词，或清除当前筛选条件。",
			installDescription: "从已签名目录安装插件、技能、MCP 服务、语言支持和主题。",
			clearFilters: "清除筛选条件",
			installed: "已安装 · 需单独激活",
			removalPending: "等待移除",
			available: "可安装",
			install: "安装",
			uninstall: "卸载",
			officialMcp: "已列入官方 MCP Registry · {name}@{version}",
			official: "Marketplace 官方软件包",
			thirdParty: "第三方软件包",
			operationFailed: "Marketplace 操作失败。",
		},
		"zeta.settings": {
			"chrome.search": "搜索设置",
			"chrome.categories": "设置类别",
			"chrome.noResults": "未找到设置。",
			"chrome.modalTitle": "Zeta 设置",
			"displayLanguage.title": "显示语言",
			"displayLanguage.description": "选择 Zeta 界面使用的语言。",
			"displayLanguage.restart": "部分界面将在重新打开设置后更新。",
			"displayLanguage.builtin": "内置",
			"displayLanguage.marketplace": "Marketplace",
			"displayLanguage.installMore": "从 Marketplace 安装更多语言",
			"displayLanguage.loading": "正在加载可用语言…",
			"displayLanguage.unavailable": "Marketplace 语言包暂时不可用。",
			"displayLanguage.install": "安装",
			"displayLanguage.installed": "已安装",
			"displayLanguage.select": "界面语言",
			"sections.general.label": "常规",
			"sections.general.description": "配置应用核心行为和默认值。",
			"sections.chat.label": "聊天",
			"sections.chat.description": "配置聊天行为、对话和呈现方式。",
			"sections.user.label": "用户",
			"sections.user.description": "管理身份、账户和用户级偏好。",
			"sections.workspace-trust.label": "工作区信任",
			"sections.workspace-trust.description": "查看和撤销允许运行工作区能力的文件夹。",
			"sections.appearance.label": "外观",
			"sections.appearance.description": "自定义 Zeta 的视觉外观。",
			"sections.editor.label": "编辑器",
			"sections.editor.description": "配置文本编辑、字体和编辑器行为。",
			"sections.languages.label": "语言",
			"sections.languages.description": "发现和管理 Marketplace 编程语言扩展。",
			"sections.localization.label": "显示语言",
			"sections.localization.description": "选择 Zeta 界面使用的语言。",
			"groups.agents.label": "Agent",
			"groups.agents.description": "创建 Agent 与团队，并配置它们共享的能力。",
			"sections.agents.label": "我的 Agent",
			"sections.agents.description": "创建、选择和配置可复用的 Agent。",
			"sections.teams.label": "团队",
			"sections.teams.description": "组合可复用的多 Agent 团队并定义协作方式。",
			"sections.agent-defaults.label": "默认设置",
			"sections.agent-defaults.description": "选择默认 Agent 和共享执行行为。",
			"sections.models.label": "模型",
			"sections.models.description": "选择模型并配置模型行为。",
			"sections.git.label": "Git",
			"sections.git.description": "配置源代码管理和 Git 工作流。",
			"sections.worktrees.label": "Worktree",
			"sections.worktrees.description": "管理 Worktree 的创建、位置和生命周期。",
			"sections.marketplace.label": "Marketplace",
			"sections.marketplace.description": "发现和安装软件包，无需让 Zeta 暴露 Marketplace 内部细节。",
			"sections.plugins.label": "插件",
			"sections.plugins.description": "管理已安装的插件及其行为。",
			"sections.connectors.label": "连接器",
			"sections.connectors.description": "连接由插件提供能力的外部账户。",
			"sections.rules.label": "规则",
			"sections.rules.description": "配置 Agent 遵循的指令和规则。",
			"sections.skills.label": "技能",
			"sections.skills.description": "管理 Agent 可激活的可复用技能。",
			"sections.tools-and-mcps.label": "工具与 MCP",
			"sections.tools-and-mcps.description": "配置工具和 Model Context Protocol 连接。",
			"sections.hooks.label": "Hooks",
			"sections.hooks.description": "配置工作流前后的自动化操作。",
			"sections.browser.label": "浏览器",
			"sections.browser.description": "配置浏览器行为和网页交互。",
			"sections.tabs.label": "标签页",
			"sections.tabs.description": "自定义标签页行为和组织方式。",
			"sections.indexing.label": "索引",
			"sections.indexing.description": "控制 Agent 工具发现和工作区语义搜索。",
			"sections.experimental.label": "实验性",
			"sections.experimental.description": "尝试仍在开发中的功能。",
			"sections.documentation.label": "文档",
			"sections.documentation.description": "配置文档来源和相关行为。",
		},
	},
};

export const builtinLanguagePackCatalogs: readonly LanguagePackCatalog[] = [english, chinese];
