[package]
name = "zeta-utils-home-dir"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
readme = "README.md"

[lib]
doctest = false
name = "zeta_utils_home_dir"
path = "src/lib.rs"

[dependencies]
dirs = { workspace = true }
zeta-utils-absolute-path = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
