[package]
name = "zeta-native"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[[bin]]
name = "zeterm"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
unicode-width = { workspace = true }
zeta-app-server-client = { workspace = true }
zeta-app-server-protocol = { workspace = true }
zeta-icons = { workspace = true }
zeta-keybinding = { workspace = true }
zeta-terminal = { workspace = true }
zeta-theme = { workspace = true }
zeta-protocol = { workspace = true }
zeta-renderer = { workspace = true }
zeta-slash-commands = { workspace = true }
zeta-diff = { workspace = true }
zeta-editor = { workspace = true }
zeta-file-search = { workspace = true }
zeta-ui = { workspace = true }
zeta-ui-dispatch = { workspace = true }
zeta-utils-path = { workspace = true }
zeta-utils-pty = { workspace = true }
zeta-wgpu = { workspace = true }
zeta-winit = { workspace = true }
zui = { workspace = true }

[target.'cfg(not(target_os = "android"))'.dependencies]
arboard = { workspace = true }

[lints]
workspace = true
