[package]
name = "zeta-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
name = "zeta_api"
path = "src/lib.rs"

[dependencies]
serde_json = { workspace = true }
zeta-client = { workspace = true }
zeta-http-client = { workspace = true }
zeta-protocol = { workspace = true }

[lints]
workspace = true
