[package]
name = "zeta-workbench-controller"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_workbench_controller"
path = "src/lib.rs"

[dependencies]
zeta-protocol = { workspace = true }
zeta-terminal-workspace = { workspace = true }
zeta-workbench = { workspace = true }
zeta-workbench-host = { workspace = true }
zeta-workbench-ui = { workspace = true }

[lints]
workspace = true
