[package]
name = "ash-memories-extension"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "memories_extension"
path = "src/lib.rs"

[dependencies]
async-utils = { package = "ash-async-utils", path = "../../async-utils" }
extension-api = { package = "ash-extension-api", path = "../extension-api" }
memories = { workspace = true }
protocol = { package = "ash-protocol", path = "../../protocol" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tools = { package = "ash-tools", path = "../../tools" }

[dev-dependencies]
pollster = { workspace = true }
state = { package = "ash-state", path = "../../state" }
tempfile = { workspace = true }

[lints]
workspace = true
