[package]
name = "zeta-image-generation"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false

[dependencies]
image = { workspace = true, features = ["png", "jpeg", "webp"] }
tempfile = { workspace = true }
client = { package = "zeta-client", path = "../../zeta-client" }
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }
http-client = { package = "zeta-http-client", path = "../../http-client" }
async-utils = { package = "zeta-async-utils", path = "../../async-utils" }
extension-api = { package = "zeta-extension-api", path = "../extension-api" }
tools = { package = "zeta-tools", path = "../../tools" }
protocol = { package = "zeta-protocol", path = "../../protocol" }
extension-items = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
