[package]
name = "zeta-code-retrieval"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_code_retrieval"
path = "src/lib.rs"

[dependencies]
thiserror = { workspace = true }
zeta-async-utils = { workspace = true }
zeta-code-index = { workspace = true }
zeta-code-index-cloud = { workspace = true }
zeta-code-index-semantic = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
zeta-model-provider = { workspace = true }
zeta-workspace = { workspace = true }

[lints]
workspace = true
