load("//:defs.bzl", "ash_rust_binary")
load("//bazel/platforms:release_binaries.bzl", "multiplatform_binaries")

ash_rust_binary(
    name = "ash",
    crate_name = "ash",
    crate_root = "src/main.rs",
    deps = [],
)

alias(
    name = "cli",
    actual = ":ash",
)

multiplatform_binaries(name = "ash")
