[package]
name = "ash-cli"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[[bin]]
name = "ash"
path = "src/main.rs"

[dependencies]
ash-utils-home-dir = { workspace = true }
ash-app-server-daemon = { workspace = true }
ash-app-server = { workspace = true }
process-hardening = { workspace = true }
build-info = { workspace = true }
flate2 = { workspace = true }
fs2 = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
signal-hook = { workspace = true }
tar = { workspace = true }
ureq = { workspace = true }
zip = { workspace = true }
ash-app-server-client = { workspace = true }
ash-app-server-protocol = { workspace = true }
ash-exec = { workspace = true }
ash-install-context = { workspace = true }
ash-protocol = { workspace = true }
ash-product-update = { workspace = true }
ash-remote = { workspace = true }
ash-remote-connections = { workspace = true }
arg0 = { workspace = true }
ash-tui = { workspace = true }

[dev-dependencies]
ash-file-access = { workspace = true }
ash-fast-regex-search = { workspace = true }
ed25519-dalek = { workspace = true }
insta = { workspace = true }
portable-pty = { workspace = true }
tempfile = { workspace = true }
ash-terminal = { workspace = true }
ash-product-update = { workspace = true, features = ["signing"] }

[lints]
workspace = true
