[package]
name = "ash-queue"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
extension-api = { package = "ash-extension-api", path = "../extension-api" }
extension-items = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
ts-rs = { workspace = true }
thiserror = { workspace = true }
protocol = { package = "ash-protocol", path = "../../protocol" }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
