[package]
name = "zeta-protocol"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_protocol"
path = "src/lib.rs"

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
ts-rs = { workspace = true }
zeta-workspace = { workspace = true }

[lints]
workspace = true
