load("//:defs.bzl", "zeta_rust_binary")
load("//bazel/platforms:release_binaries.bzl", "multiplatform_binaries")

zeta_rust_binary(
    name = "zeta",
    crate_name = "zeta",
    crate_root = "src/main.rs",
    deps = [],
)

alias(
    name = "cli",
    actual = ":zeta",
)

multiplatform_binaries(name = "zeta")
