[package]
name = "ash-config"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_config"
path = "src/lib.rs"

[features]
schema = ["dep:schemars", "ash-execpolicy/schema"]

[dependencies]
schemars = { workspace = true, optional = true }
features = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
toml = { workspace = true }
ash-model-provider-config = { workspace = true }
ash-execpolicy = { workspace = true }
ash-protocol = { workspace = true }
plugin = { package = "ash-plugin", path = "../plugin" }
ash-state = { workspace = true }
ash-file-access = { workspace = true }

[lints]
workspace = true
