[package]
name = "zeta-keyring-store"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_keyring_store"
path = "src/lib.rs"

[dependencies]
keyring = { workspace = true, features = ["crypto-rust"] }
sha2 = { workspace = true }
zeta-secrets = { path = "../secrets" }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { workspace = true, features = ["linux-native-async-persistent"] }

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { workspace = true, features = ["apple-native"] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { workspace = true, features = ["windows-native"] }

[target.'cfg(any(target_os = "freebsd", target_os = "openbsd"))'.dependencies]
keyring = { workspace = true, features = ["sync-secret-service"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
