[package]
name = "ash-sleep"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false

[dependencies]
serde_json = { workspace = true }
async-utils = { package = "ash-async-utils", path = "../../async-utils", features = ["wait"] }
extension-api = { package = "ash-extension-api", path = "../extension-api" }
tools = { package = "ash-tools", path = "../../tools" }
extension-items = { workspace = true }

[dev-dependencies]
protocol = { package = "ash-protocol", path = "../../protocol" }
pollster = { workspace = true }

[lints]
workspace = true
