import { registerColor } from "../colorRegistry.js";
import { foreground, mutedForeground, widgetBorder } from "./baseColors.js";

const owner = "platform.theme.components";
const color = (id: string, dark: string, light: string, description: string): string => registerColor(id, { dark, light }, { description, owner });
const alias = (id: string, value: string, description: string): string => registerColor(id, { dark: value, light: value }, { description, owner });

export const inputForeground = alias("input.foreground", foreground, "Input text foreground.");
export const inputBackground = color("input.background", "#313131", "#ffffff", "Input background.");
export const inputBorder = color("input.border", "#3c3c3c", "#cecece", "Input border.");
export const inputPlaceholderForeground = alias("input.placeholderForeground", mutedForeground, "Input placeholder foreground.");
export const selectionForeground = color("selection.foreground", "#ffffff", "#000000", "Selected text foreground.");
export const selectionBackground = color("selection.background", "#264f78", "#add6ff", "Selected text background.");
export const hoverForeground = color("hover.foreground", "#f5f5f7", "#f5f5f7", "Foreground for managed Hovers.");
export const hoverBackground = color("hover.background", "#2d2e33", "#2d2e33", "Background for managed Hovers.");
export const hoverBorder = color("hover.border", "#ffffff18", "#ffffff18", "Border around managed Hovers.");
export const hoverShadow = color("hover.shadow", "#00000030", "#00000030", "Shadow around managed Hovers.");
export const listHoverBackground = color("list.hoverBackground", "#2a2d2e", "#e8e8e8", "Hovered list row background.");
export const listActiveSelectionForeground = color("list.activeSelectionForeground", "#ffffff", "#ffffff", "Active list selection foreground.");
export const listActiveSelectionBackground = color("list.activeSelectionBackground", "#04395e", "#0060c0", "Active list selection background.");
export const treeIndentGuidesStroke = color("tree.indentGuidesStroke", "#585858", "#a9a9a9", "Tree indentation guide stroke.");
export const menuForeground = color("menu.foreground", "#cccccc", "#000000", "Command menu item foreground.");
export const menuSelectionForeground = alias("menu.selectionForeground", foreground, "Selected menu item foreground.");
export const menuSelectionBackground = alias("menu.selectionBackground", listHoverBackground, "Selected menu item background.");
export const menuBackground = color("menu.background", "#252526", "#ffffff", "Command menu background.");
export const menuHoverBackground = color("menu.hoverBackground", "#45454b", "#e2e2e4", "Hovered command menu item background.");
export const buttonForeground = alias("button.foreground", foreground, "Default button foreground.");
export const buttonBorder = alias("button.border", foreground, "Border around buttons that request an explicit outline.");
export const buttonBackground = color("button.background", "#0e639c", "#0078d4", "Default button background.");
export const buttonHoverBackground = alias("button.hoverBackground", listHoverBackground, "Hovered button background.");
export const buttonActiveBackground = color("button.activeBackground", "#37373d", "#dcdcdc", "Pressed button background.");
export const actionBarBackground = color("actionBar.background", "#313136", "#f5f5f6", "Background behind an inline ActionBar.");
export const actionBarToggledBackground = color("actionBar.toggledBackground", "#37373d", "#E4E6F2", "Background for a checked ActionBar item.");
export const tabListHoverBackground = color("tabList.hoverBackground", "#45454b", "#e2e2e4", "Background for a hovered TabList tab.");
export const tabListActiveBackground = alias("tabList.activeBackground", listActiveSelectionBackground, "Background for a selected TabList tab.");
export const buttonSecondaryBackground = color("button.secondaryBackground", "#3a3d41", "#e5e5e5", "Secondary button background.");
export const primaryButtonForeground = color("button.primaryForeground", "#ffffff", "#ffffff", "Primary button foreground.");
export const primaryButtonBackground = alias("button.primaryBackground", buttonBackground, "Primary button background.");
export const primaryButtonHoverBackground = color("button.primaryHoverBackground", "#1177bb", "#006cbe", "Hovered primary button background.");
export const toolbarHoverBackground = color("toolbar.hoverBackground", "#5a5d5e50", "#5a5d5e29", "Hovered toolbar item background.");
export const keybindingLabelForeground = color("keybindingLabel.foreground", "#cccccc", "#555555", "Keybinding label foreground.");
export const keybindingLabelBackground = color("keybindingLabel.background", "#8080802b", "#dddddd66", "Keybinding label background.");
export const keybindingLabelBorder = color("keybindingLabel.border", "#80808033", "#cccccc66", "Keybinding label border.");
export const keybindingLabelBottomBorder = color("keybindingLabel.bottomBorder", "#6b6b6b", "#b0b0b0", "Keybinding label bottom border.");
export const scrollbarSliderBackground = color("scrollbar.sliderBackground", "#79797966", "#64646433", "Scrollbar slider background.");
export const scrollbarSliderHoverBackground = color("scrollbar.sliderHoverBackground", "#646464b3", "#64646459", "Hovered scrollbar slider background.");
export const scrollbarSliderActiveBackground = color("scrollbar.sliderActiveBackground", "#bfbfbf66", "#00000033", "Active scrollbar slider background.");
export const dialogBackground = color("dialog.background", "#252526", "#ffffff", "Dialog background.");
export const dialogBorder = alias("dialog.border", widgetBorder, "Dialog border.");
export const dialogBackdropBackground = color("dialog.backdropBackground", "#00000073", "#00000059", "Backdrop behind modal dialogs.");
export const dialogShadow = color("dialog.shadow", "#00000073", "#0000003d", "Shadow around modal dialogs.");
export const quickInputBackground = color("quickInput.background", "#252526", "#f8f8f8", "Quick input background.");
export const quickInputBackdropBackground = color("quickInput.backdropBackground", "#00000026", "#0000001f", "Backdrop behind quick input.");
export const textLinkActiveForeground = color("textLink.activeForeground", "#4e94ce", "#006ab1", "Foreground for active links and link-like editor actions.");
export const textCodeBlockBackground = color("text.codeBlockBackground", "#0f0f0f", "#f2f2f2", "Inline and block code background.");
export const searchMatchBackground = color("search.matchBackground", "#f9c74f8c", "#f9c74f8c", "Highlighted search match background.");
