[package]
name = "zeta-cli"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[[bin]]
name = "zeta"
path = "src/main.rs"

[dependencies]
zeta-app-server = { workspace = true }
zeta-app-server-client = { workspace = true }
zeta-app-server-protocol = { workspace = true }
zeta-mcp-server = { workspace = true }
zeta-protocol = { workspace = true }
zeta-tui = { workspace = true }

[lints]
workspace = true
