// Generated by `zeta-app-server-protocol generate_protocol`. Do not edit.
export const APP_SERVER_PROTOCOL_MAJOR = 4 as const;
export const APP_SERVER_PROTOCOL_REVISION = 1 as const;
export const APP_SERVER_CAPABILITY_VERSION = 5 as const;
export const APP_SERVER_SCHEMA_HASH = "sha256:4c07f3c4d2f217b289895442346c4921f4dc2c74a48108b95be2061757ae40a7" as const;
export type JsonRpcVersion = "2.0";
export type JsonRpcId = number | string | null;
export type JsonRpcRequest<P> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; method: string; params: P };
export type JsonRpcNotification<P> = { jsonrpc: JsonRpcVersion; method: string; params: P };
export type JsonRpcSuccess<R> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; result: R };
export type JsonRpcFailure<E> = { jsonrpc: JsonRpcVersion; id: JsonRpcId; error: E };
export type JsonRpcResponse<R, E> = JsonRpcSuccess<R> | JsonRpcFailure<E>;
export type JsonRpcError = { code: number; message: string; data: unknown };
