load("//app:defs.bzl", "app_rust_library")

app_rust_library(
    name = "settings",
    crate_name = "zeta_settings",
    crate_root = "lib.rs",
    package_name = "app/settings",
    source_globs = [
        "*.rs",
        "keybindings/*.rs",
        "remote/*.rs",
    ],
    unit_tests = True,
)
