[package]
name = "zeta-sprite"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[features]
default = ["compiler"]
compiler = ["dep:anyhow", "dep:clap", "dep:image", "dep:resvg"]

[lib]
doctest = false
name = "zeta_sprite"
path = "src/lib.rs"

[[bin]]
name = "zeta-sprite"
path = "src/main.rs"
required-features = ["compiler"]

[dependencies]
anyhow = { workspace = true, optional = true }
clap = { workspace = true, features = ["derive"], optional = true }
image = { workspace = true, features = ["png"], optional = true }
resvg = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints.rust]
unsafe_code = "deny"
