[package]
name = "zui"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zui"
path = "src/lib.rs"

[[bin]]
name = "zui-packager"
path = "tools/zui_packager.rs"
required-features = ["native"]

[features]
default = ["wgpu"]
native = [
    "dep:accesskit",
    "dep:accesskit-platform",
    "dep:arboard",
    "dep:base64",
    "dep:ed25519-dalek",
    "dep:futures",
    "dep:global-hotkey",
    "dep:muda",
    "dep:open",
    "dep:raw-window-handle",
    "dep:rfd",
    "dep:semver",
    "dep:serde",
    "dep:serde_json",
    "dep:sha2",
    "dep:tray-icon",
    "dep:url",
    "dep:ureq",
    "dep:winit",
]
wgpu = [
    "native",
    "dep:bytemuck",
    "dep:glyphon",
    "dep:pollster",
    "dep:resvg",
    "dep:wgpu",
]

[dependencies]
accesskit = { workspace = true, optional = true }
accesskit-platform = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
cosmic-text = { workspace = true }
ed25519-dalek = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
global-hotkey = { workspace = true, optional = true }
glyphon = { workspace = true, optional = true }
open = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
resvg = { workspace = true, optional = true }
raw-window-handle = { workspace = true, optional = true }
rfd = { workspace = true, optional = true }
semver = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
sys-locale = { workspace = true }
thiserror = { workspace = true }
unicode-segmentation = { workspace = true }
url = { workspace = true, optional = true }
ureq = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
winit = { workspace = true, optional = true }

[target.'cfg(not(target_os = "android"))'.dependencies]
arboard = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
muda = { workspace = true, optional = true }
tray-icon = { workspace = true, optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
muda = { workspace = true, optional = true }
tray-icon = { workspace = true, optional = true }

[lints]
workspace = true

[dev-dependencies]
tempfile = { workspace = true }
