[package]
name = "zeta-tools"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_tools"
path = "src/lib.rs"

[dependencies]
bm25 = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
zeta-async-utils = { workspace = true }
zeta-protocol = { workspace = true }
zeta-sandboxing = { workspace = true }

[lints]
workspace = true
