[package]
name = "zeta-app-server-transport"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_app_server_transport"
path = "src/lib.rs"

[dependencies]
futures = { workspace = true }
rustix = { workspace = true, features = ["event"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite = { workspace = true }
zeta-app-server-protocol = { workspace = true }
zeta-uds = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
