import "./colorTheme.js";
import { Colors, colorCssVariable } from "./colorRegistry.js";
import { Sizes, sizeCssVariable, sizeToCss } from "./sizeRegistry.js";
import { ColorScheme } from "./theme.js";
import { USER_COLOR_THEME_SCHEMA_URL } from "./userColorTheme.js";

export interface DesignTokenArtifacts {
  readonly manifest: string;
  readonly schema: string;
  readonly catalog: string;
  readonly userThemeSchema: string;
  readonly userThemeTemplate: string;
}

/** Validates every registered token graph and emits deterministic build artifacts. */
export function compileDesignTokenArtifacts(): DesignTokenArtifacts {
  const schemes = [ColorScheme.Dark, ColorScheme.Light, ColorScheme.HighContrastDark, ColorScheme.HighContrastLight];
  const resolved = new Map(schemes.map((scheme) => [scheme, new Map(Colors.resolve(scheme).map(({ id, value }) => [id, value?.toString() ?? null]))]));
  const colors = Colors.getColors().map(({ id, description, owner, needsTransparency = false, deprecated }) => ({
    id,
    kind: "color",
    cssVariable: colorCssVariable(id),
    owner,
    description,
    needsTransparency,
    ...(deprecated ? { deprecated } : {}),
    values: Object.fromEntries(schemes.map((scheme) => [scheme, resolved.get(scheme)!.get(id) ?? null])),
  }));
  const sizes = Sizes.getSizes().map(({ id, description, owner, value, deprecated }) => ({
    id,
    kind: "size",
    cssVariable: sizeCssVariable(id),
    owner,
    description,
    ...(deprecated ? { deprecated } : {}),
    value: sizeToCss(value),
  }));
  const manifestValue = { version: 1, colors, sizes };
  const schemaValue = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://zeta.dev/schemas/design-tokens.schema.json",
    title: "Zeta design token manifest",
    type: "object",
    additionalProperties: false,
    required: ["version", "colors", "sizes"],
    properties: {
      version: { const: 1 },
      colors: { type: "array", items: { $ref: "#/$defs/color" } },
      sizes: { type: "array", items: { $ref: "#/$defs/size" } },
    },
    $defs: {
      common: {
        type: "object",
        required: ["id", "kind", "cssVariable", "owner", "description"],
        properties: {
          id: { type: "string", pattern: "^[a-z][a-zA-Z0-9]*(?:\\.[a-z][a-zA-Z0-9]*)*$" },
          kind: { type: "string" },
          cssVariable: { type: "string", pattern: "^--zeta-" },
          owner: { type: "string", minLength: 1 },
          description: { type: "string", minLength: 1 },
          deprecated: { type: "string" },
        },
      },
      color: {
        allOf: [
          { $ref: "#/$defs/common" },
          {
            type: "object",
            required: ["values", "needsTransparency"],
            properties: {
              kind: { const: "color" },
              needsTransparency: { type: "boolean" },
              values: {
                type: "object",
                additionalProperties: false,
                required: schemes,
                properties: Object.fromEntries(schemes.map((scheme) => [scheme, { type: ["string", "null"] }])),
              },
            },
          },
        ],
      },
      size: {
        allOf: [
          { $ref: "#/$defs/common" },
          {
            type: "object",
            required: ["value"],
            properties: {
              kind: { const: "size" },
              value: { type: "string" },
            },
          },
        ],
      },
    },
  };
  const rows = [
    "# Generated design token catalog",
    "",
    "> Generated by `pnpm tokens:generate`. Do not edit by hand.",
    "",
    `Colors: ${colors.length} · Sizes: ${sizes.length}`,
    "",
    "## Colors",
    "",
    "| Token | Owner | Dark | Light | CSS variable |",
    "| --- | --- | --- | --- | --- |",
    ...colors.map((token) => `| \`${token.id}\` | ${token.owner} | \`${token.values.dark}\` | \`${token.values.light}\` | \`${token.cssVariable}\` |`),
    "",
    "## Sizes",
    "",
    "| Token | Owner | Value | CSS variable |",
    "| --- | --- | --- | --- |",
    ...sizes.map((token) => `| \`${token.id}\` | ${token.owner} | \`${token.value}\` | \`${token.cssVariable}\` |`),
    "",
  ];
  const colorValueReference = { $ref: "#/$defs/colorValue" };
  const transform = (op: string, properties: Record<string, unknown>, required: string[]) => ({
    type: "object",
    additionalProperties: false,
    required: ["op", "value", ...required],
    properties: {
      op: { const: op },
      value: colorValueReference,
      ...properties,
    },
  });
  const userThemeSchemaValue = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: USER_COLOR_THEME_SCHEMA_URL,
    title: "Zeta user color theme",
    type: "object",
    additionalProperties: false,
    required: ["version", "id", "label", "colorScheme", "colors"],
    properties: {
      $schema: { const: USER_COLOR_THEME_SCHEMA_URL },
      version: { const: 1 },
      id: { type: "string", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$" },
      label: { type: "string", minLength: 1, maxLength: 80 },
      colorScheme: { enum: schemes },
      colors: {
        type: "object",
        maxProperties: 512,
        propertyNames: { enum: Colors.getColors().map(({ id }) => id) },
        additionalProperties: colorValueReference,
      },
    },
    $defs: {
      colorValue: {
        anyOf: [
          { type: "string", maxLength: 128, pattern: "^(?:#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})|[a-z][a-zA-Z0-9]*(?:\\.[a-z][a-zA-Z0-9]*)*)$" },
          transform("transparent", { factor: { type: "number", minimum: 0, maximum: 1 } }, ["factor"]),
          transform("lighten", { factor: { type: "number", minimum: 0, maximum: 1 } }, ["factor"]),
          transform("darken", { factor: { type: "number", minimum: 0, maximum: 1 } }, ["factor"]),
          transform("mix", { other: colorValueReference, factor: { type: "number", minimum: 0, maximum: 1 } }, ["other", "factor"]),
          transform("opaque", { background: colorValueReference }, ["background"]),
        ],
      },
    },
  };
  const userThemeTemplateValue = {
    $schema: USER_COLOR_THEME_SCHEMA_URL,
    version: 1,
    id: "my-custom-theme",
    label: "My Custom Theme",
    colorScheme: ColorScheme.Dark,
    colors: {
      "workbench.background": "#0b1020",
      "editor.background": "#0b1020",
      "editor.foreground": "#dbe7ff",
      "sideBar.background": "#10172a",
      "auxiliaryBar.background": "sideBar.background",
      "panel.background": "sideBar.background",
      "titleBar.background": "#080d18",
      "titleBar.foreground": "#edf4ff",
      "titleBar.actionForeground": "#dbe7ff",
      "input.background": "#18223a",
      "input.border": "#31446d",
      focusBorder: "#7aa2f7",
      "accent.foreground": "#89b4fa",
      "button.primaryBackground": "#4169a8",
      "button.primaryHoverBackground": "#527bbd",
      "selection.background": "#29466f",
      "list.activeSelectionBackground": "#29466f",
      "toolbar.hoverBackground": {
        op: "transparent",
        value: "#ffffff",
        factor: 0.2,
      },
    },
  };
  return {
    manifest: `${JSON.stringify(manifestValue, null, 2)}\n`,
    schema: `${JSON.stringify(schemaValue, null, 2)}\n`,
    catalog: `${rows.join("\n")}\n`,
    userThemeSchema: `${JSON.stringify(userThemeSchemaValue, null, 2)}\n`,
    userThemeTemplate: `${JSON.stringify(userThemeTemplateValue, null, 2)}\n`,
  };
}
