[package]
name = "zeta-model-tokenizer"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_model_tokenizer"
path = "src/lib.rs"

[dependencies]
hf-chat-template = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokenizers = { workspace = true }
zeta-http-client = { workspace = true }
zeta-protocol = { workspace = true }
zeta-utils-path = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
