[package]
name = "zeta-codex-app-server"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_codex_app_server"
path = "src/lib.rs"

[dependencies]
serde_json = { workspace = true }
sha2 = { workspace = true }
zeta-app-server-transport = { workspace = true }
zeta-core = { workspace = true }
zeta-login = { workspace = true }
zeta-protocol = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
