[package]
name = "zeta-model-provider"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_model_provider"
path = "src/lib.rs"

[dependencies]
zeta-api = { workspace = true }
zeta-async-utils = { workspace = true }
zeta-client = { workspace = true }
zeta-context-engine = { workspace = true }
zeta-http-client = { workspace = true }
zeta-model-provider-config = { workspace = true }
zeta-protocol = { workspace = true }
zeta-secrets = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
