[package]
name = "zeta-model-provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
name = "zeta_model_provider"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
zeta-api = { workspace = true }
zeta-core = { workspace = true }
zeta-credentials = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
