[package]
name = "zeta-editor-core"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_editor_core"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
