/** Stable DOM-free API for programmatic line-oriented and structured-document consumers. */
export { TextPosition } from "./common/core/position.js";
export type { IPosition } from "./common/core/position.js";
export { TextRange } from "./common/core/range.js";
export type { IRange } from "./common/core/range.js";
export type { ITextRange } from "./common/core/range.js";
export { SelectionDirection } from "./common/core/selection.js";
export { TextSelection } from "./common/core/selection.js";
export type { ISelection } from "./common/core/selection.js";
export { TextModel } from "./common/model/textModel.js";
export type { TextEditOptions } from "./common/model/textModel.js";
export type { TextModelHistoryLimit } from "./common/model/textModel.js";
export type { TextModelMaintenanceOptions } from "./common/model/textModel.js";
export type { TextModelOptions } from "./common/model/textModel.js";
export { DocumentModel } from "./common/model/documentModel.js";
export type { DocumentChange } from "./common/model/documentModel.js";
export type { DocumentModelOptions } from "./common/model/documentModel.js";
export { createDocumentNode } from "./common/model/document.js";
export { createDocumentRoot } from "./common/model/document.js";
export { createTextNode } from "./common/model/document.js";
export type { DocumentAttributes } from "./common/model/document.js";
export type { DocumentMark } from "./common/model/document.js";
export type { DocumentNode } from "./common/model/document.js";
export type { DocumentNodeId } from "./common/model/document.js";
export { createDefaultDocumentSchema } from "./common/model/documentSchema.js";
export { DocumentSchema } from "./common/model/documentSchema.js";
export type { DocumentSchemaOptions } from "./common/model/documentSchema.js";
export { DocumentTransaction } from "./common/model/documentTransaction.js";
export type { DocumentStep } from "./common/model/documentTransaction.js";
export { DocumentSerializationError } from "./common/model/documentSerialization.js";
export { deserializeDocument } from "./common/model/documentSerialization.js";
export { serializeDocument } from "./common/model/documentSerialization.js";
export { allSelection } from "./common/core/documentSelection.js";
export { nodeSelection } from "./common/core/documentSelection.js";
export { textSelection } from "./common/core/documentSelection.js";
export type { DocumentSelection } from "./common/core/documentSelection.js";
