[package]
name = "zeta-websocket-client"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_websocket_client"
path = "src/lib.rs"

[dependencies]
base64 = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net", "time"] }
tokio-tungstenite = { workspace = true }
url = { workspace = true }
zeta-http-client = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
