[package]
name = "zeta-app-server-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
name = "zeta_app_server_protocol"
path = "src/lib.rs"

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
ts-rs = { workspace = true }
zeta-protocol = { workspace = true }

[lints]
workspace = true
