[package]
name = "zeta-marketplace-client"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_marketplace_client"
path = "src/lib.rs"

[dependencies]
flate2.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tough.workspace = true
url.workspace = true
zip.workspace = true

[lints]
workspace = true
