[package]
name = "zeta-config-schema"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
config = { package = "zeta-config", path = "../config", features = ["schema"] }
schemars = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
