[package]
name = "zeta-workspace-index-storage"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_workspace_index_storage"
path = "src/lib.rs"

[dependencies]
fs2 = { workspace = true }
zeta-workspace = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
