[package]
name = "zeta-wgpu"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_wgpu"
path = "src/lib.rs"

[dependencies]
bytemuck = { workspace = true }
glyphon = { workspace = true }
pollster = { workspace = true }
resvg = { workspace = true }
thiserror = { workspace = true }
wgpu = { workspace = true }
zeta-icon = { workspace = true }
zeta-renderer = { workspace = true }
zeta-winit = { workspace = true }
zui = { workspace = true }

[dev-dependencies]
zeta-icons = { workspace = true }

[lints]
workspace = true
