[package]
name = "zeta-app-server-client"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "zeta_app_server_client"
path = "src/lib.rs"

[dependencies]
queue = { workspace = true }
diagnostics = { workspace = true }
feedback = { workspace = true }
base64 = { workspace = true }
zeta-memory-diagnostics = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zeroize = { workspace = true }
zeta-app-server = { workspace = true }
zeta-app-server-protocol = { workspace = true }
zeta-app-server-transport = { workspace = true }
zeta-client = { workspace = true }
zeta-install-context = { workspace = true }
zeta-protocol = { workspace = true }
zeta-file-access = { workspace = true }

[lints]
workspace = true

[target.'cfg(windows)'.dependencies]
zeta-utils-pty = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
zeta-async-utils = { workspace = true }
zeta-core = { workspace = true }
