[package]
name = "zeta-mxc-sandbox"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
name = "mxc_sandbox"
doctest = false

[dependencies]
log = { workspace = true }
mxc-sdk = { workspace = true }
dunce = { workspace = true }
zeta-install-context = { workspace = true }
zeta-sandboxing = { workspace = true }
zeta-file-access = { workspace = true }

[target.'cfg(windows)'.dependencies]
tracelogging = "=1.2.3"

[dev-dependencies]
zeta-protocol = { workspace = true }
zeta-tool-executor = { workspace = true }
zeta-async-utils = { workspace = true }
network-proxy = { workspace = true, features = ["server"] }
tempfile = { workspace = true }

[lints]
workspace = true
