[package]
name = "zeta-workspace-access"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
readme = "README.md"

[lib]
doctest = false
name = "zeta_workspace_access"
path = "src/lib.rs"

[dependencies]
zeta-workspace = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
