[package]
name = "zeta-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
name = "zeta_tui"
path = "src/lib.rs"

[dependencies]
crossterm = { workspace = true }
ratatui = { workspace = true }
unicode-width = { workspace = true }
zeta-app-server-client = { workspace = true }
zeta-app-server-protocol = { workspace = true }
zeta-protocol = { workspace = true }

[lints]
workspace = true
