[package]
name = "ash-async-utils"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_async_utils"
path = "src/lib.rs"

[lints]
workspace = true

[features]
wait = ["dep:async-io", "dep:event-listener"]

[dependencies]
async-io = { workspace = true, optional = true }
event-listener = { workspace = true, optional = true }

[dev-dependencies]
pollster = { workspace = true }
