[package]
name = "ash-app-server-client"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false
name = "ash_app_server_client"
path = "src/lib.rs"

[dependencies]
memories = { workspace = true }
queue = { workspace = true }
diagnostics = { workspace = true }
feedback = { workspace = true }
base64 = { workspace = true }
ash-memory-diagnostics = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
zeroize = { workspace = true }
ash-app-server = { workspace = true }
ash-app-server-protocol = { workspace = true }
ash-app-server-transport = { workspace = true }
ash-client = { workspace = true }
ash-protocol = { workspace = true }
ash-file-access = { workspace = true }

[lints]
workspace = true

[target.'cfg(windows)'.dependencies]
ash-utils-pty = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
ash-async-utils = { workspace = true }
ash-core = { workspace = true }
