load("//:defs.bzl", "ash_rust_crate", "ash_rust_binary")

ash_rust_crate(
    name = "config-schema",
    crate_name = "ash_config_schema",
    data = ["//ash-rs/config:schema.json"],
)
ash_rust_binary(
    name = "generate",
    crate_name = "ash_config_schema",
    crate_root = "src/main.rs",
    deps = [":config-schema"],
)
