// Generated from resources/icons by build/zeterm/syncRustIcons.ts.
// Do not edit this file directly.

use crate::IconDefinition;

// Canonical artwork can exist before a product semantic is registered.
#[allow(dead_code)]
#[rustfmt::skip]
pub(crate) mod artwork {
    use super::IconDefinition;
    pub(crate) const ACCOUNT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/account.svg"));
    pub(crate) const ADD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/add.svg"));
    pub(crate) const ADD_SMALL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/add-small.svg"));
    pub(crate) const AGENT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/agent.svg"));
    pub(crate) const AGENT_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/agent-filled.svg"));
    pub(crate) const ALIGN_CENTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/align-center.svg"));
    pub(crate) const ALIGN_JUSTIFIED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/align-justified.svg"));
    pub(crate) const ALIGN_LEFT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/align-left.svg"));
    pub(crate) const ALIGN_RIGHT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/align-right.svg"));
    pub(crate) const APPEARANCE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/appearance.svg"));
    pub(crate) const ARCHIVE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/archive.svg"));
    pub(crate) const ARROW_DOWN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/arrow-down.svg"));
    pub(crate) const ARROW_LEFT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/arrow-left.svg"));
    pub(crate) const ARROW_RIGHT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/arrow-right.svg"));
    pub(crate) const ARROW_UP: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/arrow-up.svg"));
    pub(crate) const BELL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/bell.svg"));
    pub(crate) const BELL_DOT: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/bell-dot.svg"));
    pub(crate) const BELL_SLASH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/bell-slash.svg"));
    pub(crate) const BOLD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/bold.svg"));
    pub(crate) const BOOK: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/book.svg"));
    pub(crate) const BOOKS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/books.svg"));
    pub(crate) const BROWSER_EXPLORE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/browser-explore.svg"));
    pub(crate) const BROWSER_WEB: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/browser-web.svg"));
    pub(crate) const CALENDAR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/calendar.svg"));
    pub(crate) const CHART: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chart.svg"));
    pub(crate) const CHAT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat.svg"));
    pub(crate) const CHAT_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chat-filled.svg"));
    pub(crate) const CHECK: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/check.svg"));
    pub(crate) const CHEVRON_DOWN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chevron-down.svg"));
    pub(crate) const CHEVRON_LEFT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chevron-left.svg"));
    pub(crate) const CHEVRON_RIGHT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chevron-right.svg"));
    pub(crate) const CHEVRON_UP: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/chevron-up.svg"));
    pub(crate) const CLAUDE: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/claude.svg"));
    pub(crate) const CLOSE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/close.svg"));
    pub(crate) const CODE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/code.svg"));
    pub(crate) const COMMAND: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/command.svg"));
    pub(crate) const COPY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/copy.svg"));
    pub(crate) const COPY_CODE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/copy-code.svg"));
    pub(crate) const CSV: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/csv.svg"));
    pub(crate) const CSV_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/csv-filled.svg"));
    pub(crate) const CSV_GREEN: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/csv-green.svg"));
    pub(crate) const CSV_LETTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/csv-letter.svg"));
    pub(crate) const CSV_LETTER_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/csv-letter-filled.svg"));
    pub(crate) const CURSOR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/cursor.svg"));
    pub(crate) const CURSOR_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/cursor-filled.svg"));
    pub(crate) const CUSTOMIZE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/customize.svg"));
    pub(crate) const CUSTOMIZE_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/customize-filled.svg"));
    pub(crate) const DATABASE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/database.svg"));
    pub(crate) const DATABASE_FLAT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/database-flat.svg"));
    pub(crate) const DIAGNOSTICS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/diagnostics.svg"));
    pub(crate) const DIFF: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/diff.svg"));
    pub(crate) const DISCARD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/discard.svg"));
    pub(crate) const DOCX: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/docx.svg"));
    pub(crate) const DOCX_BLUE: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/docx-blue.svg"));
    pub(crate) const DOCX_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/docx-filled.svg"));
    pub(crate) const DOWNLOAD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/download.svg"));
    pub(crate) const DOWNLOAD_BOX: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/download-box.svg"));
    pub(crate) const DOWNLOAD_TRAY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/download-tray.svg"));
    pub(crate) const EDIT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/edit.svg"));
    pub(crate) const ELLIPSIS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/ellipsis.svg"));
    pub(crate) const ENTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/enter.svg"));
    pub(crate) const ERASER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/eraser.svg"));
    pub(crate) const EXPORT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/export.svg"));
    pub(crate) const EXPORT_TRAY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/export-tray.svg"));
    pub(crate) const EYE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/eye.svg"));
    pub(crate) const EYE_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/eye-filled.svg"));
    pub(crate) const FILE_DOWNLOADED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/file-downloaded.svg"));
    pub(crate) const FILE_TEXT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/file-text.svg"));
    pub(crate) const FILES: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/files.svg"));
    pub(crate) const FILTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/filter.svg"));
    pub(crate) const FOLD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/fold.svg"));
    pub(crate) const FOLDER_DOWNLOADED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/folder-downloaded.svg"));
    pub(crate) const GEAR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/gear.svg"));
    pub(crate) const GIT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git.svg"));
    pub(crate) const GIT_BRANCH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-branch.svg"));
    pub(crate) const GIT_COMMIT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/git-commit.svg"));
    pub(crate) const H1: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h1.svg"));
    pub(crate) const H2: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h2.svg"));
    pub(crate) const H3: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h3.svg"));
    pub(crate) const H4: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h4.svg"));
    pub(crate) const H5: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/h5.svg"));
    pub(crate) const HISTORY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/history.svg"));
    pub(crate) const HOME: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/home.svg"));
    pub(crate) const IMAGE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/image.svg"));
    pub(crate) const IMAGE_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/image-filled.svg"));
    pub(crate) const INFO: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/info.svg"));
    pub(crate) const ITALICS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/italics.svg"));
    pub(crate) const LAYOUT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout.svg"));
    pub(crate) const LAYOUT_PANEL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-panel.svg"));
    pub(crate) const LAYOUT_PANEL_OFF: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/layout-panel-off.svg"));
    pub(crate) const LAYOUT_SIDEBAR_LEFT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-left.svg"));
    pub(crate) const LAYOUT_SIDEBAR_LEFT_OFF: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/layout-sidebar-left-off.svg"));
    pub(crate) const LAYOUT_SIDEBAR_LEFT_OFF_EMPTY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-left-off-empty.svg"));
    pub(crate) const LAYOUT_SIDEBAR_RIGHT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-right.svg"));
    pub(crate) const LAYOUT_SIDEBAR_RIGHT_OFF: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/layout-sidebar-right-off.svg"));
    pub(crate) const LAYOUT_SIDEBAR_RIGHT_OFF_EMPTY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/layout-sidebar-right-off-empty.svg"));
    pub(crate) const LEGEND: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/legend.svg"));
    pub(crate) const LETTER_B: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/letter-b.svg"));
    pub(crate) const LETTER_H: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/letter-h.svg"));
    pub(crate) const LETTER_T: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/letter-t.svg"));
    pub(crate) const LIBRARY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/library.svg"));
    pub(crate) const LIGHTNING: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/lightning.svg"));
    pub(crate) const LIGHTNING_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/lightning-filled.svg"));
    pub(crate) const LINK_EXTERNAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/link-external.svg"));
    pub(crate) const LIST_FILTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/list-filter.svg"));
    pub(crate) const LIST_UNORDERED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/list-unordered.svg"));
    pub(crate) const MENU: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/menu.svg"));
    pub(crate) const MODEL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/model.svg"));
    pub(crate) const MODEL_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/model-filled.svg"));
    pub(crate) const NEW_FILE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/new-file.svg"));
    pub(crate) const NEW_FOLDER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/new-folder.svg"));
    pub(crate) const OPENAI: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/openai.svg"));
    pub(crate) const ORIGIN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/origin.svg"));
    pub(crate) const PARAMETERS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/parameters.svg"));
    pub(crate) const PASS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pass.svg"));
    pub(crate) const PASS_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pass-filled.svg"));
    pub(crate) const PAUSE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pause.svg"));
    pub(crate) const PDF: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pdf.svg"));
    pub(crate) const PDF_FILLED: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/pdf-filled.svg"));
    pub(crate) const PDF_RED: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/pdf-red.svg"));
    pub(crate) const PINNED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/pinned.svg"));
    pub(crate) const PREVIEW: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/preview.svg"));
    pub(crate) const PROJECTS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/projects.svg"));
    pub(crate) const PROJECTS_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/projects-filled.svg"));
    pub(crate) const QUOTE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/quote.svg"));
    pub(crate) const QUOTES: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/quotes.svg"));
    pub(crate) const REFRESH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/refresh.svg"));
    pub(crate) const REMOVE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/remove.svg"));
    pub(crate) const REMOVE_SMALL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/remove-small.svg"));
    pub(crate) const REPO_FETCH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/repo-fetch.svg"));
    pub(crate) const REPO_PULL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/repo-pull.svg"));
    pub(crate) const REPO_PUSH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/repo-push.svg"));
    pub(crate) const RSS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/rss.svg"));
    pub(crate) const SANDBOX: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/sandbox.svg"));
    pub(crate) const SAVE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/save.svg"));
    pub(crate) const SCREEN_FULL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/screen-full.svg"));
    pub(crate) const SCREEN_NORMAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/screen-normal.svg"));
    pub(crate) const SEARCH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/search.svg"));
    pub(crate) const SETTINGS: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/settings.svg"));
    pub(crate) const SPLIT_HORIZONTAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/split-horizontal.svg"));
    pub(crate) const SPLIT_PAGE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/split-page.svg"));
    pub(crate) const SPLIT_VERTICAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/split-vertical.svg"));
    pub(crate) const STAR: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/star.svg"));
    pub(crate) const STAR_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/star-filled.svg"));
    pub(crate) const START: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/start.svg"));
    pub(crate) const SUMMARY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/summary.svg"));
    pub(crate) const SYNC: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/sync.svg"));
    pub(crate) const TABLE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/table.svg"));
    pub(crate) const TARGET: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/target.svg"));
    pub(crate) const TERMINAL: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/terminal.svg"));
    pub(crate) const TERMINAL_CMD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/terminal-cmd.svg"));
    pub(crate) const TERMINAL_GIT_BASH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/terminal-git-bash.svg"));
    pub(crate) const TEXT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/text.svg"));
    pub(crate) const TRANSLATE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/translate.svg"));
    pub(crate) const TRASH: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/trash.svg"));
    pub(crate) const TRASH_FLAT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/trash-flat.svg"));
    pub(crate) const TXT_LETTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/txt-letter.svg"));
    pub(crate) const TXT_LETTER_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/txt-letter-filled.svg"));
    pub(crate) const TYPOGRAPHY: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/typography.svg"));
    pub(crate) const UNDERLINE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/underline.svg"));
    pub(crate) const UNFOLD: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/unfold.svg"));
    pub(crate) const UNPIN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/unpin.svg"));
    pub(crate) const WARNING: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/warning.svg"));
    pub(crate) const WRITE: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/write.svg"));
    pub(crate) const XLS_GREEN: IconDefinition = IconDefinition::multicolor(include_bytes!("../../../resources/icons/xls-green.svg"));
    pub(crate) const XLS_LETTER: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/xls-letter.svg"));
    pub(crate) const XLS_LETTER_FILLED: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/xls-letter-filled.svg"));
    pub(crate) const ZOOM_IN: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/zoom-in.svg"));
    pub(crate) const ZOOM_OUT: IconDefinition = IconDefinition::symbolic(include_bytes!("../../../resources/icons/zoom-out.svg"));
}

#[cfg(test)]
#[rustfmt::skip]
pub(crate) const ALL_ARTWORK: &[(&str, IconDefinition)] = &[
    ("account", artwork::ACCOUNT),
    ("add", artwork::ADD),
    ("add-small", artwork::ADD_SMALL),
    ("agent", artwork::AGENT),
    ("agent-filled", artwork::AGENT_FILLED),
    ("align-center", artwork::ALIGN_CENTER),
    ("align-justified", artwork::ALIGN_JUSTIFIED),
    ("align-left", artwork::ALIGN_LEFT),
    ("align-right", artwork::ALIGN_RIGHT),
    ("appearance", artwork::APPEARANCE),
    ("archive", artwork::ARCHIVE),
    ("arrow-down", artwork::ARROW_DOWN),
    ("arrow-left", artwork::ARROW_LEFT),
    ("arrow-right", artwork::ARROW_RIGHT),
    ("arrow-up", artwork::ARROW_UP),
    ("bell", artwork::BELL),
    ("bell-dot", artwork::BELL_DOT),
    ("bell-slash", artwork::BELL_SLASH),
    ("bold", artwork::BOLD),
    ("book", artwork::BOOK),
    ("books", artwork::BOOKS),
    ("browser-explore", artwork::BROWSER_EXPLORE),
    ("browser-web", artwork::BROWSER_WEB),
    ("calendar", artwork::CALENDAR),
    ("chart", artwork::CHART),
    ("chat", artwork::CHAT),
    ("chat-filled", artwork::CHAT_FILLED),
    ("check", artwork::CHECK),
    ("chevron-down", artwork::CHEVRON_DOWN),
    ("chevron-left", artwork::CHEVRON_LEFT),
    ("chevron-right", artwork::CHEVRON_RIGHT),
    ("chevron-up", artwork::CHEVRON_UP),
    ("claude", artwork::CLAUDE),
    ("close", artwork::CLOSE),
    ("code", artwork::CODE),
    ("command", artwork::COMMAND),
    ("copy", artwork::COPY),
    ("copy-code", artwork::COPY_CODE),
    ("csv", artwork::CSV),
    ("csv-filled", artwork::CSV_FILLED),
    ("csv-green", artwork::CSV_GREEN),
    ("csv-letter", artwork::CSV_LETTER),
    ("csv-letter-filled", artwork::CSV_LETTER_FILLED),
    ("cursor", artwork::CURSOR),
    ("cursor-filled", artwork::CURSOR_FILLED),
    ("customize", artwork::CUSTOMIZE),
    ("customize-filled", artwork::CUSTOMIZE_FILLED),
    ("database", artwork::DATABASE),
    ("database-flat", artwork::DATABASE_FLAT),
    ("diagnostics", artwork::DIAGNOSTICS),
    ("diff", artwork::DIFF),
    ("discard", artwork::DISCARD),
    ("docx", artwork::DOCX),
    ("docx-blue", artwork::DOCX_BLUE),
    ("docx-filled", artwork::DOCX_FILLED),
    ("download", artwork::DOWNLOAD),
    ("download-box", artwork::DOWNLOAD_BOX),
    ("download-tray", artwork::DOWNLOAD_TRAY),
    ("edit", artwork::EDIT),
    ("ellipsis", artwork::ELLIPSIS),
    ("enter", artwork::ENTER),
    ("eraser", artwork::ERASER),
    ("export", artwork::EXPORT),
    ("export-tray", artwork::EXPORT_TRAY),
    ("eye", artwork::EYE),
    ("eye-filled", artwork::EYE_FILLED),
    ("file-downloaded", artwork::FILE_DOWNLOADED),
    ("file-text", artwork::FILE_TEXT),
    ("files", artwork::FILES),
    ("filter", artwork::FILTER),
    ("fold", artwork::FOLD),
    ("folder-downloaded", artwork::FOLDER_DOWNLOADED),
    ("gear", artwork::GEAR),
    ("git", artwork::GIT),
    ("git-branch", artwork::GIT_BRANCH),
    ("git-commit", artwork::GIT_COMMIT),
    ("h1", artwork::H1),
    ("h2", artwork::H2),
    ("h3", artwork::H3),
    ("h4", artwork::H4),
    ("h5", artwork::H5),
    ("history", artwork::HISTORY),
    ("home", artwork::HOME),
    ("image", artwork::IMAGE),
    ("image-filled", artwork::IMAGE_FILLED),
    ("info", artwork::INFO),
    ("italics", artwork::ITALICS),
    ("layout", artwork::LAYOUT),
    ("layout-panel", artwork::LAYOUT_PANEL),
    ("layout-panel-off", artwork::LAYOUT_PANEL_OFF),
    ("layout-sidebar-left", artwork::LAYOUT_SIDEBAR_LEFT),
    ("layout-sidebar-left-off", artwork::LAYOUT_SIDEBAR_LEFT_OFF),
    ("layout-sidebar-left-off-empty", artwork::LAYOUT_SIDEBAR_LEFT_OFF_EMPTY),
    ("layout-sidebar-right", artwork::LAYOUT_SIDEBAR_RIGHT),
    ("layout-sidebar-right-off", artwork::LAYOUT_SIDEBAR_RIGHT_OFF),
    ("layout-sidebar-right-off-empty", artwork::LAYOUT_SIDEBAR_RIGHT_OFF_EMPTY),
    ("legend", artwork::LEGEND),
    ("letter-b", artwork::LETTER_B),
    ("letter-h", artwork::LETTER_H),
    ("letter-t", artwork::LETTER_T),
    ("library", artwork::LIBRARY),
    ("lightning", artwork::LIGHTNING),
    ("lightning-filled", artwork::LIGHTNING_FILLED),
    ("link-external", artwork::LINK_EXTERNAL),
    ("list-filter", artwork::LIST_FILTER),
    ("list-unordered", artwork::LIST_UNORDERED),
    ("menu", artwork::MENU),
    ("model", artwork::MODEL),
    ("model-filled", artwork::MODEL_FILLED),
    ("new-file", artwork::NEW_FILE),
    ("new-folder", artwork::NEW_FOLDER),
    ("openai", artwork::OPENAI),
    ("origin", artwork::ORIGIN),
    ("parameters", artwork::PARAMETERS),
    ("pass", artwork::PASS),
    ("pass-filled", artwork::PASS_FILLED),
    ("pause", artwork::PAUSE),
    ("pdf", artwork::PDF),
    ("pdf-filled", artwork::PDF_FILLED),
    ("pdf-red", artwork::PDF_RED),
    ("pinned", artwork::PINNED),
    ("preview", artwork::PREVIEW),
    ("projects", artwork::PROJECTS),
    ("projects-filled", artwork::PROJECTS_FILLED),
    ("quote", artwork::QUOTE),
    ("quotes", artwork::QUOTES),
    ("refresh", artwork::REFRESH),
    ("remove", artwork::REMOVE),
    ("remove-small", artwork::REMOVE_SMALL),
    ("repo-fetch", artwork::REPO_FETCH),
    ("repo-pull", artwork::REPO_PULL),
    ("repo-push", artwork::REPO_PUSH),
    ("rss", artwork::RSS),
    ("sandbox", artwork::SANDBOX),
    ("save", artwork::SAVE),
    ("screen-full", artwork::SCREEN_FULL),
    ("screen-normal", artwork::SCREEN_NORMAL),
    ("search", artwork::SEARCH),
    ("settings", artwork::SETTINGS),
    ("split-horizontal", artwork::SPLIT_HORIZONTAL),
    ("split-page", artwork::SPLIT_PAGE),
    ("split-vertical", artwork::SPLIT_VERTICAL),
    ("star", artwork::STAR),
    ("star-filled", artwork::STAR_FILLED),
    ("start", artwork::START),
    ("summary", artwork::SUMMARY),
    ("sync", artwork::SYNC),
    ("table", artwork::TABLE),
    ("target", artwork::TARGET),
    ("terminal", artwork::TERMINAL),
    ("terminal-cmd", artwork::TERMINAL_CMD),
    ("terminal-git-bash", artwork::TERMINAL_GIT_BASH),
    ("text", artwork::TEXT),
    ("translate", artwork::TRANSLATE),
    ("trash", artwork::TRASH),
    ("trash-flat", artwork::TRASH_FLAT),
    ("txt-letter", artwork::TXT_LETTER),
    ("txt-letter-filled", artwork::TXT_LETTER_FILLED),
    ("typography", artwork::TYPOGRAPHY),
    ("underline", artwork::UNDERLINE),
    ("unfold", artwork::UNFOLD),
    ("unpin", artwork::UNPIN),
    ("warning", artwork::WARNING),
    ("write", artwork::WRITE),
    ("xls-green", artwork::XLS_GREEN),
    ("xls-letter", artwork::XLS_LETTER),
    ("xls-letter-filled", artwork::XLS_LETTER_FILLED),
    ("zoom-in", artwork::ZOOM_IN),
    ("zoom-out", artwork::ZOOM_OUT),
];
